### ISSUE TITLE
Checkbox always checked

### ISSUE THREAD

**Issue by samhermes** [wp-shortcake/shortcake#100]
Once a checkbox is checked, it won't allow you to uncheck it. There doesn't seem to be any update to the shortcode if the box is unchecked, so the value remains true no matter what.

**Comment by danielbachhuber** [comment]
Thanks for the report! I have a good sense of what's causing this — we'll try to get it fixed in the next release.

**Comment by jitendraharpalani58** [comment]
@danielbachhuber @samhermes which checkbox is it? 

@samhermes can you please upload a screenshot?

**Comment by danielbachhuber** [comment]
> which checkbox is it?

I think you'll need to create a sample checkbox field

**Comment by danielbachhuber** [comment]
@samhermes Can you confirm the fix?

**Comment by samhermes** [comment]
Confirmed. Thanks guys!
