### ISSUE TITLE
Wow this looks really interesting!

### ISSUE THREAD

**Issue by paaljoachim** [wp-shortcake/shortcake#101]
Hey

This plugin looks really really interesting! Visible content shortcodes seen in the content creation screen. Awesome!

A few thoughts... (my focus area is design and video tutorials easywebdesigntutorials.com - not much of a developer..... yet...:))
It seems the plugin can experiment with various shortcodes and see what it is able to show and not.
That the plugin could gradually add various shortcodes that work and are seen in the content creation area.
I have the impression right now that it leaves it up to a developer to take the bare bones plugin and extend it with their own shortcodes so that each developer can create their own experimentation.
It would be interesting of having various developers share their own creation.
It seems like a plugin Janneke and a few others would really like to extend.

I am very much looking forward to seeing how things develop. Coming in at a stage where I can help with design and docs (when I grasp how things work).

Have a great day!

**Comment by danielbachhuber** [comment]
> This plugin looks really really interesting!

Thanks!

> I have the impression right now that it leaves it up to a developer to take the bare bones plugin and extend it with their own shortcodes so that each developer can create their own experimentation.

Yep, it requires implementation on a developer's part — not just activate and use.

> It seems like a plugin Janneke and a few others would really like to extend.

We're certainly hoping other people adopt the plugin (and submit bug reports, pull requests, etc. :smile:  )

**Comment by paaljoachim** [comment]
So if a developer makes a test plugin with a few visualized shortcodes I could create an article and a video tutorial showing the future of shortcodes.

Btw
I have e-mailed a few people (wptavern and a few shortcodes plugin developers), posted in the Advanced WordPress group on facebook: 
https://www.facebook.com/groups/advancedwp/
as well as posted in the LinkedIn WordPress Developers group.

This plugin is awesome! Having shortcodes actually showing inside the content creation area will be of big help in creating visualized layouts in the backend of WordPress.
