### ISSUE TITLE
Feature plugin for Core?

### ISSUE THREAD

**Issue by paaljoachim** [wp-shortcake/shortcake#102]
Hey

Just thinking here. It seems this plugin could actually become a feature plugin for core (sometime down the road be added to core).

**Comment by danielbachhuber** [comment]
> It seems this plugin could actually become a feature plugin for core

Yep! That's the idea. Currently, the primary challenge to mitigate is that shortcode UI needs to be manually specified for each shortcode. I'm not sure we'll ever get around that.
