### ISSUE TITLE
Why preview?

### ISSUE THREAD

**Issue by ellatrix** [wp-shortcake/shortcake#104]
I'm not sure why a preview is necessary. The one that I currently see is not a live previews, as in, I don't see a preview as I change stuff. I can understand the use of a live preview, but that's not really doable if you need information from the server (would be different if the shorcode provides a JS template). Now you can just as well update the shortcode (1 click) and edit it again (1 click) instead of preview it (1 click) and edit it again (1 click). Actually, this is a worse experience because when the preview is OK, you still need to update it (1 extra click).

**Comment by danielbachhuber** [comment]
See #61 for the discussion around the original implementation.

The primary justification in my mind is that opening a modal is a blocking experience. Switching between tabs to see a preview of the value you're changing is much less mental overhead than opening and closing repeatedly.

But, as you can see from the conversation, we tried to do a more live-ish preview which didn't work out for the technical reasons you suggested.

I'm pretty happy with preview as it exists now. If/when Shortcake ever ends on core track, though, we can revisit.

**Comment by mattheu** [comment]
I'm not totally sold on the preview. I'd be interested to hear other users experiences of it. Does anyone find it useful?

My biggerst concern here is that I don't want the added complexity of previews affecting the ease of implementing complex shortcodes in the media views. 

Currently - its working and its not obtrusive. But i'm not attached to it and I would certainly favour removing to ensure simplicity.

**Comment by bfintal** [comment]
My opinion is that either:
1. the preview tab is removed, or
2. when the screen is large enough, put the preview side by side with the settings that updates when the settings change; then hide the preview on smaller screens.

**Comment by soderlind** [comment]
For some project I like the preview, for other I don't, i.e. I like to be able to disable / enable preview in  register_shortcode_ui
eg:

``` php
Shortcode_UI::get_instance()->register_shortcode_ui(
                'myshortcode',
                array(
                    'label'         => "My Label",
                    'listItemImage' => 'dashicons-book',
                    'preview'       => false, // enable/disable preview, default = true
                    'attrs'         => array(
                    ...
                    )
                )
);
```

**Comment by mattheu** [comment]
I think this is reasonable. See also https://github.com/fusioneng/Shortcake/issues/127

**Comment by danielbachhuber** [comment]
I'd like to refrain from any decisions one way or another until we have solid technical direction on #116. 

Whether or not inline editing is feasible for most shortcodes significantly impacts the future of the preview UX

**Comment by rogercoathup** [comment]
+1 for an easy way to disable preview on our shortcodes -- we have a number where it doesn't make sense to see a preview in the post editor, e.g. shortcodes that need styles that are enqueued in the front end only, need front end js, or simply take up too much space and make editing the post more different.

Update: think I'm confusing the preview tab, with the general preview of the shortcode of in the post editor

**Comment by danielbachhuber** [comment]
> Update: think I'm confusing the preview tab, with the general preview of the shortcode of in the post editor

You are. If you're concerned about the latter, then it's the responsibility of your code to disable the preview. You can just return some placeholder value in your `do_shortcode()` callback.

**Comment by rogercoathup** [comment]
Thanks for quick reply -- yes, that's the route I'm going down

**Comment by davisshaver** [comment]
I am just getting back into Shortcake work and backreading. I would support removing the preview. When inserting an image or other media, there's no preview, so this seems okay with user expectations. I also found that the preview could fail silently, leaving the user confused if the shortcode needs server info.

re @danielbachhuber's point in https://github.com/fusioneng/Shortcake/issues/104#issuecomment-74597790, my take is that inline editing won't make sense until there's a core/TinyMCE feature to enable that interaction (I can't identify a similar, non-blocking pattern in existing media interactions). Quick edit would be a good first step https://github.com/fusioneng/Shortcake/issues/169 though.

**Comment by mattheu** [comment]
Preview is gone. Closing
