### ISSUE TITLE
Aesop Story Engine similar to Shortcake

### ISSUE THREAD

**Issue by paaljoachim** [wp-shortcake/shortcake#105]
Hey guys

It seems the Aesop Story Engine is something similar to Shortcake.
For instance here is the aiview js code:
https://github.com/bearded-avenger/aesop-core/blob/master/admin/assets/js/tinymce/aiview/plugin.js#L7

Both projects can probably learn from each other and perhaps also collaborate.

**Comment by danielbachhuber** [comment]
Thanks for the tip — we'll have to check it out.
