### ISSUE TITLE
Access Media

### ISSUE THREAD

**Issue by Danny159** [wp-shortcake/shortcake#106]
Have the ability to select a madia file :)

**Comment by danielbachhuber** [comment]
@Danny159 Not sure I follow. Could you explain in greater detail?

**Comment by Danny159** [comment]
Sorrry @danielbachhuber, Have a button next to a text box saying Add Media, where you can then select an image from the Media Library and it puts the URL into the textbox :)

Hope you now understand :)

**Comment by danielbachhuber** [comment]
What if we had a rich textarea that behaved like the normal WordPress editor?

**Comment by Danny159** [comment]
Hmm, Yes I guess you are right... :)

**Comment by soderlind** [comment]
@danielbachhuber not sure if I agree. If I only need to add media, why should I have/see the wp editor?

I'd prefer a field like this (screenshot from the [Admin Page Framework](https://github.com/michaeluno/admin-page-framework)):

![media-file](https://cloud.githubusercontent.com/assets/1649452/6011468/7c30ad0a-ab3c-11e4-8650-a9cfee7d1446.png)

**Comment by milgrom** [comment]
I agree that an add media button would be a great addition to keep things simple for non technical users.  And the rich textarea editor would also be a great addition for situations where it's required.

**Comment by yumyo** [comment]
+++1

**Comment by danielbachhuber** [comment]
Added in #146 as `type=attachment`
