### ISSUE TITLE
Overwriting Stylesheets

### ISSUE THREAD

**Issue by crstauf** [wp-shortcake/shortcake#110]
Shortcake overwrites/removes stylesheets added via WordPress built-in function `add_editor_style`.

Removing the TinyMCE filter and placing this code in the construct of the class will add the CSS file to the editor, and keep from overwriting other stylesheets.

`add_editor_style($this->plugin_url . '/css/shortcode-ui-editor-styles.css');`

**Comment by danielbachhuber** [comment]
Thanks for the report, @crstauf, we'll take a look.

**Comment by crstauf** [comment]
Welcome, Daniel! Wasn't sure if you'd want me to submit a branch/pull
request for something so small or not.

Caleb Stauffer

**Comment by danielbachhuber** [comment]
> Wasn't sure if you'd want me to submit a branch/pull
> request for something so small or not.

Oh, pull requests are more than welcome !

**Comment by crstauf** [comment]
Nice! Will do then. :-)

Caleb Stauffer

**Comment by danielbachhuber** [comment]
This was fixed by #112
