### ISSUE TITLE
Issue when using ACF edition pages

### ISSUE THREAD

**Issue by chdenat** [wp-shortcake/shortcake#111]
This made me crazy during 30 minutes ... :)

When Shortcake is activated I can not make any edit in my ACF admin pages  and got the issue described in the attached image.

When shortcake has been deactivated  all is fine.

May be it is related to the fact that there is no mce in the ACF page ?

Thanks for any tmp fix.

![2015-01-16 19_32_31-nouveau groupe de champs gf38 wordpress](https://cloud.githubusercontent.com/assets/9724885/5781953/3553238c-9db7-11e4-8f97-22ff2d9e9b08.jpg)

**Comment by chdenat** [comment]
Guys,

FYI I've fixed it by making a test on wp.mce : 
<code>
if (wp.mce) {
                wp.mce.views.register(
                    shortcode.get('shortcode_tag'),
                    $.extend(true, {}, sui.utils.shortcodeViewConstructor)
                );
            }
</code>

**Comment by danielbachhuber** [comment]
@christian-denat Yeah, it's #109. I'll try to get this fixed shortly.
