### ISSUE TITLE
No composer.json ?

### ISSUE THREAD

**Issue by phh** [wp-shortcake/shortcake#113]
It would be easier to install Shortcake if the plugin had a composerfile or was in the WordPress plugins repo.

**Comment by danielbachhuber** [comment]
Pull requests welcome (for composer.json)!

We'll be adding it to the WordPress plugins repo sometime between now and the next release.

**Comment by phh** [comment]
Sure thing :)

Here's a very simple basic composer.json file.
https://github.com/fusioneng/Shortcake/pull/114
