### ISSUE TITLE
Styling problem, shortcode instance always returns 1

### ISSUE THREAD

**Issue by cyrildc** [wp-shortcake/shortcake#119]
Hi,

In my button shortcode I declare an $instance variable (like on the gallery shortcode) to set a css class for the button so that I can add css style.

```
static $instance = 0;
$instance++;

<a class="button button-<?php echo $instance ;?>">
```

The issue is that in the visual content editor, the instance always returns 1. If I have multiple buttons on the page, the styling is wrong.

**Comment by danielbachhuber** [comment]
Try:

```
static $instance;
if ( ! isset( $instance ) ) {
    $instance = 0;
}
$instance++;
<a class="button button-<?php echo $instance ;?>">
```

**Comment by cyrildc** [comment]
I've tried but it doesn't work:

```
add_shortcode( 'pullquote', function( $attr, $content = '' ) {

    static $instance;
    if ( ! isset( $instance ) ) {
        $instance = 0;
    }
    $instance++;

    $attr = wp_parse_args( $attr, array(
        'source' => '',
        ) );

    ob_start();

    ?>
    <section class="pullquote">
        <?php echo $instance;?>
        <?php echo esc_html( $content ); ?><br/>
        <cite><em><?php echo esc_html( $attr['source'] ); ?></em></cite>
    </section>      

     <?php
        return ob_get_clean();
  });
```

If I add 2 pullquotes shortcodes in the editor, they both echo 1 for the $instance in the editor.

**Comment by danielbachhuber** [comment]
Oh. That's because the preview happens through admin ajax, which is run once for each preview.

**Comment by cyrildc** [comment]
So there is no way to achieve it?

**Comment by danielbachhuber** [comment]
None that I can think of, other than if you were to have a shortcode argument for the style.

**Comment by bobbingwide** [comment]
The ajax interface could pass an identifier through to the shortcode which could then be intercepted by 'shortcode_ui_before_do_shortcode'. This means the shortcode has to do more work to find the instanec number it intends to use.
