### ISSUE TITLE
Treat default values differently from placeholder

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#122]
Many of my shortcodes have a lot of parameters, with each parameter mapping directly to a value for a WordPress function's parameter. 

A lot of these parameters have default values, either set by the shortcode or by the invoked function.

It would be nice to be able to display the default values to the user - this can be achieved using the placeholder - but not have unchanged placeholder values created as shortcode parameters.

e.g. Using the defaults as placeholder values for the gallery shortcode we get

`[gallery order="ASC" orderby="menu_order ID" itemtag="dl" icontag="dt" captiontag="dd" columns="3" size="thumbnail"]`

It would be a lot nicer to just have [gallery].

This way, if the underlying shortcode's default values were to change, then the user's content would not have to be updated to reflect the change. 

Caveat: There will always be exceptions where the new default matches the overridden placeholder.

**Comment by danielbachhuber** [comment]
> It would be nice to be able to display the default values to the user - this can be achieved using the placeholder - but not have unchanged placeholder values created as shortcode parameters.

Is this not the current behavior? Not sure I follow.

**Comment by bobbingwide** [comment]
In my example for gallery I'd taken the defaults and assigned them to the 'value' for each parameter.
This therefore generated the shortcode with these default values.

I want to be able to display the default value to the user, but only create the actual parameter to the shortcode when the user has explicitly chosen it. 

ie. If I just choose Insert Element the generated shortcode would be `[gallery]`
But if I changed the order parameter to DESC then the generated shortcode would be `[gallery order=DESC]`.

In my current solution for oik, the default values, and other possible values, are shown below the input field for the parameter. I currently only support text fields; I've been waiting for something like shortcake to do the right thing for me. 
![image](https://cloud.githubusercontent.com/assets/2474435/6001450/cb8da8ae-aae1-11e4-8641-bcd777c326ce.png)

**Comment by bobbingwide** [comment]
Hi, looks like I'd coded it wrong. 
In my routine that maps my shortcode's syntax arrays to those required by shortcake
rather than use `'placeholder' => $default`
I'd coded `'value' => $default`.

I copied the code from #46 - where 'value' is used to show the default, rather than referring to the example on readme.md
