### ISSUE TITLE
Single or multiple post selection list

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#123]
Shortcodes such as [gallery] include parameters which require the user to specify the ID or IDs of the posts to be displayed, included or excluded. 

The logic should allow for parameters which allow multiple values to be specified. 

I have many shortcodes which also support the entry of post IDs. 

It would be nice to have native support for selecting the posts from existing content. 

This requirement may involve interaction with other parameter values that the user chooses: post_type, post_status, etcetera, but it's more likely to be controlled by hidden values.

e.g. For the gallery shortcode the IDs to be displayed in a selection list would be limited to attachments.  

For a shortcode such as [bw_pdf] the selection would be filtered with post_mime_type=attachment/pdf.

**Comment by danielbachhuber** [comment]
> It would be nice to have native support for selecting the posts from existing content.

We actually have an internal Select2 field for selecting one post for a shortcode. I can understand and agree with the appeal of being able to pick multiple posts. We'll keep this in mind as an enhancement.

**Comment by danielbachhuber** [comment]
@bobbingwide we've just added a `post_select` field which permits the selection of a single image. However, galleries aren't easily accommodated. Is it worth opening another issue for media selection?

**Comment by mattheu** [comment]
We should be able to support galleries as part of the attachment field I think. I think we should open a ticket. I've had this request before.

Also related is #244

**Comment by bobbingwide** [comment]
@danielbachhuber OK. I'll have a look and see if I can use it. 
But it's not just attachments are referenced by post ID.

**Comment by mattheu** [comment]
The post select allows you to specify any query you want so should be able to select any post type.

**Comment by bastienho** [comment]
Hi, the same feature for taxonomies or custom lists would be very useful

**Comment by misfist** [comment]
+1 I need multi-select for taxonomies and other lists.
