### ISSUE TITLE
Add to WordPress.org plugins repo

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#125]
It would be nice if everything auto-deployed, though. We'll need to handle:
- [x] Deploy master to svn trunk
- [x] Tagged releases
- [x] Readme conversion
- [x] Screenshots
- [ ] Banner image

**Comment by westonruter** [comment]
Our `svn-push` script handles these: https://github.com/xwp/wp-dev-lib/blob/master/svn-push

**Comment by danielbachhuber** [comment]
@westonruter do you have it hooked into Travis?

**Comment by westonruter** [comment]
No, but that would be sweet.

**Comment by danielbachhuber** [comment]
@mattheu Cool to ship tomorrow? cc @jitendraharpalani58

**Comment by danielbachhuber** [comment]
https://wordpress.org/plugins/shortcode-ui/
