### ISSUE TITLE
Support parameters which may also be 'content'

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#135]
When I first developed shortcodes I only worked with parameters and didn't make use of 'content'.

I now have shortcodes which would be better coded to process the $content rather than a named parameter. In order to transition I'll need to be able to support accepting the content either from a named parameter or from the nested content. 

e.g. `[bbboing text="Code is poetry"]` could just as easily be `[bbboing]Code is poetry[/bbboing]`

Using the $content method allows the further expansion of nested shortcodes.

It would be nice if shortcake could cater for this. 

Related: #129

**Comment by danielbachhuber** [comment]
> In order to transition I'll need to be able to support accepting the content either from a named parameter or from the nested content.

You should do this as a one-off migration by writing your own WP-CLI command. I don't think it's viable for Shortcake to do this automatically.

**Comment by bobbingwide** [comment]
Can I re-raise this in advance of proposed changes to shortcode syntax in the shortcode roadmap, where attributes that contain HTML will have to be defined in the content.
e.g.

```
[bbboing text="Code is poetry"]
[attr:text=]Code <b>isn't really</p> poetry.
[/bbboing]
```
