### ISSUE TITLE
Control sort sequence of shortcodes

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#136]
The order in which the shortcodes are listed on the Insert Post Element dialog depends on the sequence in which they are registered. 

It would be nice if the user could have some control over how they are listed. 
- My preference is to sort by shortcode tag.
- Others may prefer the most used to appear first
- I very much doubt that the sequence in which the plugins and theme register them would make any sense to the end user.

Related: #124

**Comment by danielbachhuber** [comment]
I was just thinking this the other day. I think sorting alphabetical makes the most sense.

**Comment by lukecarbis** [comment]
+1 for alphabetical. Makes it easiest for the user to find.

This in mind, they should be sorted by title, not shortcode tag.

For example a shortcode with the title of `Awesome Shortcode` and a tag of `xwp_awesome_shortcode` should be sorted with A, not X.

**Comment by danielbachhuber** [comment]
I can think of a situation where you have a lot of shortcodes and want to break them into sections too (e.g. ones that are always used vs. those that are used just occasionally).

**Comment by danielbachhuber** [comment]
Going with alphabetical by label for now. We can come back to sections later if it comes up again.
