### ISSUE TITLE
Filter / search mechanism for shortcodes

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#137]
Even if the shortcodes are nicely sorted on the Insert Post Content dialog, there may still be too many on display. 

It would be nice to have a filter and/or search mechanism that will enable the user to find the shortcode that they need. 
- It would be implemented something like the Media Library tab
- The search need not be limited to the shortcode tag
- There could be contextual information provided by the label (shortcode desciption)
- Or the parameters ( names and values )
- Or tags indicating business functionality 

Related: #136

**Comment by mattheu** [comment]
Agreed this could be useful

**Comment by danielbachhuber** [comment]
One minor issue, but this is looking pretty good otherwise #221
