### ISSUE TITLE
Incorporate "catalog" functionality

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#138]
In all the plugins and themes available for WordPress there are probably well over 2,000(*) unique shortcodes. Each one waiting to be discovered and used. 
- For my own shortcodes I developed an API to define each shortcode's syntax.
- I used the output from this in my own shortcode creation routine (quicktag and TinyMCE buttons)
- It is also used to populate the 'shortcode help' admin page.
- And in the [bw_codes] shortcode, 
- These display ALL the currently active shortcodes to the site visitor 
- I also used the data strucures to populate a shortcode catalog
- The catalog currently lists my plugin's shortcodes, WordPress core shortcodes 
- and a few others from plugins I use regularly. 

The techniques that I applied to create my catalog could be applied using the more advanced definitions used by shortcake. The catalog could then be accessed using the WP REST API to dynamically provide the latest and greatest information about each shortcode and its parameters.

Eventually, it may not be necessary to have plugins delivering loads of shortcodes you don't use... you would just pick the ones you want from the catalog. 

A bit of a pipe dream perhaps? 
Maybe for WordPress.org, but not so far away for oik-plugins.

To delve a little deeper visit http://www.oik-plugins.com/oik_shortcodes/bw_codes/

(*) Someone did a scan of the plugin repo a while back. Can't remember who though.

**Comment by danielbachhuber** [comment]
> A bit of a pipe dream perhaps?

You might be the only one with this problem :wink:

**Comment by danielbachhuber** [comment]
I think we'll close this as #maybelater for now. It could be a supplemental plugin that someone builds.
