### ISSUE TITLE
IE11 Crashes

### ISSUE THREAD

**Issue by Danny159** [wp-shortcake/shortcake#140]
There seem to be a problem with IE11.

When you edit a page that uses Shortcake and click to edit the shortcode IE11 freezes says a script it looping then crashes...

Is anyone else having this problem? Or know of a fix.

Thanks

**Comment by danielbachhuber** [comment]
Sorry for the late reply. We can leave this open to see if anyone else can confirm.

**Comment by mattheu** [comment]
Confirmed this bug - opening PR now

**Comment by danielbachhuber** [comment]
Thanks for your work on this, @mattheu 

@Danny159 Can you confirm the fix?
