### ISSUE TITLE
Image upload [how to]

### ISSUE THREAD

**Issue by yumyo** [wp-shortcake/shortcake#141]
Hello,
first of all thank you for Shortcake, it's a really beautiful solution to handle shortcodes in wordpress. 

An image upload feature is critical in many of our current projects. As far as I understand it could be achieved using Shortcake along with the **fieldmanager** plugin but I can't get it working. Could you exaplain how to build a simple [image] shortcode with the ability to let users select/upload an attachment from within the Shortcake UI?

**Comment by danielbachhuber** [comment]
Already requested in #106. Please don't open duplicate tickets.
