### ISSUE TITLE
Abstract shortcode-ui.js into modules with Browserify

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#142]
`shortcode-ui.js` is getting quite long and complex. We should break it into logical modules using Browserify.

@noppanit Can you weigh in with some thoughts in this regard?

**Comment by noppanit** [comment]
I'd like to refactor this and add some tests as well. Or @jitendraharpalani58 if you want to do it, it's ok for me as well.

**Comment by danielbachhuber** [comment]
@jitendraharpalani58 wants to work on it, but you'd make a great review partner :)

**Comment by danielbachhuber** [comment]
:ship:
