### ISSUE TITLE
Form enhancements

### ISSUE THREAD

**Issue by mishterk** [wp-shortcake/shortcake#144]
I'd love to see – in the Post Element Details Edit tab – a richer form experience. 

Field descriptions (below the labels) would be very handy, and maybe the ability to increase field widths based on a selection of options (small, medium, large?).

If these abilities are already in there – awesome – I'm just having trouble finding some decent docs on possibilities keys in the `attrs` array when registering a shortcode UI.

**Comment by danielbachhuber** [comment]
> Field descriptions (below the labels) would be very handy

I agree. Adding in #145

> maybe the ability to increase field widths based on a selection of options (small, medium, large?).

I think what we really need is generic support for `attributes` in a similar manner to Fieldmanager. You'd be able to pass `style`, `length`, data attributes, etc.

@mattheu thoughts?

**Comment by mattheu** [comment]
+1

**Comment by bfintal** [comment]
+1 solves the `multiple` attribute for select types
