### ISSUE TITLE
Edit button not working

### ISSUE THREAD

**Issue by rogercoathup** [wp-shortcake/shortcake#151]
Icon button to edit a shortcode once added to post content is not working - throws an error at line 661 in shortcode-ui.js:
TypeError: undefined is not an object (evaluating 'this.frame.toolbar')

Version v0.2.0-dev of Shortcode  UI
Version 1.0.0 of Shortcake UI Pullquote Demo

Clean install of WP, 2015 theme, Vagrant / Chassis

**Comment by chrisvanpatten** [comment]
I'm having the same problem, with the same error at the same line. (Well, it's worded differently... "Uncaught TypeError: Cannot read property 'toolbar' of undefined" ...but I'm guessing it means the same thing!)

**Comment by danielbachhuber** [comment]
Thanks for the quick report! Fixing this in #152

**Comment by rogercoathup** [comment]
Can confirm that fixes the problems.  Many thanks.
