### ISSUE TITLE
Remove fieldmanager fields

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#160]
It was a good test case for the customization of shortcake but I think its time to stop bundling it.

Firstly - its confusing - quite a few people are put off shortcake because it seems like it requires fieldmanager.

Secondly - I don't think it should complicate development of shortcake. Of course Shortcake should aim for extensibility - and as before fieldmanager support chould be a great test case - but shouldn't be bundled with Shortcake. See #139

Finally - The main reason we used it was to avoid having to build our own media upload field. However I don't think it was easier and we now have our own image/attachment field. See #146

**Comment by roborourke** [comment]
+1

**Comment by franz-josef-kaiser** [comment]
:+1:

**Comment by danielbachhuber** [comment]
Let's package what we have in a separate repo (which I can create next week), and make sure Shortcake doesn't fatal if the fields are missing

**Comment by danielbachhuber** [comment]
@mattheu I've granted you access to the new repo if you want to take care of it. Otherwise, I can do later this week.

**Comment by danielbachhuber** [comment]
Thanks @mattheu
