### ISSUE TITLE
Support numeric attribute

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#165]
I encountered Jetpack's Googlemap shortcode that has this syntax:

`[googlemaps http://blahblahblah.com]`

It's attribute key is numeric, and by the time the shortcode is rendered into the editor view, the attributes get lost in **js/shortcode-ui.js** `formatShortcode()`. The `$attr` variable inside the `add_shortcode` doesn't contain it anymore

I think this should be handled

**Comment by danielbachhuber** [comment]
Duplicate of #128

**Comment by bfintal** [comment]
Didn't notice that
