### ISSUE TITLE
Translating Shortcake

### ISSUE THREAD

**Issue by zedejose** [wp-shortcake/shortcake#166]
I was about to create a pull request, but decided to check here if my approach is correct, first:
- I see no `load_plugin_textdomain`call anywhere in the code, I assume it's missing and should be there
- Textdomains vary across the code, see https://github.com/fusioneng/Shortcake/blob/master/inc/class-shortcode-ui.php#L80 (textdomain is `shortcode-ui`) and https://github.com/fusioneng/Shortcake/blob/master/inc/fields/class-field-attachment.php#L47, (textdomain is now `shortcake`). I assume only one should be used, which is best?
- The above implies creating a .pot file inside a (as of yet, inexistant) languages folder
- I suspect that all of the above also implies updating the Gruntfile with a i18n task (I normally use [grunt-wp-i18n](https://github.com/blazersix/grunt-wp-i18n) myself)

Is the approach sound?

**Comment by danielbachhuber** [comment]
> I assume it's missing and should be there

Correct.

> I assume only one should be used, which is best?

Let's go with `shortcode-ui`, for internal consistency with the rest of the codebase.

> I suspect that all of the above also implies updating the Gruntfile with a i18n task

+1 automation

**Comment by zedejose** [comment]
Hmmm I've hit a block of not very elegant solution:
- To make it "proper", the `load_plugin_textdomain`call should be made inside the `Shortcode_UI`class, but since that is in a subfolder, I have no way of retrieving the plugin's base dir elegantly (making it 100% portable). I mean I _can_, but it feels hacky and... dirty.
- The other option is to call it in from the main file, like so https://gist.github.com/zedejose/4a38b9d952ca0209d93b, but it somehow doesn't feel any cleaner... 

Ideas? (sorry for being extra careful)

**Comment by danielbachhuber** [comment]
What if we set a conference and then reference that?

I don't know that 100% portability is a huge concern though. If/when this ends up in core, we'll be changing up the translations anyway.

**Comment by zedejose** [comment]
works for me, where/when is good?

**Comment by danielbachhuber** [comment]
Sorry. "Conference" was meant to be "constant"

**Comment by zedejose** [comment]
constant is also good :)
