### ISSUE TITLE
TinyMCE views API improvements for 4.2

### ISSUE THREAD

**Issue by ellatrix** [wp-shortcake/shortcake#181]
Hi,

Just wanted to say that I'm redoing some parts of the TinyMCE views API, so if someone sees any  issues, let me know. Also, If you have any suggestions for improvements in 4.2, let me know too. :)

Thanks!

https://core.trac.wordpress.org/ticket/31412

**Comment by ellatrix** [comment]
The patch as it currently is will break things.

**Comment by danielbachhuber** [comment]
@iseulde Can we package a backwards compat shim somehow then?

**Comment by ellatrix** [comment]
Certainly. I'll see what I can do.

**Comment by mattheu** [comment]
I've managed to update this to work fairly easily. Only concern is VIP might deploy this change before 4.2... Quickstart at least will update to trunk right?

**Comment by mattheu** [comment]
Closing this issue. Master is now compatable - and there are separate issues for any outstanding problems.
