### ISSUE TITLE
Easy for shortcake field input IDs to conflict

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#187]
I was testing the checkbox PR and #182 and noticed that if I used the attribute name 'checkbox', then clicking the label didn't focus the checkbox.

This is because the ID conflicts with another field on the page.

A simple fix would be to prefix `id` and `attr` to avoid conflicts. I don't think this will have any other effects.

**Comment by danielbachhuber** [comment]
Let's fix this for v0.2.0 — it would be nice to get out of the way.
