### ISSUE TITLE
When shortcode preview is selected, "delete" should remove it

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#193]
Current behavior is to trigger browser back button

![image](https://cloud.githubusercontent.com/assets/36432/6349960/942c400a-bbe4-11e4-96c6-78e0ca490394.png)

**Comment by davisshaver** [comment]
@danielbachhuber Just tested this with two shortcodes in two browsers. Are you still experiencing the issue?

**Comment by danielbachhuber** [comment]
> Are you still experiencing the issue?

Nope. Must've been fixed in core.
