### ISSUE TITLE
500 Server Error, need advice

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#201]
Hello,

A user had this error:

> Parse error: syntax error, unexpected T_FUNCTION in /public_html/wp-content/plugins/page-builder-sandwich/inc/shortcake/shortcode-ui.php on line 29

Need your advice on this one, since it's a weird one. Looking at line `29` there shouldn't be any problem. The server is running on PHP 5.3+ so anonymous functions are okay.

I'm including Shortcake this way:

```
add_action( 'init', array( $this, 'loadShortcake' ), 1 );
```

```
public function loadShortcake() {
    // Don't do anything when we're activating a plugin to prevent errors
    // on redeclaring Shortcake classes
    if ( is_admin() ) {
        if ( ! empty( $_GET['action'] ) && ! empty( $_GET['plugin'] ) ) {
            if ( $_GET['action'] == 'activate' ) {
                return;
            }
        }
    }

    // Include Shortcake if we don't have it yet
    if ( ! class_exists( 'Shortcode_UI' ) ) {
        require_once( PBS_PATH . 'inc/shortcake/shortcode-ui.php' );
    }
}
```

Anything wrong here?

**Comment by danielbachhuber** [comment]
Your server probably isn't running 5.3 even though you think it is.

**Comment by bfintal** [comment]
That's what I'm thinking since the error is `unexpected T_FUNCTION`. However, he was able to run the plugin before with no problems. Then his host removed the plugin due to this 500 error. Unfortunately, the above error message is the only clue I've got. Ideas?

**Comment by danielbachhuber** [comment]
https://www.google.com/search?q=unexpected+T_FUNCTION&oq=unexpected+T_FUNCTION&aqs=chrome..69i57.284j0j7&sourceid=chrome&es_sm=91&ie=UTF-8

**Comment by bfintal** [comment]
Alright, just needed confirmation that THAT was the only possible cause of this. Thanks!

Closing this.

@danielbachhuber now off to my PRs _(nudge)_ :point_right: :smile:
