### ISSUE TITLE
Multiple option for select type attributes

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#206]
I tried manually adding a `multiple` attribute on an existing `select` attribute to see what the output would be. The output was a csv string containing the values highlighted in the drop down - the correct expected output.

I would suggest adding a `multiple` option that can be used for `select` types.

**Comment by danielbachhuber** [comment]
We should really just solve https://github.com/fusioneng/Shortcake/issues/144#issuecomment-73894464, which would support any arbitrary attribute.

**Comment by bfintal** [comment]
#144 sounds like a good encompassing solution for stuff like this
