### ISSUE TITLE
WordPress 4.2 compatibility issues

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#214]
From https://github.com/fusioneng/Shortcake/pull/209#issuecomment-76698566
- Styles aren't imported into the iframes automatically, and I'd rather not have to duplicate this functionaliyt from core. 
  - I've opened a ticket on trac - https://core.trac.wordpress.org/ticket/31464
  - Currently no styles are imported so some things look broken
- Sometimes iframe previews are not correctly resized to fit images. 
  - created a trac ticket for this also - https://core.trac.wordpress.org/ticket/31480

**Comment by mattheu** [comment]
https://core.trac.wordpress.org/ticket/31464 is fixed.

**Comment by danielbachhuber** [comment]
Yep, 31464 is good for our needs.

**Comment by danielbachhuber** [comment]
Closing in favor of #257
