### ISSUE TITLE
Show default message when a shortcode has no fields to edit

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#219]
This is more of a UX enhancement. In the Add Post Element UI, when a shortcode is clicked and it doesn't have any attribtues, insert it right away instead of showing a blank UI.

What do you guys think?

**Comment by danielbachhuber** [comment]
I'm :-1: because it adds inconsistency and complexity to the UX

**Comment by bfintal** [comment]
No problem, I agree it is inconsistent. The reason for the comment is that when the shortcode doesn't have any attributes, it's a bit awkward to see the UI blank.

**Comment by danielbachhuber** [comment]
Maybe we should have a default "There are no fields" to edit message?

**Comment by bfintal** [comment]
I think that do the trick :+1:
