### ISSUE TITLE
Search UI can conflict with Post Elements grid

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#221]
![image](https://cloud.githubusercontent.com/assets/36432/6510355/68ba75da-c31a-11e4-83c0-f10495d88755.png)

From #137

**Comment by davisshaver** [comment]
@danielbachhuber I did some device/browser testing and couldn't reproduce this.

**Comment by danielbachhuber** [comment]
Fixed in core then?

`/me shrugs`

Seems like there's enough padding to me:

![image](https://cloud.githubusercontent.com/assets/36432/9100219/3358998a-3b8d-11e5-8fbc-6ba20a30a268.png)
