### ISSUE TITLE
How to open the shorcode UI dialog when a button is clicked (click event is triggered)

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#223]
Great job you've all done with the Shortcode API. i integrated shortcake to a plugin am working on and it's great.

I would love to add a button close to the `Add Media` button using WP `media_buttons` action hook that will open the shorcake dialog when a click event is triggered without having to navigate to **Add media** button >> **Insert post element**

Can you guys point me to the direction to implement this? cc @danielbachhuber @noppanit

**Comment by mattheu** [comment]
Internally we have to do this when you 'edit' a shortcode. I think you will want something like this: 

``` php
var wp_media_frame = wp.media.frames.wp_media_frame = wp.media({
    frame : "post",
    state : 'shortcode-ui',
});

wp_media_frame.open();
```

**Comment by w3guy** [comment]
Worked. Thanks @mattheu
