### ISSUE TITLE
Shortcode getting wrapped with <p> tag when Tinymce is switch to Text mode.

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#226]
Each time a shortcode is inserted to TinyMCE and switch to Text mode, the shortcode ends up being wrap by a `<p>` tag.

Example

`<p>[user-avatar]</p>`

Please someone point me in the direction to get this fixed cc @danielbachhuber

**Comment by danielbachhuber** [comment]
I haven't seen this happen with any of our shortcodes before.

To confirm, this is on a fresh install of WordPress, with TwentyFifteen active and all plugins disabled?

**Comment by w3guy** [comment]
@danielbachhuber  It only happens when i switch to visual mode and back to Text mode. Inserting directly to text mode doesn't include the `p` tag.

Lemme do a test on a fresh install and see.

**Comment by w3guy** [comment]
@danielbachhuber error was my fault.

**Background**
Am using `wp_editor` to render a TinyMCE editor.

Setting `wpautop` to true or removing it entirely fixed the problem.

I'm closing the issue right now.

Thanks Team fusion.. you guys rock
