### ISSUE TITLE
Doc related: how are options for <select>, radio buttons and checkboxes created?

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#227]
text, textarea, email, url, number, and date are straight-forward to implement, how do i create the different options for radio, select, checkbox?

Say the `type` is set to `select` what array parameter is used for defining the options?

cc @danielbachhuber

**Comment by danielbachhuber** [comment]
> what array parameter is used for defining the options?

`option`: https://github.com/fusioneng/Shortcake/blob/master/inc/templates/edit-form.tpl.php#L52

> cc @danielbachhuber

You don't need to cc me on every issue. I get the notification regardless.

**Comment by w3guy** [comment]
Got the cc part.

It isn't `option` but `options`.

For future reference, here is a sample code.

```
'options'   => array(
                'facebook' => 'Facebook',
                'twitter'  => 'Twitter',
                'google'   => 'Google',
                'linkedIn' => 'Linkedin',
                'github'   => 'Github'
            ),
```

Where the array key is the attribute value and the array-value the option label.
