### ISSUE TITLE
Shortcode attribute dialog blank when  visual editor (rich_editing) is disabled by the user

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#234]
Came across this bug few minute ago. 

Note: am using shortcake to easily insert some custom shortcode i made in my post.

I disabled the `visual editor` in my WordPress profile and when i tried to use shortcake, the attribute dialog turn out blank.

See images below for clarity.

![visual-editor](https://cloud.githubusercontent.com/assets/4140659/6730244/ee21c2fc-ce3a-11e4-9a46-da758525d7c9.png)

![shortcake-empty](https://cloud.githubusercontent.com/assets/4140659/6730336/e71bce48-ce3b-11e4-88ac-0730e7c5591f.PNG)

**Comment by danielbachhuber** [comment]
Thanks for the report — we'll take a look into this.

**Comment by w3guy** [comment]
I will be very happy if this bug is fixed as soon as possible. My clients are seriously on my neck.

I will be happy if you guys provide me a temporary fix while waiting for the an official fix to the plugin

**Comment by w3guy** [comment]
Well i found a temporary fix to this issue by using css to make hidden the visual tinymce tab when users has rich editing disabled.

**Comment by danielbachhuber** [comment]
Related #153

**Comment by danielbachhuber** [comment]
Thanks again for the report @Collizo4sky. Turned out to be relatively straightforward.

**Comment by w3guy** [comment]
The pleasure is all mine. :dancer:
