### ISSUE TITLE
Cant get "inner_content" working.. Peep in to correct my code 

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#237]
Here is my code

```
    shortcode_ui_register_for_shortcode(
        'social-button',
        array(
            'label'         => 'Social button',
            'listItemImage' => 'dashicons-editor-textcolor',
            'inner_content' => array(
                'label' => 'Text',
            ),
                'attr'        => 'content',
                'type'        => 'text',
                'description' => "The text shown in the socialbutton",

        )
    );
```

**Comment by jitendraharpalani58** [comment]
@Collizo4sky if you are using `inner_content` you will not need `attr=>'content''. If you just need a field for inner content, you could suffice:

```
shortcode_ui_register_for_shortcode(
        'social-button',
        array(
            'label'         => 'Social button',
            'listItemImage' => 'dashicons-editor-textcolor',
            'inner_content' => array(
                'label' => 'Text',
            ),
        )
    );
```

Also, `attr` is an array, for example:

```
'attrs'          => array(
                array(
                    'label'        => 'URL',
                    'attr'         => 'url',
                    'type'         => 'text',
                    'description'  => 'Full URL to the Facebook Post or Video',
                ),
            ),
```

**Comment by w3guy** [comment]
I understand but the problem is, it isn't working. i.e the attribute dialog is empty.

Ok see. i used this code your provided

```
shortcode_ui_register_for_shortcode(
        'social-button',
        array(
            'label'         => 'Social button',
            'listItemImage' => 'dashicons-editor-textcolor',
            'inner_content' => array(
                'label' => 'Text',
            ),
        )
    );
```

This is the result

![wmpty-shrt](https://cloud.githubusercontent.com/assets/4140659/6769957/f9ce2438-d0b0-11e4-9626-aa43a2f87f2d.png)

**Comment by w3guy** [comment]
#238 ##Bug Alert

inner_content textarea appear on the dialog of shortcode that originally do not support or include the inner_text content.

Eg i have a shortcode with no attribute.. prior to this commit, the dialog becomes blank which is expected but after this comment, inner_text textarea appears on `all` shortcodes regardless of whether it is needed or not.

![bug](https://cloud.githubusercontent.com/assets/4140659/6806193/7eaf5a22-d247-11e4-982c-b084444eefa1.png)

**Comment by danielbachhuber** [comment]
@Collizo4sky Can you confirm the fix on `master`?

**Comment by w3guy** [comment]
@danielbachhuber works flawlessly. Please update the WP repo.

**Comment by danielbachhuber** [comment]
> Please update the WP repo.

We will ship v0.3 in the next month or so. In the interim, you're welcome to use the `master` branch of this repo.
