### ISSUE TITLE
Shortcode preview inline-block or floated

### ISSUE THREAD

**Issue by MWDelaney** [wp-shortcake/shortcake#239]
Hello!
This is a great tool and I'm eager to integrate it into my shortcode plugins. Having a single, predictable UI for inserting and editing shortcodes is a noble goal and I'm excited to see it!

Is it possible to make a shortcode preview either inline-block or floated, the way TinyMCE floats images? Many of my shortcodes tend to be for inline elements (like Font Awesome icons) and the full-width block preview breaks up content in a way that doesn't reflect how the shortcode will look on the front-end.

Thanks!

**Comment by danielbachhuber** [comment]
> Is it possible to make a shortcode preview either inline-block or floated, the way TinyMCE floats images?

Not at the moment. You can follow #169 for progress on that request though.
