### ISSUE TITLE
Incompatible with PHP 5.3?

### ISSUE THREAD

**Issue by jeromydarling** [wp-shortcake/shortcake#240]
Myself and a number of others users are running into this issue activating Shortcake:

Parse error: syntax error, unexpected T_FUNCTION in /wp-content/themes/aurelia/framework/shortcake/shortcode-ui.php on line 29

Does shortcake require PHP 5.4?? I have no plugins installed

**Comment by danielbachhuber** [comment]
> Does shortcake require PHP 5.4??

It requires PHP 5.3. The error message you're seeing indicates you're running PHP 5.2 or lower.

**Comment by jeromydarling** [comment]
I'm on site5 and running 5.3.x according to their KB:

http://kb.site5.com/php/how-to-change-your-php-version/

**Comment by danielbachhuber** [comment]
> I'm on site5 and running 5.3.x according to their KB:

Nope, you're running PHP 5.2 or lower. You should triple-check your config.

**Comment by jrfnl** [comment]
Uhm... to be considered for core, shouldn't it be compatible with PHP 5.2.6+ ?

**Comment by danielbachhuber** [comment]
> Uhm... to be considered for core, shouldn't it be compatible with PHP 5.2.6+ ?

Possibly. Depends on when core makes the 5.3 bump. I need to go through the feature plugin guidelines and create a new issue to ensure we're meeting all of the requirements.
