### ISSUE TITLE
Allow for HTML in the 'description' attribute when registering shortcode

### ISSUE THREAD

**Issue by cjmaio** [wp-shortcake/shortcake#242]
It would be incredibly useful to allow for HTML in the 'description' attribute when registering a shortcode.

For example, when I add a field called 'icon' for an end user to add in a Font Awesome icon, I want to give them the URL to the list of icons. When I tried it, I ended up with this:

```
Choose an icon for the circle beside the button. Simply copy the name from any of the <a href="http://fortawesome.github.io/Font-Awesome/icons/" alt="Font Awesome">Font Awesome icons</a> available.
```

I am not sure if that was done on purpose or not. If not, I may submit a PR with this functionality if desired.

**Comment by mattheu** [comment]
Thanks for reporting. I think this is a fairly common requirement. There is a PR already - https://github.com/fusioneng/Shortcake/pull/189

When data is passed to an Underscores templates - you need to explicitly allow unescaped output. We'll look into a workaround.

**Comment by danielbachhuber** [comment]
Need to get a verdict from VIP on how they'd like to handle escaping HTML in attributes.

**Comment by danielbachhuber** [comment]
VIP wants to make sure all output is appropriately sanitized / escaped. In order to do this "properly", we'd need to switch away from Underscores to a templating engine that supports custom escaping callbacks.

**Comment by danielbachhuber** [comment]
Actually, we can just go the easier route:

![image](https://cloud.githubusercontent.com/assets/36432/10313551/0ff9c9e8-6c05-11e5-927b-84e7d9969d4a.png)
