### ISSUE TITLE
Preview rendering twice following update

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#247]
Affects WP trunk + Shortcake master. If you update an existing element, it gets inserted twice.

This issue is only present after https://core.trac.wordpress.org/changeset/31832

I have opened a ticket on trac to track this issue: https://core.trac.wordpress.org/ticket/31796

**Comment by danielbachhuber** [comment]
Thanks @mattheu !

**Comment by mattheu** [comment]
Fixed in https://core.trac.wordpress.org/changeset/31931
