### ISSUE TITLE
Examples repository

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#250]
Would it be difficult to manage some kind of users code repository ? Some place where people can leave their code, possibly with screenshots what this code does. You have one example.

So that beginners can study code and get whole picture what is possbile and what not. Maybe reuse some snippets and adapt them to own needs.
I see they exist everywhere, but still not complete snippets.

I mean I could ask people to do it, but nobody would listen to me. You have more authority.

**Comment by mattheu** [comment]
:) I think the Wiki on github would be a great place for stuff like this.

**Comment by StaggerLeee** [comment]
Please add it to explanation on Github main page. This issue will be quick lost among others.
https://github.com/fusioneng/Shortcake

**Comment by danielbachhuber** [comment]
> Please add it to explanation on Github main page.

We can do as a part of #231

**Comment by danielbachhuber** [comment]
We now have https://github.com/fusioneng/Shortcake/wiki/Shortcode-UI-Examples

It will be linked to in the readme shortly. I'd love some help fleshing it out, formatting, etc. :)

**Comment by StaggerLeee** [comment]
Thank you. Unfortunately cannot help with anything right now. Have no clue how to use it and dont have any snippet yet.
