### ISSUE TITLE
Call to undefined function is_rtl() in  theme.php on line 1380

### ISSUE THREAD

**Issue by FriendlyWP** [wp-shortcake/shortcake#251]
Hi, I'm getting the fatal error `Call to undefined function is_rtl() in ... wp-includes/theme.php on line 1380` when Shortcake is running and I'm editing a page/post. 

When I comment out line 30 of inc/class-shortcode-ui.php (`$this->add_editor_style();`) the error disappears. It seems like everything works fine without that line, including the loading of the plugin's editor stylesheet.

**Comment by mattheu** [comment]
I'll take a look at this. Are you running into this issue on the standard post edit page in the WP Admin?

**Comment by FriendlyWP** [comment]
It was editing a Page, but yes, the standard post.php edit screen.

**Comment by them-es** [comment]
To reproduce this issue you need to install the [RTL Tester Plugin](https://wordpress.org/plugins/rtl-tester/)

Workaround is to run 'add_editor_style' in class-shortcode-ui.php after the theme has been setup
`add_action( 'after_setup_theme', array( $this, 'add_editor_style' ) );`
