### ISSUE TITLE
Referencing shortcake in another plugin / plugin load order?

### ISSUE THREAD

**Issue by FriendlyWP** [wp-shortcake/shortcake#252]
Hi, I have Shortcake installed and everything works fine if I reference it from within my theme's functions.php file. I'm trying to move my shortcodes into a separate functionality plugin, however, and when I do I run into the issue of Shortcake not being available if my plugin loads before Shortcake.

If my plugin is named zzz-plugin-name, it loads after shortcode-ui and everything works fine. 

If my plugin is named aaa-plugin-name, it loads before shortcode-ui and my plugin's `if (function_exists('shortcode_ui_register_for_shortcode'))` check fails. 

I've looked into a number of ways to re-order the plugin loading stuff but it all seems really hackish. Is there a better way I should be including the Shortcake functionality in my plugin?

Thanks!

**Comment by danielbachhuber** [comment]
> Is there a better way I should be including the Shortcake functionality in my plugin?

You should hook your registration calls on `plugins_loaded`:

```
add_action( 'plugins_loaded', function() {
    // Use shortcode_ui_register_for_shortcode() to register UI
});
```
