### ISSUE TITLE
https://core.trac.wordpress.org/ticket/31480

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#257]
Keep an eye on this - https://core.trac.wordpress.org/ticket/31480

Arguments passed to render are changing - will need to make a small change when this gets merged.

**Comment by danielbachhuber** [comment]
Will we need to shim for 4.1?

**Comment by mattheu** [comment]
No - We already have backwards compat by keeping around the old view object - as the structure of this code was changed.

**Comment by danielbachhuber** [comment]
@mattheu Can this be closed, or are there other changes we'll be waiting for?

**Comment by mattheu** [comment]
Nope we can close.
