### ISSUE TITLE
Ability to add attributes such as "min", "max" and "step" to the numeric field.

### ISSUE THREAD

**Issue by jimmyandrade** [wp-shortcake/shortcake#258]
Here's one suggestion for how to do this...

First, a function to add the fields...

```
abstract class Shortcode {

    private $shortcode_ui_atts = array();

    protected function add_ui_att( $attr, $label, $type = 'text', $description = null, $attributes = array() ) {

        if( !is_array( $this->shortcode_ui_atts ) ) {
            $this->shortcode_ui_atts = array();
        }

        $this->shortcode_ui_atts[] = wp_parse_args( $attributes, array(
            'attr'  => $attr,
            'label' => $label,
            'type'  => $type,
            'description' => $description,
        ) );

    }

}
```

An example of how to call:

```
$this->add_ui_att(
    'level',
    __( 'Level', 'textdomain' ),
    'number',
    __( 'Heading level (from 1 to 5). Default is 2.', 'textdomain' ),
    array(
        'min' => 1,
        'max' => 5,
        'placeholder' => 2,
        'step' => 1,
    )
);
```

**Comment by danielbachhuber** [comment]
Is this a question?

**Comment by jimmyandrade** [comment]
No. As I wrote above, it's a suggestion. It would be nice if the attributes "min", "max" and "step" were supported when adding a numeric field related to some shortcode attribute.

But it is still a question: support for these attributes already exist? I couldn't find it when browsing the plug-in code. After all, I'm sorry if I expressed myself badly. My English is not the best ;)

**Comment by danielbachhuber** [comment]
> But it is still a question: support for these attributes already exist? I couldn't find it when browsing the plug-in code.

Not yet. Hopefully coming in v0.3 with generic support for attributes: #212
