### ISSUE TITLE
Createer WP Plugin

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#259]
https://beta2.createer.com/Wordpress

Take a look at this. What is this ? Something like Visual Composer or better. And can you maybe use some inspiration from this, or is this completely different visual editing platform. (bypassing WP editor at whole)

**Comment by danielbachhuber** [comment]
> Take a look at this.

Thanks for the heads up!

**Comment by MartinDesigner** [comment]
Not only Wordpress or Joomla is the key from Createer. You can easily design online ads, responsive landing pages and print materials such as flyers, posters, covers, invitations and more. Createer lets you easily share your designs on social media, send them via email, download as HTML, image or PDF. Createer also includes 3,000 predesigned templates and over 250,000 images (illustrations, photos and icons) to work with in its user-friendly drag’n’drop enviroment.
