### ISSUE TITLE
dev.php - Example shortcode.

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#264]
We currently have dev.php that includes an example shortcode. Its great for pople getting started, as well as development.

The file just needs to be included. 
- It was brougt up in the chat this month that this could be enabled in the beta tester plugin.
- I keep committing this include by mistake ;)
  - daniel suggested a git pre commit hook.

Probably some improvements that can be made here.

**Comment by danielbachhuber** [comment]
We can also add plugin headers to the `dev.php` file so WordPress recognizes it for activation in the admin. This would be my suggestion.

**Comment by mattheu** [comment]
Didn't know you could do that... good idea.
