### ISSUE TITLE
Broken Dependencies - shortcode-ui (missing)

### ISSUE THREAD

**Issue by phh** [wp-shortcake/shortcake#265]
From Query Monitor:

| Scripts |  | Dependencies |
| --- | --- | --- |
| Broken Dependencies | shortcake-field-attachment http://***/wp-content/plugins/shortcode-ui/js/build/field-attachment.js | shortcode-ui (missing) |

**Comment by danielbachhuber** [comment]
@phh Sorry, not sure what this is referring to and the attachment field seems to work fine. Can you clarify?

**Comment by phh** [comment]
Due to this error from the query monitor plugin:
![shortcake issue](https://cloud.githubusercontent.com/assets/1304003/7032957/b77b9908-dd76-11e4-81f9-f0168899dfbd.png)

But it seems like the script is enqueued. Maybe a query monitor issue then?

**Comment by danielbachhuber** [comment]
> Maybe a query monitor issue then?

cc @johnbillion

**Comment by johnbillion** [comment]
What screen are you seeing this error on?

**Comment by phh** [comment]
Everywhere inside the admin area.

**Comment by johnbillion** [comment]
Found it.

This is actually a broken dependency in Shortcake. The `shortcode-ui` script is only registered on the `wp_enqueue_editor` action, but the `shortcake-field-attachment` script is enqueued everywhere and depends on `shortcode-ui`.

This means on screens other than the post editing screen the `shortcake-field-attachment` script has a broken dependency and doesn't get enqueued.

**Comment by danielbachhuber** [comment]
Makes sense. We'll get this fixed.
