### ISSUE TITLE
Support galleries, or comma-separated lists of IDs

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#283]
The Attachment field should support galleries. Allowing you to add multiple files which will be stored as a comma separated list.

**Comment by mattheu** [comment]
From #123

**Comment by StaggerLeee** [comment]
Would it be possible to use Shortcake to make something like Flexslider gallery from gallery shortcode (not attached to post only) ?
I did managed it manually, but as an addon for Shortcake it would be great.

http://webdesignforidiots.net/2015/02/customizing-the-output-of-the-gallery-shortcode/

**Comment by danielbachhuber** [comment]
> Would it be possible to use Shortcake to make something like Flexslider gallery from gallery shortcode (not attached to post only) ?

Nope, that looks to be separate from Shortcake.

**Comment by StaggerLeee** [comment]
Thanks for reply. Wanted just to see how easy would be to bring WordPress closer to news portals. Native gallery is big NO-NO for news portals and magazine layouts.

**Comment by mattheu** [comment]
Would like to support adding multiple images with the image field, but would be up to the implementor to actually build the gallery.

**Comment by StaggerLeee** [comment]
Oh no, you missed it. Dont ask you to make this form URL above. Just to make it possible for users to make it.
All Shortcake needs to do is visualize slider in TinyMce body. And of course on click at shortcode add, sort, remove images, but this is more WP native modal window and gallery management, nothing special new needs.

And more important. This from URL above is piece of cake to make manualy.
Most important would be Shortcake keep native [gallery id=""] shortcode for future change of mind, future developing, etc.

**Comment by StaggerLeee** [comment]
Just to say. I did not tested code form URL above and dont know if it works. It is just there for reference, because I cannot find anymore on Google right URL where I found code and used it. 
Have it in my snippets collections, but there is no need to paste it here and spam with it.

But principle is the same. 
WP native gallery shortcode stays the same in database, not strange shortcodes different plugins output and when you delete plugin you are in big troubles. [my-fancy-gallery id=""].

**Comment by cliffordp** [comment]
I know it's not ideal, but if you just HAVE to have a comma-separated list of attachment IDs, you can use the `post_select` field type (but then there's no image preview). For example:

```
        $postid_query_args = array(
            'post_status' => array( 'inherit' ),
            'post_type' => 'attachment', // default is 'post'
        );
...
...
                array(
                    'label'  => esc_html__( 'Attachment(s) to display', '' ),
                    'attr'   => 'postid',
                    'query'  => $postid_query_args,
                    'type'   => 'post_select',
                    'multiple' => true, // allow user to select more than 1 post
                    'description'  => esc_html__( 'Drop down list is all files from the Media Library. This shortcode argument can accept one or more comma-separated post/attachment IDs.', '' ),
                ),
```

**Comment by goldenapples** [comment]
Done in #508.
