### ISSUE TITLE
Support Fieldmanager for defining more complex fields

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#29]
We've started down the route of building our own form builder. However, it would be nice if we could instead reuse Fieldmanager for building more complex fields.

According to @mboynes, this should actually be pretty straightforward by creating our own Shortcode UI Fieldmanager Context.

**Comment by danielbachhuber** [comment]
@mattheu is going to take a swing at this

**Comment by danielbachhuber** [comment]
I'd like to leave this open for now to get @netaustin and @mboynes' thoughts on the implementation.

**Comment by netaustin** [comment]
It's on my weekend plan to download the plugin and play with it. In the meantime, I gave you another :star:

**Comment by danielbachhuber** [comment]
@netaustin @mboynes any thoughts? hoping to ship v0.1.0 tomorrow.

**Comment by danielbachhuber** [comment]
:ship: :ship: :ship:
