### ISSUE TITLE
Creating 2 same shortcodes turn the first into its loading state

### ISSUE THREAD

**Issue by bfintal** [wp-shortcake/shortcake#300]
Replicate:
- Create a new page
- Create an X shortcode (any)
- Create another X shortcode (the same)

Result: ![result](http://cl.ly/image/3N1d3I0g131l/Image%202015-04-24%20at%202.21.16%20AM.png)

Tested with a master copy a few days ago, version v0.3-alpha. And testing in WP 4.2-RC4-32277

**Comment by danielbachhuber** [comment]
I can reproduce when the shortcodes have the same arguments. When they have different arguments, it works as expected.

> Tested with a master copy a few days ago, version v0.3-alpha. And testing in WP 4.2-RC4-32277

Does it reproduce in earlier versions?

**Comment by bfintal** [comment]
Before updating to RC4, I also previously tried in WP 4.2-RC1 and the same thing happens

**Comment by bfintal** [comment]
Also happens in the released 4.2
