### ISSUE TITLE
Continuously fetching shortcode preview bug when Shortcode content is empty.

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#301]
If a shortcode preview response is successful but empty, then shortcake will attempt to fetch the preview again. This will happen continuously.

The fetch is triggered in the `getContent` method - when no content is found. 

However a super-simple fix for this is to trigger the ajax request on initialization. 

This will fix the infinite requests bug, but the preview will still be broken - MCE views will continue to show the preview as loading if content is empty. But I think this should be up to the shortcode author to provide some sort of feedback?

**Comment by danielbachhuber** [comment]
I think an error message would be appropriate. Or our own view that says "this post element has no output"

For all the shortcodes we have, I haven't yet started to throw misconfiguration notices for when the shortcode has no output.

**Comment by mattheu** [comment]
Actually - I think typically a shortcode shouldn't display an error notice on the front end of a site. Failing silently would often be better.

I'm up for having some kind of notice.

**Comment by mattheu** [comment]
Fixed in #302.

Opening a new issue to discuss error mesages. #303
