### ISSUE TITLE
Parse error: syntax error, unexpected T_FUNCTION (when I activate plugin)

### ISSUE THREAD

**Issue by hirejordansmith** [wp-shortcake/shortcake#305]
I'm getting this error when I try to install and activate the plugin on a new site (using newest version)

Parse error: syntax error, unexpected T_FUNCTION in /home2/trainit2/public_html/nicolaiyde/wp-content/plugins/shortcode-ui/shortcode-ui.php on line 31

I've done a theme / plugin conflict test and the issue persists with no plugins active and using base WP 2015 theme.

I have shortcake installed on other sites with no issues.

Any ideas what would cause this kind of error?

**Comment by danielbachhuber** [comment]
Shortcake requires PHP5.3+
