### ISSUE TITLE
possible to render a shortcode without adding an ui?

### ISSUE THREAD

**Issue by zu** [wp-shortcake/shortcake#306]
Just a question/feature request that I don't know where else to ask.

I' d like to use shortcake to render an existing shortcode from a plugin (Delightful Downloads).
There is no need for a UI as the plugin has its own. I only want to see it in TinyMCE as it would be in the frontend. And surely I'd expect to open the Download Edit page on click on the rendered element.

Would this be possible? And what are the steps?

Some hints would be highly appreciated.

**Comment by danielbachhuber** [comment]
> Would this be possible?

Seems possible, although it would need a fair bit of custom code.

> And what are the steps?

You'll likely need to hire help if you're unable to get started on your own.
