### ISSUE TITLE
Implement events on attribute fields that can be listened to

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#316]
I'm working on an issue that requires listening to changes on an attachment field, and updating other fields in a shortcode if they're not already set with the values from the attachment.

This seems as though it would be much easier to do if each field surfaced some custom events which could be listened to by another controller.  Would it make sense for each view to trigger an event in its `updateValue` callback which could be listened to by other observers? Or is there already a way of doing this which I'm not seeing? 

More generally, I guess what I'd like is an API for extending attribute fields with custom scripts. Is this being discussed, or does anyone how ideas how best to approach it?

**Comment by noppanit** [comment]
I don't think it's been discussed. Are you thinking of something like KnockoutJs or AngularJs? with observer pattern?

**Comment by goldenapples** [comment]
Yeah, my initial thought was to how in AngularJs, it would be something like `$scope.$emit('eventname', data)`, then you would need to attach a listener on the rootScope to pass that data to another scope.

In Backbone, the pattern seems to be to broadcast an event from a view like `this.trigger('eventname', data)` and then listen from another backbone model like `this.listenTo( editAttributeField, 'eventname', callback )`.

Seems like this could be accomodated by triggering events at a few relevant points (at the end of `updateValue` for editAttributeField, at the end of `updateAttachment` for attachment fields, etc. I'm not sure I'm seeing the whole architecture though.

**Comment by danielbachhuber** [comment]
> I'm not sure I'm seeing the whole architecture though.

When I was working on `editAttributeField` last, I was thinking it might be useful to have some base attribute model each field should extend.

**Comment by danielbachhuber** [comment]
@goldenapples Are you happy enough with this to close?

**Comment by goldenapples** [comment]
Yup, I think its good and should work for my purposes. I wanted this for a couple of attributes in Image Shortcake, so I'll use it there and see if it works for everything I wanted.

I'm debating whether there should also be an action that fires at the shortcode level, so that you can register a listener on all attributes to a shortcode. But I haven't thought of a use case where that would be necessary yet, so I'll leave it out until I see one.
