### ISSUE TITLE
urlencode or otherwise escape attributes when sending to editor

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#321]
Quote marks in attributes, even if escaped, break the parser. HTML tags in attributes are subject to kses, and then escaped as attributes, making it impossible to use HTML markup in attribute values.

A [comment on trac](https://core.trac.wordpress.org/ticket/32078#comment:7) suggests passing attribute values through urlencode on save / urldecode on extract to get around these problems. This would greatly extend the usefulness of these shortcodes, making it feasible for example to have a rich editor attribute type.

**Comment by danielbachhuber** [comment]
> suggests passing attribute values through urlencode on save / urldecode on extract to get around these problems.

You must be telepathetically connected with @sanchothefat :) #322. Personally, urlencode seems like a massive hack. I'd be interested in any alternatives you have to suggest.

**Comment by roborourke** [comment]
I think any kind of encoding is bound to be a hack, it would either require an overhaul of the shortcode regex or even the whole shortcode system. As soon as it became easy to add more complex data into a shortcode eg. through shortcake we were bound to hit this limitation.

Maybe the approach would be generate some special nested XML markup in the `inner_content` where attributes can be extracted from though not sure about backwards compat or feasibility of that. Still got the 4.2.1 issue with HTML breaking views there though.

**Comment by danielbachhuber** [comment]
This is addressed on master with #496.
