### ISSUE TITLE
Require that select elements have a value set.

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#323]
Currently, the shortcode attribute model's `updateValue` callback only happens on `change` events. 

This is confusing with attribute fields like selects, radio buttons, and checkboxes, where the user would assume that the state the field is in when the form is initially rendered -- the first item in a select list, or an unchecked value for a checkbox -- is the value they are selecting. However, unless the user actually changes the select to a different value and then changes it back, that attribute will simply not exist on the shortcode model.

I think a more intuitive approach would be, if no `value` is set on an attribute when registering shortcode ui for a shortcode, to default the `value` to the first item in the list. This would preserve the expected behavior of HTML forms.

**Comment by fourfour** [comment]
+1

**Comment by danielbachhuber** [comment]
:+1:

**Comment by danielbachhuber** [comment]
No longer applicable https://wordpress.slack.com/archives/feature-shortcode/p1433790569000071

**Comment by cggit** [comment]
this seems to still be an issue
