### ISSUE TITLE
Allow Shortcode UI to be displayed in post_type: page

### ISSUE THREAD

**Issue by bastienho** [wp-shortcake/shortcake#328]
Hi,

Everything is in the title, the new feature "post_type" seems to allow to integrate the UI in any post_type, but not for native pages.
Is it true, or did I miss something ?

regards

**Comment by danielbachhuber** [comment]
> the new feature "post_type" seems to allow to integrate the UI in any post_type, but not for native pages.

Can you share more details on your configuration, so we can be of assistance debugging?

**Comment by bastienho** [comment]
Hi, thank you.

So pages should be supported ?

so, this is a bug, and here is the configuration :  **WP 4.2.2 Multi-site**, with the following plugins :
- Advanced Custom Fields
- Advanced Post List
- Akismet
- Allow Javascript in Text Widgets
- Blog Copier
- Contact Form 7
- Contact Form 7 Tiny MCE
- Contact Form DB
- Duplicate Post
- EELV Share Post
- Enable Media Replace
- Event Post
- Facebook Thumb Fixer
- Improved User Search in Backend
- Lightbox Gallery
- Logos des partis politiques français
- MindCat
- MultiDomain
- MultiSite Widget Link
- My shared widgets
- OST 3D Image tag cloud : Beta 1.0
- Really Simple CAPTCHA
- Ressources
- Rich Tax Description Editor
- Search Everything
- Shortcode UI (off course)
- SoundCloud Shortcode
- SpeakUp! Email Petitions Fake Fields adder
- SpeakUp! Email Petitions Importer
- SSL Insecure Content Fixer
- TinyMCE Advanced
- Unfiltered MU
- Upload Media by Zip
- Varnish HTTP Purge
- Video Thumbnails
- WordPress importer
- WP-Optimize
- WP-Piwik
- WP Calameo
- WP Multi-Network
- wpNSC (Not Short Code)
- WP Scheduled Read-Only
- wp_pdf.js
- YAST : Yet Another Support Tool

**Comment by danielbachhuber** [comment]
> So pages should be supported ?

Yes

> so, this is a bug, and here is the configuration : WP 4.2.2 Multi-site, with the following plugins :

There's likely some plugin conflict. I'd recommend trying on a brand new WordPress install with no plugins, and then install and activate each plugin one by one to see what might be causing the issue.

**Comment by bastienho** [comment]
Confirmation, this was a javascript error somewhere which was causing the bug.
