### ISSUE TITLE
New lines stripped in textarea field type

### ISSUE THREAD

**Issue by MaximeCulea** [wp-shortcake/shortcake#331]
Hi,

There is a bug between WordPress 4.2.\* (tested on 4.2.2) and the textarea field type.
When adding new lines in a textarea while inserting the shortcode in tinymce, the new lines are stripped off and the shortcode is not rendering the wanted display.

The same plugin works on  4.1.5 WordPress.

PS : Both essai were on a fresh empty site.

Thank you

**Comment by danielbachhuber** [comment]
Is this the same as #312 and https://core.trac.wordpress.org/ticket/32078

**Comment by MaximeCulea** [comment]
Ok it seems this ticket looks like mine but I did not found the same issue. In fact the probleme is that shortcake preview works ( ajax do_shortcode ) when using textarea, but when saving it into the wysiwyg it does not render at all by the fact new lines are not retrieved in html but in text.

You can find attached, some sceenshots for this.
![shortcake-contribution](https://cloud.githubusercontent.com/assets/5576409/7722233/8f242342-fede-11e4-90e1-a01dfd1a0a7d.png)
![shortcake-preview](https://cloud.githubusercontent.com/assets/5576409/7722232/8f21f310-fede-11e4-8063-7988329ed9df.png)
![wysiwyg-contribution](https://cloud.githubusercontent.com/assets/5576409/7722234/8f248396-fede-11e4-9a9e-98dac184f278.png)

With yout ticket's example, do you suggest me that it will be fixed in the 0.4v ?
My issue make me wonder about "Tested up to: 4.2.1".

Anyway thank your for your repply and I am waiting to hearing from you soon.
Best,
