### ISSUE TITLE
Redundant whitespace in shortcodes without attribute

### ISSUE THREAD

**Issue by w3guy** [wp-shortcake/shortcake#334]
I have some shortcodes without attributes. when added to a post via shortcake, it render s expected but viewing the shortcode in text mode reveals a redundant white space before the closing brace like so `[pinnacle ]` although no adverse/side effect. just wana bring this to you guys notice.

FYI: am using the v3 in WordPress repo.

**Comment by danielbachhuber** [comment]
I've seen this before. We'll try to get it fixed for the next release.
