### ISSUE TITLE
Fatal error when activating TinyMce for frontend comments

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#337]
I use latest and best code for comments visual editor from WP Edit PRO plugin.

Shortcake gives: 

Fatal error: Call to undefined function get_current_screen() in D:\EasyPHP\data\localweb\some_test_wp\wp-content\plugins\shortcode-ui\inc\class-shortcode-ui.php on line 85
Disabled Shortcake plugin and editor shows in comments and working fine as before.

Not that I use now Shortcake for anything, just want you to know.

**Comment by StaggerLeee** [comment]
Why not check if visual editor is activated on frontend and use Shortcake in the same way as in backend ?
Is it possible at all ?

I see many uses here. bbPress, comments, support forums, all possible media in comments to make it easy for beginners but arranged with Shortcake to exclude security risks, very customized media modal box, customized URL field, all possible fields, etc...

**Comment by danielbachhuber** [comment]
> Why not check if visual editor is activated on frontend and use Shortcake in the same way as in backend ?

Shortcake will still work on the frontend. The feature where a developer can limit a given shortcode UI to specific post types will only work on the backend until #366 is fixed.
