### ISSUE TITLE
Sample UI registration doesnt work

### ISSUE THREAD

**Issue by dougcassidy** [wp-shortcake/shortcake#343]
I have got shortcake running on a a simple text field.  Works great for that, thanks.

However, besides a sytnax error typo in https://github.com/fusioneng/Shortcake/wiki/Registering-Shortcode-UI , 
The shortcode you register is expecting a double ended shortcode with content in the middle, like [pullquote source="default cite"]The quote would be here.[/pullquote] And the shortcake is producing: [pullquote source="default cite" content="The quote would be here."] 

It does seem that the double ended type of shortcode would be the thing, for a textarea type shortcode.

**Comment by danielbachhuber** [comment]
Sorry, that example is quite out of date. You'd be better off to look at the dev plugin: https://github.com/fusioneng/Shortcake/blob/master/dev.php
