### ISSUE TITLE
Attachment Field: Clicking on attachment should let me pick a different attachment

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#350]
![image](https://cloud.githubusercontent.com/assets/36432/7990138/bf76ee50-0aa3-11e5-89b0-479c4df08aae.png)

**Comment by davisshaver** [comment]
@mkeppel, assigning to you for review.

**Comment by danielbachhuber** [comment]
One thing I noticed: it would be nice if the library retained the selection when I opened it

**Comment by danielbachhuber** [comment]
I'll handle retaining the selection in v0.6.0
