### ISSUE TITLE
Question: is it all possible to remove shortcodes?

### ISSUE THREAD

**Issue by zedejose** [wp-shortcake/shortcake#352]
(I have searched issues and code but found no answer, apologies if it is already answered elsewhere)

Use case: I want to only offer a subset of loaded shortcodes to content authors (less confusing)

**Comment by danielbachhuber** [comment]
Well, you need to opt-in to registering UI for shortcodes. Do you need to de-register UI?

**Comment by zedejose** [comment]
Not sure I understand the question, tbh. I simply need to, say, _not_ see 'pbs_button' (or any other of my choice)

**Comment by zedejose** [comment]
Got it sorry, shortcodes are one thing, the UI another, so yes, de-register the UI for a shortcode.

**Comment by danielbachhuber** [comment]
> I simply need to, say, not see 'pbs_button' (or any other of my choice)

You won't see it, unless the developer for `pbs_button` registered UI for it.

**Comment by zedejose** [comment]
I'm an idiot at completely the wrong place, @danielbachhuber, sorry about that. This is what I needed :)

https://github.com/gambitph/Page-Builder-Sandwich/wiki/Misc-Filters

Ok to close.

**Comment by danielbachhuber** [comment]
I'm adding a filter for you too #353 so you can disable UI (which you can't easily do right now).

**Comment by zedejose** [comment]
Brilliant, thanks
