### ISSUE TITLE
Request: Add ability to define custom shortcode attributes and values

### ISSUE THREAD

**Issue by aaemnnosttv** [wp-shortcake/shortcake#368]
I have a shortcode which accepts a few known attributes, as well as any number of custom attributes - they could be anything.

The known attributes could have fields registered for them, but for the unknowns I would like to be able to register the ability to add custom simple key/value pairs in the UI.

Thoughts?

**Comment by danielbachhuber** [comment]
Intriguing idea. I've filed it as a potential enhancement.

**Comment by mattheu** [comment]
We discussed this in the feature-shorcode meeting on Slack today.

Our concern is that adding custom key/value pairs, doesn't give you any info on what needs to be entered, and isn't a great user experience. No better than the current state of shortcodes.

But we discussed the possiblity of optional attributes, with a select dropdown for adding them. This seems a pretty achievable feature, keeps all the advantages of the UI, and should address much of the use case for this. Any thoughts?

**Comment by aaemnnosttv** [comment]
I agree, not a great experience, but it _is_ better than the current state of shortcodes when you consider everything else that comes with Shortcake - particularly the rendered placeholder in the visual editor. IMO, this feature is a wonderful enhancement for any shortcode, regardless of what the UI for editing it looks like.  It's also better than if the UI were enabled for some attributes, and then in order to add other custom/user-defined attributes, the user has to close the UI, then switch to the text tab and then continue editing manually.

Another benefit of entering the value with the UI would be the ability to do things like escape quotes or other characters which prevent the shortcode from being broken by user input.  So, there definitely is a lot of value just in using the UI, even if it's not as easy/clear-cut as a "standard" pre-defined field.

> Our concern is that adding custom key/value pairs, doesn't give you any info on what needs to be entered

In my use case, custom attributes become html attributes for the element that the shortcode generates, so there's no explanation necessary as to what needs to be entered.  However, registering a field for every possible html attribute is not practical, and trying to would still be limited and ultimately, a much worse user experience.  There are however certain reserved attributes I want to be able to utilize the full power of the UI for, like the awesome post select field.

I admit my use case here is probably an edge case, but that doesn't mean other shortcodes may also not benefit from the feature.

The optional attributes is a good idea, but it doesn't solve my issue.

I am only really suggesting this feature as an optional opt-in via the shortcode's UI configuration.  I don't think it would be a good addition to add to all/every shortcode UI.

**Comment by danielbachhuber** [comment]
We're not going to support creating arbitrary key=>value pairs through the Shortcake UI.
