### ISSUE TITLE
Checkbox does send invalid data to shortcode function when in administration

### ISSUE THREAD

**Issue by fkonecny** [wp-shortcake/shortcake#369]
Hello,
when I use checkbox in the administration I get different results than on the front page.
For better insight I include var_dumps from xdebug as pictures.
Front page works correctly once set up:
![bug-front page](https://cloud.githubusercontent.com/assets/996465/8455162/e65564b0-2002-11e5-85f8-58047e6a3b04.png)
But when I open editor and look at it it returns 'right' => '1' for every element and when I change the settings to correct one (rechecking and updating the element) it turns out to be absolutely different than expected.
![bug-admin-page](https://cloud.githubusercontent.com/assets/996465/8455209/3e16a2c2-2003-11e5-8243-03b2a6feabb5.png)

**Comment by fkonecny** [comment]
From my little investigation with debugging I found out that it already sends wrong shortcode. As I do not know how to work with Backbone.js I am absolutely clueless what to do.

**Comment by danielbachhuber** [comment]
@yadsk Can you share the code you're using to register the shortcode UI?
