### ISSUE TITLE
Implement batch fetching of shortcode previews

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#371]
Currently Shortcake makes a separate ajax request for each shortcode in a post content. It would speed up the initial time it takes to get an editor instance to a stable state if all of these requests could be combined into one request on the initial load.

I haven't investigated too deeply to determine the level of complexity for this, but if it's possible, it could make the experience of opening a post with many shortcodes much smoother.

**Comment by danielbachhuber** [comment]
:100:

**Comment by bobbingwide** [comment]
Is this a bit like running do_shortcode on $post_content with an intercepting function to wrap the output of each shortcode with whatever the editor needs to detect the expanded shortcodes?

**Comment by goldenapples** [comment]
> Is this a bit like running do_shortcode on $post_content with an intercepting function to wrap the output of each shortcode with whatever the editor needs to detect the expanded shortcodes?

In theory, yes. Functionally, it'll work a lot different because the content is being fetched through `wp.mce.views`. Currently each view has its own `fetch()` method which makes an ajax post to `do_shortcode`, and renders the response. I'm picturing passing all the shortcodes to render off to another class which makes a single call for all the views, which will then return a promise that each view can handle on its own.

**Comment by danielbachhuber** [comment]
:ship:
