### ISSUE TITLE
Russian translation

### ISSUE THREAD

**Issue by ghost** [wp-shortcake/shortcake#374]
Sorry, didn't know how I could contact you.

So, here's the Russian translation: http://ukstudio.ru/languages.zip

Great job and awesome plugin!

**Comment by danielbachhuber** [comment]
Thanks @ninetienne! This translation will be included in the next release.

**Comment by ghost** [comment]
I've also added translation for the Image Shortcode, however when adding the files to the plugin's language folder, I don't get the strings translated :(

Here's the translation: http://ukstudio.ru/languages-image.zip
