### ISSUE TITLE
Only register shortcode UI when editor is being created

### ISSUE THREAD

**Issue by jrfnl** [wp-shortcake/shortcake#385]
Lean loading - based on the current example code (dev.php), the UI would always be registered, no matter whether in front-end, back-end, non-editor admin page etc. as it hooks into `init`

I'd like to suggest creating a hook people should use to register the shortcode UI on and having that hook only run when an editor is being created.

So then it would become something along the lines of:

``` php
add_action( 'register_shortcode_ui', 'my_plugin_shortcode_ui_registration_function' );

function my_plugin_shortcode_ui_registration_function() {
    shortcode_ui_register_for_shortcode(
        'shortcode_1',
        array(...)
    );
    shortcode_ui_register_for_shortcode(
        'shortcode_2',
        array(...)
    );
}
```

This would also remove the need for the `function_exists( 'shortcode_ui_register_for_shortcode' )` checks as the hook will only be run from Shortcake and therefore the function will be available.

**Comment by danielbachhuber** [comment]
> I'd like to suggest creating a hook people should use to register the shortcode UI on and having that hook only run when an editor is being created.

I dig it #388

**Comment by cggit** [comment]
admin_init seems to work but Im having trouble getting the current page ID so early. If you go the custom hook route can you pass it some variables so we can have some context.

**Comment by danielbachhuber** [comment]
`register_shortcode_ui` will be the trick.
