### ISSUE TITLE
Bug ? Json parse error on Ajax calls

### ISSUE THREAD

**Issue by jrfnl** [wp-shortcake/shortcake#387]
WP 4.2.2
Shortcake 0.5

Using the dev.php file for testing - Shortcake Dev shortcode
All ajax calls (page select, preview) fail with `SyntaxError: Json.parse: unexpected character` message.

Response samples:
`{"success":true,"data":{"posts":[],"found_posts":0,"posts_per_page":10}}`
`{"success":true,"data":{"posts":[{"id":2,"text":"Voorbeeld pagina"}],"found_posts":"1","posts_per_page":10}}`
`{"success":true,"data":"\n\t\t<section class=\"pullquote\" style=\"padding: 20px; background: rgba(0,0,0,0.1);\">\n\t\t\t<p style=\"margin:0; padding: 0;\">\n\t\t\t\t<b>Content:<\/b> <\/br>\n\t\t\t\t<b>Source:<\/b> <\/br>\n\t\t\t\t<b>Image:<\/b> <\/br>\n\t\t\t<\/p>\n\t\t<\/section>\n\n\t\t"}`

**Comment by danielbachhuber** [comment]
Is this on a clean install of WordPress? I'm unable to reproduce.

**Comment by jrfnl** [comment]
It sort of is - it is clean install, but I do have some debug plugins running - some of which also use ajax and are not experiencing this issue. Will see if I can find the time to look into it some more.
