### ISSUE TITLE
updateAttachment doesn't error out on missing attachments

### ISSUE THREAD

**Issue by paulkarpenko** [wp-shortcake/shortcake#390]
If I attach an image to a shortcode, then delete that image from the media library, the shortcode edit screen does not give me the ability to clear out the attachment or replace it. The attachment preview block simply sits in the loading state forever. 

Moving $container.removeClass( 'loading' ); out of the .done() promise and into an .always() promise will fix the issue.

**Comment by danielbachhuber** [comment]
Thanks for the report, @nvarchar. We'll get this fixed.

**Comment by danielbachhuber** [comment]
:hammer:
