### ISSUE TITLE
Question: Enqueueing scripts for Preview

### ISSUE THREAD

**Issue by GaryJones** [wp-shortcake/shortcake#394]
When looking at the Visual view of the Editor, Shortcake is correctly converting my shortcode into a crafted `<div>` (inside a few other divs which are presumably to wrap any embedded content). However, I then need to add in some JS files that populate my div with content some map and graph visualizations. The charts are displaying fine on the front-end.

Any suggestions for the best way to enqueue scripts and styles in the footer that are needed for the Preview, but only when the shortcode is parsed and shown as embedded content on the Edit screen? Is there a Shortcake or other suitable action hook?

Thanks.

**Comment by danielbachhuber** [comment]
> Any suggestions for the best way to enqueue scripts and styles in the footer that are needed for the Preview, but only when the shortcode is parsed and shown as embedded content on the Edit screen? Is there a Shortcake or other suitable action hook?

Yep, check out how we're doing it with Shortcake Bakery: https://github.com/fusioneng/shortcake-bakery/blob/master/inc/class-shortcake-bakery.php#L63

So we can make our documentation better, where you would expect to find this information?

**Comment by GaryJones** [comment]
Thanks - I had seen that hook when I skimmed through Shortcake Bakery, but hadn't tracked down if it actually was the right hook to use or not.

> So we can make our documentation better, where you would expect to find this information?

The demo plugin (dev.php), and perhaps an "Enqueue Scripts for Editor Preview" wiki page?

**Comment by GaryJones** [comment]
Why does `get_shortcake_admin_dependencies()` return instead of echo?

Also, how might I limit adding of scripts to only appear for the first instance of the shortcode / only once for all shortcodes?

**Comment by danielbachhuber** [comment]
> Why does get_shortcake_admin_dependencies() return instead of echo?

So that it can be easily used in both contexts (return and echo)

> Also, how might I limit adding of scripts to only appear for the first instance of the shortcode / only once for all shortcodes?

The previews for each shortcode are individually generated, so your callback can return each time the action is called.
