### ISSUE TITLE
Demo plugin (dev.php) observations

### ISSUE THREAD

**Issue by GaryJones** [wp-shortcake/shortcake#395]
Just a few thoughts from someone new to Shortcake, and who used the code in `dev.php` as a starting point to add support to a custom plugin. I copied all of the `init` hook callback into my code and amended from there.
- Make it clear that there are actually two examples going on here. Maybe split into two `init` hook callbacks, and comment them as "Minimal" and "Typical"/"Advanced".
- Add more comments. The ones that are there for the configuration keys are definitely useful, but some don't have them. For instance, `inner_content` seems to be a simpler way of adding textarea field without needing all of the `attrs` - that's the effect it had for me anyway - but it has no comment to make it clear. `post_type` was guessable as being the post types that the post element should be available for, but a comment with words to that effect would help clarify it.
- Make it clear somewhere that the Add Media -> Insert Post Element link only appears when there's at least one post element that can be added for the current post type. I was editing a Page, and with `post_type` not commented out, but the Minimal example commented out, it took me a few moments to guess / work out why the link wasn't present and my screen didn't match the screenshots. (Thinking long-term, this may become a UX issue for when it's rolled into Core)
- Internationalise strings. It doesn't matter which text domain is used, but having the labels, buttons, placeholders and other visible strings already wrapped in `__()` will save developers time, and help clarify what is a visible string and what's some other config value.
- The `attrs` array is a strange fellow - in my mind, _most of the keys here are actually for the field that will be displayed in the UI, not for the shortcode attribute_. `type` is always a generic word and it is trickier to work out what it is the type of when thinking in shortcode attributes, but easier if thinking in fields. For me (and I realise how non-BC this would be), it would be clearer to focus on fields and have something like:

``` php
// Available shortcode attributes fields and default values. Required. Array.
// Fields model expects 'shortcode_attr', 'type' and 'label'
// Supported field types: text, checkbox, textarea, radio, select, email, url, number, and date.
'fields' => array(
    array(
        'label'          => __( 'Attachment', 'your-text-domain' ), // Field label
        'type'           => 'attachment', // Field type
        'libraryType'    => array( 'image' ), // Media type to insert
        'addButton'      => __( 'Select Image', 'your-text-domain' ); // Button text that opens Media Library
        'frameTitle'     => __( 'Select Image', 'your-text-domain '); // Media Library frame title
        'shortcode_attr' => 'attachment', // Shortcode attribute this field populates
    ),
    array(
        'label' => __( 'Citation Source', 'your-text-domain' ),
        'type'  => 'text',
        'meta'  => array( // Holds custom field attributes.
            'placeholder' => __( 'Test placeholder', 'your-text-domain' ),
            'data-test'   => 1, // Custom data attribute
        ),
        'shortcode_attr'  => 'source',
    ),
    ...
);
```
- Add an entry for each significantly different supported field type. I needed a select field, and I guessed the key was called `options` with entries for `value => label` (so, it is somewhat intuitive naming), but when demo code exists, devs shouldn't have to be guessing like that. Probably don't need one for each text `<input>` type, but input, textarea, select, radio, post_select and attachment may all have slightly different keys that only apply to them. It gives devs something easy to copy, paste and tweak.
- There's an entry for `attachment` and `post_select`, but these are not listed in the "Supported field types" list. According to the changelog, a colour picker is also supported, but this isn't mentioned anywhere else.
- Include an example of using the `shortcake_ui_after_do_shortcode` for enqueueing a script or style sheet to make the rendered output show up correctly in the Editor.

Overall, I've got up and running with a UI for building my custom shortcode extremely quickly (thanks!), so there's a lot done right - the above observations and suggestions are merely feedback to consider or ignore as you see fit :-)

**Comment by danielbachhuber** [comment]
Thanks @GaryJones. We'll get this cleaned up in the next release.

**Comment by danielbachhuber** [comment]
Bumping out of v0.5.0, but I'll pick this up first thing for v0.6.0

**Comment by goldenapples** [comment]
An additional request I'd like to see tackled in the demo plugin: an example of using the plugin's js hooks to conditionally show some of the attribute fields.

**Comment by danielbachhuber** [comment]
From https://github.com/fusioneng/Shortcake/pull/511#issuecomment-147735141

> Also one thing I'm thinking here is that it would be good to demonstrate using the new hook register_shortcode_ui for registering UI on, rather than hooking everything on init.

**Comment by danielbachhuber** [comment]
@GaryJones mind giving https://github.com/fusioneng/Shortcake/blob/master/dev.php a once-over for any remaining improvements you'd suggest?

**Comment by GaryJones** [comment]
Will take a look tomorrow. Thanks @danielbachhuber.

**Comment by GaryJones** [comment]
I'd suggest something like: [dev.php](https://gist.github.com/GaryJones/1b96696efdde85ba4b62)
Diff between your current dev.php and my suggestion: [diff](https://gist.github.com/GaryJones/1b96696efdde85ba4b62/revisions)

Points:
- Structured plugin documentation - [introduction](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L22-L32) makes it clear that the plugin is handling two shortcodes, and is split up into four clear stages. A few extra clear linespaces between sections, and a numbered heading allow developers to navigate their way through the example plugin.
- More verbose [explanation](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L39-L50) regarding check for Shortcake and use of admin notice (and why self-deactivating would not be a Good Thing).
- A few (probably personal) formatting changes that I think may the code easier to read and comprehend.
- i18n added to [two](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L68) [strings](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L119).
- Changed the [textdomain](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L8) in the plugin header and i18n functions to `shortcode-ui-example`, which makes it a little clearer that it should be changed for individual plugins, and isn't just part of it being because it requires Shortcake.

Points not addressed:
- Showing all the different field types, like select, color picker etc. Although these are now [mentioned](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L175) in the demo file, it still leaves comments like [this](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L183) which doesn't help developers.
- `shortcake_ui_after_do_shortcode` snippet for showing how to enqueue dependencies if a shortcode is used.
- Changing the deeply nested arrays, so one doesn't end up with [this](https://gist.github.com/GaryJones/1b96696efdde85ba4b62#file-dev-php-L216-L220) may make the code easier to read by keeping the data and the call to `shortcode_ui_register_for_shortcode()` separate (easier var_dump debugging, refactor out to a separate function, etc.). One suggestion would be:

``` php
function shortcode_ui_dev_advanced_example() {
    /*
     * Define the UI for attributes of the shortcode. Optional.
     *
     * In this demo example, we register three fields - Attachment, Citation Source, and Select Page.
     *
     * If no UI is registered for an attribute, then the attribute will
     * not be editable through Shortcake's UI. However, the value of any
     * unregistered attributes will be preserved when editing.
     *
     * Each array must include 'attr', 'type', and 'label'.
     * * 'attr' should be the name of the attribute.
     * * 'type' options include: text, checkbox, textarea, radio, select, email,
     *     url, number, and date, post_select, attachment, color.
     * * 'label' is the label text associated with that input field.
     *
     * Use 'meta' to add arbitrary attributes to the HTML of the field.
     *
     * Use 'encode' to encode attribute data. Requires customization in shortcode callback to decode.
     *
     * Depending on 'type', additional arguments may be available.
     */
    $fields = array(
        array(
            'label'       => esc_html__( 'Attachment', 'shortcode-ui-example' ),
            'attr'        => 'attachment',
            'type'        => 'attachment',
            /*
             * These arguments are passed to the instantiation of the media library:
             * 'libraryType' - Type of media to make available.
             * 'addButton' - Text for the button to open media library.
             * 'frameTitle' - Title for the modal UI once the library is open.
             */
            'libraryType' => array( 'image' ),
            'addButton'   => esc_html__( 'Select Image', 'shortcode-ui-example' ),
            'frameTitle'  => esc_html__( 'Select Image', 'shortcode-ui-example' ),
        ),
        array(
            'label'  => esc_html__( 'Citation Source', 'shortcode-ui-example' ),
            'attr'   => 'source',
            'type'   => 'text',
            'encode' => true,
            'meta'   => array(
                'placeholder' => esc_html__( 'Test placeholder', 'shortcode-ui-example' ),
                'data-test'   => 1,
            ),
        ),
        array(
            'label'    => esc_html__( 'Select Page', 'shortcode-ui-example' ),
            'attr'     => 'page',
            'type'     => 'post_select',
            'query'    => array( 'post_type' => 'page' ),
            'multiple' => true,
        ),
    );

    /*
     * Define the Shortcode UI arguments.
     */
    $shortcode_ui_args = array(
          /*
           * How the shortcode should be labeled in the UI. Required argument.
           */
          'label' => esc_html__( 'Shortcake Dev', 'shortcode-ui-example' ),

          /*
           * Include an icon with your shortcode. Optional.
           * Use a dashicon, or full URL to image.
           */
          'listItemImage' => 'dashicons-editor-quote',

          /*
           * Limit this shortcode UI to specific posts. Optional.
           */
          'post_type' => array( 'post' ),

          /*
           * Register UI for the "inner content" of the shortcode. Optional.
           * If no UI is registered for the inner content, then any inner content
           * data present will be backed-up during editing.
           */
          'inner_content' => array(
              'label'        => esc_html__( 'Quote', 'shortcode-ui-example' ),
              'description'  => esc_html__( 'Include a statement from someone famous.', 'shortcode-ui-example' ),
          ),

          /*
           * Define the UI for attributes of the shortcode. Optional.
           *
           * See above, to where the the assignment to the $fields variable was made.
           */
          'attrs' => $fields,
    );

    shortcode_ui_register_for_shortcode( 'shortcake_dev', $shortcode_ui_args );
}
```

If you want to give examples for the first two points, I'll wrap this all up in a PR.

**Comment by danielbachhuber** [comment]
> If you want to give examples for the first two points, I'll wrap this all up in a PR.

Please do!

For the first, `color` doesn't accept any arguments beyond the defaults. `select` supports `options`, which is expected to be an array of `value=>label` pairs. Every attribute supports `label`, `description`, `type`, `attr`, and `encode`.

For the second, here's an example of how we're loading the Facebook SDK inside of the Shortcake preview: https://github.com/fusioneng/shortcake-bakery/blob/master/inc/shortcodes/class-facebook.php#L24

**Comment by danielbachhuber** [comment]
@GaryJones Will you be able to get to this in the next couple of days? If not, I'll turn your snippet into a pull request.

**Comment by GaryJones** [comment]
Sorry Daniel, this slipped my mind. I'll get to this this afternoon. If not, go ahead and do it yourself.
