### ISSUE TITLE
JS error if $content but no 'inner_content' arg

### ISSUE THREAD

**Issue by cliffordp** [wp-shortcake/shortcake#401]
If the shortcode's `args` array does not have `inner_content` argument but the Editor has content between opening and closing shortcode tags, clicking on Shortcake's "Edit" button (pencil icon) causes a JavaScript console error for https://github.com/fusioneng/Shortcake/blob/fed5de982e437835c6b204d7dc495a883e091b40/js/build/shortcode-ui.js#L455 and clicking Shortcake's Edit button does not open the shortcode UI.

Error message: `Uncaught TypeError: Cannot read property 'set' of undefined`
<img width="927" alt="screenshot 2015-07-28 11 35 03" src="https://cloud.githubusercontent.com/assets/1812179/8937224/b83c7080-351c-11e5-9e90-99663384cbf1.png">

Example with my custom `mdl-badge` shortcode:
- `[mdl-badge badge_text="Inbox" data="7"]` is ok (self-enclosed shortcode) **<-- how this particular shortcode is designed**
- `[mdl-badge badge_text="Inbox" data="7"][/mdl-badge]` is ok (`$content` == '')
- `[mdl-badge badge_text="Inbox" data="7"]hello[/mdl-badge]` causes JS error (`$content` == 'hello')

The shortcode's rendering still works, just not the Edit button.

So the issue is if someone manually creates/edits shortcodes in Text editor, they could shoot themselves in the foot and not know how to fix, since it's not obvious the issue is because there's `$content` but no `inner_content` argument

**Comment by danielbachhuber** [comment]
Confirmed. I suppose we have a similar problem where attributes will be dropped if UI isn't registered for them.
