### ISSUE TITLE
Built-in way to detect if we're in TinyMCE with Shortcake enabled?

### ISSUE THREAD

**Issue by cliffordp** [wp-shortcake/shortcake#407]
Is there a built-in way to detect if we're in TinyMCE with Shortcake enabled?

If not, I'd like to see one added to Shortcake so my shortcode plugin that relies on Shortcake can say "if we're in a TinyMCE with Shortcake active, run this function"

I hope this request makes sense.

tyvm

**Comment by danielbachhuber** [comment]
Could you add a callback to `enqueue_shortcode_ui` and set a constant?

**Comment by cliffordp** [comment]
Just brainstorming here. Don't mind me ;)

I think having something like DOING_AJAX (https://github.com/fusioneng/Shortcake/issues/399) but for Shortcake would be helpful -- e.g. DOING_SHORTCAKE?

I'm thinking I want to use this constant / callback / whatever in multiple ways:
1) as an alternative to is_admin() because what about front-end post editors?

```
// we do NOT want Shortcake to render this shortcode, just to be able to edit it
if( is_admin() ) {
    return '';
}
```

Maybe thinking along the same lines as being able to disable Shortcake "edit existing" UI  (https://github.com/fusioneng/Shortcake/issues/414)

2) as a way to enqueue styles/scripts in the editor only when needed
but then maybe DOING_SHORTCAKE would be too late to enqueue on front-end and/or admin?

I'm still deciding exactly what I want to do but maybe the `enqueue_shortcode_ui` or `shortcode_ui_loaded_editor` actions are sufficient, at least for these 2 use cases.

Feel free to share any advice.

**Comment by danielbachhuber** [comment]
While rendering the shortcode, you could use `did_action( 'shortcode_ui_before_do_shortcode' )`

We can keep this open as an enhancement but, given there are reasonable workarounds, I don't see the need to address it immediately.

**Comment by cliffordp** [comment]
More robust documentation if nothing else. No worries. tyvm for the help.

**Comment by danielbachhuber** [comment]
I'm adding `SHORTCODE_UI_DOING_PREVIEW` constant for this purpose.
