### ISSUE TITLE
Auto detect short codes

### ISSUE THREAD

**Issue by pippinsplugins** [wp-shortcake/shortcake#41]
This is awesome but it would be more awesome if it automatically detected all registered short codes.

Retrieving a list of all short codes and their attributes is pretty straight forward, so the only part that wouldn't be included by default (I think) is the image.

Detecting short codes automatically would make this far more useful since it would remove the requirement of plugin and theme authors registering their short codes themselves. Instead of 1/100 short codes being supported, 99/100 short codes would be supported.

**Comment by solepixel** [comment]
Yes, This. I've been wanting this for a long time and definitely know there are limitations with the way WordPress shortcodes are implemented, but I would love to see a collection of existing shortcodes as part of this. Have to agree with @pippinsplugins that it will encourage (and make it easier for) developers to implement this in their plugins if it's already being done. Shortcodes are a mess in the editor (especially when it comes to wrapping paragraph tags) and a cleaner look to all of them by default would be really awesome.

**Comment by danielbachhuber** [comment]
> Retrieving a list of all short codes and their attributes is pretty straight forward, so the only part that wouldn't be included by default (I think) is the image.

Actually, it's not possible to get the attributes for a shortcode, which is why you have to register the UI (with corresponding fields).

**Comment by pippinsplugins** [comment]
> Actually, it's not possible to get the attributes for a shortcode, which is why you have to register the UI (with corresponding fields).

Sure it is. Take all registered shortcodes and then retrieve each of their attributes by running the `shortcode_atts()` function. If you loop through each, you can retrieve a list of the default attributes for each shortcode.

**Comment by danielbachhuber** [comment]
> Take all registered shortcodes and then retrieve each of their attributes by running the shortcode_atts() function.

Shortcodes aren't required to use `shortcode_atts()`, nor does `shortcode_attrs()` indicate the type of attribute (e.g. text vs textarea vs. radio, etc.)

**Comment by pippinsplugins** [comment]
Right but all properly done shortcodes will. I think it'd be better to
detect as many shortcodes and atts as possible.

**Comment by danielbachhuber** [comment]
> I think it'd be better to
> detect as many shortcodes and atts as possible.

There's no explicit core support for this though, which means the implementation would be spotty at best. Happy to be convinced otherwise in a pull request, but I'm pretty sure explicitly registering UI fields is what we're stuck with for now.

**Comment by pippinsplugins** [comment]
It may be a little hacks but it seems like a much better solution to me. It
will be much easier for this to have more value and a wider audience if it
is not placed upon all other plugin developers to explicitly support it.

**Comment by jimmyandrade** [comment]
@pippinsplugins, but I started working in a small lib that could be used to add shortcodes and the data necessary for the shortcake automatically use them.

It's not exactly a way to detect shortcodes automatically, but you could use fewer lines to do what is already done. When I get home I will publish the lib repository in question.

**Comment by jimmyandrade** [comment]
As I said before, I'd publish the repository with the class that could be used to register shortcode for both WordPress Core and Shortcake (Shortcode UI plugin).

Well, I looked at @danielbachhuber's repo http://github.com/fusioneng/shortcake-bakery and I loved the proposal for a plug-in with some commonly used shortcodes. I decided to carry the class I created.

So, in an ideal world, if everyone use this class to register shortcodes, these would be seamlessly registered for Shortcake. You can see repo & my pull request here: fusioneng/shortcake-bakery/pull/4

**Comment by StaggerLeee** [comment]
Give us some easy option to pull frontend JS, CSS files of plugins, when calling specific registered Shortcake shortcode ? 
We could make simple Shortcake shortcode with same name a plugin has its shortcode.
This way we could maybe use all shortcodes that plugins make and have visual editing of them.

I dont know, Shortcake is still black hole for me.

**Comment by StaggerLeee** [comment]
I see now problem would be Shortcake cannot detect attributes from plugin shortcodes.
