### ISSUE TITLE
Not everything is in the code

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#419]
You still dont have a link here to your plugin in WP repository ?

I found out about Shortcake by pure chance, via one article on net. OK, i would find out about it via subscription via Make WordPress Core. Not many people do this.

Common, do some marketing, lift head above all the code.

**Comment by danielbachhuber** [comment]
> You still dont have a link here to your plugin in WP repository ?

Hm, I guess we don't.

> Common, do some marketing, lift head above all the code.

Marketing isn't a priority for this project, at this time.
