### ISSUE TITLE
How can I get the current page id to be used in shortcode_ui_register_for_shortcode

### ISSUE THREAD

**Issue by cggit** [wp-shortcake/shortcake#428]
I would like to use the current page ID in shortcode_ui_register_for_shortcode but it seems to hook too early and when I try to use the URL shortcake JS crumbles.

Any suggestions on how I can get/use the current page ID consistently while registering my UI.

**Comment by danielbachhuber** [comment]
On master, and in v0.5.0 soon, you'll be able to use the `register_shortcode_ui` action to register shortcode UI. This should be late enough for you to get what you need.

However, to make sure I'm providing good advice, could you describe your use case in greater detail?

**Comment by cggit** [comment]
I was populating a shortcode UI select box with post meta and needed the postID. I managed to get it by parsing the QUERY_STRING on 'after_setup_theme' and storing it to be available on 'init'. Not pretty but it works. Sounds like register_shortcode_ui will make it much easier. Awesome plugin.
