### ISSUE TITLE
Assest Management

### ISSUE THREAD

**Issue by hyyan** [wp-shortcake/shortcake#43]
Thanks for the great plugin , I like a lot.

What I like mostly is the ability to detect the shortcode , I have been using the ultimate-shortcode plugin
ui before but it lacks the shortcodes detect and it lacks support to :( .

There is still one think which I am unable to figure it , how to manage asset , what if my shortcode use a external css or js files , how to manage it , it is not really clear to me , any Idea ? 

I am not trying to compare here but in the ultimate-shortcode plugin there is filter to add css or js files 
can we have something like that for this plugin ? 

Regards

**Comment by danielbachhuber** [comment]
> what if my shortcode use a external css or js files , how to manage it , it is not really clear to me , any Idea ?

I assume you're referring to how to get the preview to work properly? Can you share some code examples for your shortcode?

**Comment by hyyan** [comment]
@danielbachhuber I think my shortcode is too complected to paste here and it depends on other plugin so it might not make sense so to make my question clear let us assume we are using the default example which comes with this plugin 

Now I want to write a css file and add rule for `pullquote` class how should I enqueue the css file ?

First I thought I should use `wp_enqueue_style` but that is not working with editor preview plus the style file will be loaded in in the front end even if the my shortcode is not used .

I think the plugin must provide a way "maybe a filter " which will detect if shortcode is used in the backend or frontend and add the style automatically and if the shortcode is never used it will do nothing , 

Don't you thing that this is must be a part of plugin's job or I am missing something here?

**Comment by danielbachhuber** [comment]
Thanks for the details — this clears things up.

Currently, there are [two actions](https://github.com/fusioneng/Shortcake/blob/master/inc/class-shortcode-ui.php#L192) you can use to dump whatever extra HTML, CSS or JavaScript you need into the preview:

```
add_action( 'shortcode_ui_before_do_shortcode', function() {
    echo "<link rel='stylesheet' href='/path/to/mystyle.css' type='text/css' />";
});
```

However, I'd like to see if we can come up with a more robust solution, which we'll track in #39
