### ISSUE TITLE
Is it ok to add_action at wp_loaded instead of init?

### ISSUE THREAD

**Issue by chrishoward-au** [wp-shortcake/shortcake#447]
I have a select field that shows a list of custom taxonomies. Here is the field def:

```
          array(
              'label' => 'Taxonomy (Optional)',
              'attr'  => 'tax',
              'type'  => 'select',
              'options'=>pzarc_get_taxonomies(true)
          ),
```

This failed to show anything when I was loading my shortcake code at init as per the dev plugin example.

I tried plugins_loaded and it still showed nothing. Then I tried wp_loaded and it now shows my custom taxonomies.

However, I wonder whether this will cause other problems.

BTW my taxonomy code was straight out of the codex example:

```
$taxonomy_list  = get_taxonomies( array(
                                      'public'   => true,
                                      '_builtin' => false
                                  ) );
```

**Comment by goldenapples** [comment]
> This failed to show anything when I was loading my shortcake code at init as per the dev plugin example.

The dev plugin is a bit out of date in that example. You can register the shortcode UI at the `register_shortcode_ui` hook, as of 0.5.0. This is a later hook, and should work for what you're trying to do here. The shortcode itself should probably still be registered at `init`, though...

**Comment by chrishoward-au** [comment]
Thank you. Yes that worked.
