### ISSUE TITLE
"Failed to load preview" showing all the time in visual editor

### ISSUE THREAD

**Issue by chrishoward-au** [wp-shortcake/shortcake#448]
Am getting the "Failed to load preview" message in the visual editor for shortcodes from Shortcake Bakery, and my own.

I'm ok with it not previewing, but could it show the relevant shortcode icon instead?

I have Shortcake 0.5.0, WP 4.4-alpha (same prob on 4.3 tho), and both single and multisite. PHP 5.3.29

Thanks

**Comment by chrishoward-au** [comment]
Have just discovered it's only when Shortcode Bakery is active. When it's not, it shows the shortcode in a clickable box.

**Comment by danielbachhuber** [comment]
It seems likely there's an error notice or something else happening. Can you look into your error logs to see if there's a relevant entry?

**Comment by chrishoward-au** [comment]
Ah! Indeed! Caught out by WP not allowing all errors to display. I do have mine set to display, but WP does subvert that sometimes.

However, it is there in the log!

Undefined variable: this in /Users/chrishoward/Dropbox/httpdocs/wpms/wp-content/plugins/shortcake-bakery/inc/class-shortcake-bakery.php on line 64

Thanks

**Comment by chrishoward-au** [comment]
I wonder if that's a PHP version thing... lemme see...

Yup. Switched to 5.4 and it now works.

**Comment by danielbachhuber** [comment]
I'm fixing in https://github.com/fusioneng/shortcake-bakery/pull/79 too
