### ISSUE TITLE
How do I add attributes that have no names?

### ISSUE THREAD

**Issue by chrishoward-au** [wp-shortcake/shortcake#449]
Some shortcodes have simple format of [shortcode value] 

as opposed to [shortcode attribute_name="value"]

I delved around but couldn't figure how to handle these in Shortcake.

And if I enter a Shortcake registered shortcode manually in that format, it strips out the value.

My own shortcode has this as it's nice simple shorthand for users. Which means, if I implement Shortcake, many shortcodes will break.

So, if there's already a way to handle these (I tried 'attr'=>'', 'attr'=false and 'attr'=>0 without luck) then let me know, otherwise, please add this feature!

**Comment by danielbachhuber** [comment]
Positional attributes aren't supported at this time #128

**Comment by chrishoward-au** [comment]
Doh! That makes things difficult for me. :/ Is it on the todo list?

**Comment by danielbachhuber** [comment]
> Is it on the todo list?

Eventually, yes.

**Comment by chrishoward-au** [comment]
K. I've made a workaround by creating an alias for my shortcode that I then use with shortcake. A little clunky, but safe.
