### ISSUE TITLE
Show (live) preview when adding item

### ISSUE THREAD

**Issue by stompweb** [wp-shortcake/shortcake#45]
It would be good if there was a preview (preferably a live preview) of the shortcode output that was being entered (in the instance that there was maybe 10-15 shortcodes). The would be good on sites with a lot of shortcodes so the user knew what they were producing. It also means the user doesn't have to add it and then view it in TinyMCE to see the output.

![screenshot 2014-11-11 15 32 02](https://cloud.githubusercontent.com/assets/1017511/4995313/f8fed918-69b7-11e4-910d-3f644ddcc6a8.png)

**Comment by mattheu** [comment]
+1 Thanks!

**Comment by danielbachhuber** [comment]
:+1:

**Comment by danielbachhuber** [comment]
:ship: :ship: :ship:
