### ISSUE TITLE
Can I replace the shortcode with an icon in the visual editor?

### ISSUE THREAD

**Issue by chrishoward-au** [wp-shortcake/shortcake#451]
G'day guys

My shortcode doesn't display a preview - and I probably don't really want it to either but I would like to display an icon instead of showing the shortcode when in the visual editor.

Is that possible?

**Comment by bruno-barros** [comment]
@qwertydude I use is_admin() to render a default icon for admin users.

**Comment by danielbachhuber** [comment]
`is_admin()` is your best bet for now. See #399 for other discussion.

Flagging this for some documentation.

**Comment by chrishoward-au** [comment]
Thanks. I must doing something wrong, coz I'm still just getting the shortcode rendered.

![image](https://cloud.githubusercontent.com/assets/129821/9718547/2cc47c0e-55c0-11e5-95d5-23465b1606bf.png)

I have this as the is_admin() code now in my shortcode function:

```
if (is_admin()){
  return '<img src="'.PZARC_PLUGIN_URL.'/assets/architect-logo-final-logo-only.svg" width=32 height=32>';
}
```

I must be missing something facepalmingly obvious!

Tested on PHP 5.3 to 5.6.

**Comment by bruno-barros** [comment]
I think the problem is Shortcacke need to render the code using `ob_start()` not returning the string.

**Comment by danielbachhuber** [comment]
> Thanks. I must doing something wrong, coz I'm still just getting the shortcode rendered.

Can you share the full code for your shortcode, so I can attempt to reproduce?

> I think the problem is Shortcacke need to render the code using ob_start() not returning the string.

Shortcodes should _return_, not echo, their values.

**Comment by bruno-barros** [comment]
OK, maybe I'm not totally sure, but I render the shortcode based on the example I saw on wiki section.

This is a shortcode I made: http://pastebin.com/BpHejP4d

**Comment by chrishoward-au** [comment]
Bruno: Yup, my shortcode takes the same form.

Daniel: erm... It's a very big plugin that displays content.

Here the gist of the shortcode:

```
ob_start();
do_action('arc_before_shortcode', $pzarc_blueprint, $pzarc_overrides, $pzarc_caller, $tag);
do_action('arc_do_shortcode', $pzarc_blueprint, $pzarc_overrides, $pzarc_caller, $tag, $additional_overrides, $tablet_bp, $phone_bp);
do_action('arc_after_shortcode', $pzarc_blueprint, $pzarc_overrides, $pzarc_caller, $tag);
$pzout = ob_get_contents();
ob_end_clean();
return apply_filters('arc_filter_shortcode', $pzout, $pzarc_blueprint, $pzarc_overrides, $tag);
```

As you can see, I am certainly using ob_xxxx and returning not echoing.

The shortcode is passed to the main routine for displaying the desired content. That could be sliders, grids or others. (This is the plugin homepage: http://architect4wp.com)

It's not a biggie if I can't get it displaying right in the visual editor.

**Comment by danielbachhuber** [comment]
Ok. From the code you've shared, it's hard to say what might be going wrong. It's something with your plugin and implementation, though.

**Comment by chrishoward-au** [comment]
Yep, no worries. Thanks for both you guys help.
