### ISSUE TITLE
Translation issue with apostrophe character 

### ISSUE THREAD

**Issue by btribouillet** [wp-shortcake/shortcake#456]
Hi,

It seems there is a problem with the french translation with apostrophe character .

![capture d ecran 2015-09-11 a 14 57 04](https://cloud.githubusercontent.com/assets/7518508/9815369/c2906b44-5895-11e5-802c-5cf1a1d1f692.png)

It should be "d'article"

**Comment by danielbachhuber** [comment]
Hm. Not sure where that's at in the UI. It seems like it's probably getting double-encoded, though.

Can you share a bigger screenshot, or do some debugging on your own?

**Comment by danielbachhuber** [comment]
Related #502

This is now fixed on master.
