### ISSUE TITLE
Insert Post Element Search filter sometimes omits items

### ISSUE THREAD

**Issue by bobbingwide** [wp-shortcake/shortcake#458]
The search facility misses out some matches.

I quite like the search box on the Insert post element dialog. 
But I'm not sure how it find matches. 
I've noticed that sometimes it fails to display what I consider to be matches. 

e.g. I have a number of shortcodes starting `bw_f`
If I type `bw_field` then I'd expect to see both `bw_field` and `bw_fields`
but `bw_fields` doesn't show until I type the `s`

If I just type `f` then the `bw_follow_me` shortcode does not appear in the list.

BTW: I've not looked at the code.

**Comment by danielbachhuber** [comment]
Search is based on the label: https://github.com/fusioneng/Shortcake/blob/fc72f8fe55d3d3fdc7861946bd548b443fa31bdc/js/src/controllers/media-controller.js#L29

What labels do you have assigned to each of those shortcodes?

I'm not sure it makes sense to match on the shortcode tag, as that's not present in the UI. We could also match on the description, however.

**Comment by bobbingwide** [comment]
the labels are simply the shortcode name.
Remember I'm approaching shortcake with a bent towards the text editor, where the shortcodes are blindingly obvious.

**Comment by khromov** [comment]
We've also observed this problem.
