### ISSUE TITLE
Setting shortcode inner content?

### ISSUE THREAD

**Issue by khromov** [wp-shortcake/shortcake#461]
Is it possible to set the inner content of a shortcode using Shortcake? For example:

`[example]hello[/example]`

So I'd like a `textarea` to represent the inner content (in this example "hello")

**Comment by danielbachhuber** [comment]
Yes, you can use the `inner_content` argument. See this code as an example: https://github.com/fusioneng/Shortcake/blob/master/dev.php#L82

**Comment by khromov** [comment]
@danielbachhuber Much appreciated!
