### ISSUE TITLE
Loading editor is slow with many Shortcake-enabled shortcodes

### ISSUE THREAD

**Issue by khromov** [wp-shortcake/shortcake#476]
Because each Shortcake triggers an AJAX call using the `do_shortcode` action, it gets really slow when loading up the editor with many Shortcake-enabled shortcodes.

Most of the time is spent loading up WordPress, so my suggestion for this is to put all shortcodes that need to be rendered in a queue and then send off a single AJAX call that will render all shortcodes at once and return them in a JSON structure as an array.

This would easily cut 2-300ms per shortcode for the preview to appear .

Not sure what the best way to defer the loading is, any thoughts @danielbachhuber ?

**Comment by danielbachhuber** [comment]
> so my suggestion for this is to put all shortcodes that need to be rendered in a queue and then send off a single AJAX call that will render all shortcodes at once and return them in a JSON structure as an array.

This is exactly what we want to do #371

**Comment by khromov** [comment]
:+1:
