### ISSUE TITLE
Icons misaligned in Safari

### ISSUE THREAD

**Issue by isGabe** [wp-shortcake/shortcake#481]
Looks like Safari is throwing a fit because [we didn't prefix `transform: translate(-50%, -50%)`](https://github.com/fusioneng/Shortcake/blob/e11c29f3051e29267a8129510f8d179bac058ee5/css/shortcode-ui.css#L32). 

<img width="1214" alt="screenshot 2015-10-01 15 04 38" src="https://cloud.githubusercontent.com/assets/1437322/10232436/62e6e272-684e-11e5-8ef6-245617a06b18.png">

I'm so used to working with Autoprefixer that it didn't even register when I was creating those styles in #478. Thankfully Safari will be dropping prefixes for that and many other things in v9. In the meantime, though, this should be fixed.

**Comment by goldenapples** [comment]
:stuck_out_tongue_closed_eyes:

**Comment by danielbachhuber** [comment]
:hammer:
