### ISSUE TITLE
Demo Plugin

### ISSUE THREAD

**Issue by Mte90** [wp-shortcake/shortcake#49]
I've create a gist for a demo plugin that use the code in the readme for try this plugin in a simple way https://gist.github.com/Mte90/cb8a0e37565d219062ec

PS: The screenshot in the readme refer to a fusion-pull-quote shortcode while in the demo code the shortcode is pullquote.

**Comment by danielbachhuber** [comment]
> I've create a gist for a demo plugin that use the code in the readme for try this plugin in a simple way

Thanks! I've added a link in the readme df2eada8aabcc70c7f3a8c06a6795e4697ea70f4

> The screenshot in the readme refer to a fusion-pull-quote shortcode while in the demo code the shortcode is pullquote.

Yeah, artifact of how we got this shipped. I don't think it's worth fixing.

**Comment by Mte90** [comment]
i've updated the snippet with the last example code :-).
