### ISSUE TITLE
Parse shortcodes with hyphens in attribute names

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#495]
WordPress 4.3 officially adds supports shortcodes with hyphened-attribute names, but its JS regex hasn't been updated yet.

Discussion: https://wordpress.slack.com/archives/feature-shortcode/p1444072546000024

From #490

**Comment by goldenapples** [comment]
Trac ticket: https://core.trac.wordpress.org/ticket/34191

**Comment by stevenvachon** [comment]
Anything being done about this, or is this fixed in 4.4+? My site is currently stuck on 4.3.2

**Comment by stevenvachon** [comment]
Finally updated to latest wordpress -- this issue is indeed resolved.
