### ISSUE TITLE
It seems that we need to have all atts for re editing a shortcode

### ISSUE THREAD

**Issue by chdenat** [wp-shortcake/shortcake#50]
My UC : I have already in my post a shortcode , let's say [Myshortcode] ...[/Myshortcode]
I've declared 2  additionals parameters inside my shortcode_ui_register_for_shortcode declaration , le 'color', 'size'.

If the shortcode is [Myshortcode color='....' size='....'] ...[/Myshortcode] I can open the edit window
If the shortcode is [Myshortcode] ...[/Myshortcode] I cannot open the edit window

It seems that all attributes  are mandatory for shortcake ... that is not the case IRL  as some are defaulted by contruct...

**Comment by danielbachhuber** [comment]
cc @mattheu

**Comment by danielbachhuber** [comment]
Fixed by #50
