### ISSUE TITLE
Cannot drag shortcaked shortcode 

### ISSUE THREAD

**Issue by chdenat** [wp-shortcake/shortcake#51]
Hello 

Maybe a feature request more than a bug.
When a shortcode have been inserted, it is not possible to move it through the article like images.

**Comment by danielbachhuber** [comment]
Yep, I don't believe we've addressed this yet.

**Comment by roborourke** [comment]
The same is true for all mce views such as embeds so maybe this is something for core. Only reliable way to do it would be to extend the toolbar buttons with a handle you can click and drag.

**Comment by danielbachhuber** [comment]
> Only reliable way to do it would be to extend the toolbar buttons with a handle you can click and drag.

This sounds like a good way to do it :) Something we could trial in Shortcake, and then contribute upstream.

**Comment by danielbachhuber** [comment]
Related core ticket: https://core.trac.wordpress.org/ticket/28003

**Comment by roborourke** [comment]
My initial experiments were unsuccessful - image dragging is a special case
in contenteditable elements. Dragging nested elements only really worked
with inline content. I'll add my findings to the trac ticket.

I'm going to try a different approach with simple up/down arrows.

## 

Robert O'Rourke
_mobile:_ +447816329424
_skype: *rob.o.rourke
*web:_ röb.co

**Comment by mattheu** [comment]
I've spoken to a few people about this - and it is indeed an issue in the core implementation of media views. 

I know that there is a plan to support views like this in TinyMCE - perhaps this is a reason that they have been reluctant to try and work around this in WordPress?

**Comment by kraftner** [comment]
Has anything changed now that https://core.trac.wordpress.org/ticket/28003 has landed?

**Comment by danielbachhuber** [comment]
> Has anything changed now

Not sure. Can you test?

**Comment by kraftner** [comment]
Sorry, wasn't clear. I have tested and although images with captions can be dragged now nothing has changed for shortcake views. What I was wondering is if this might have paved the way as I haven't understood yet where exactly the problem is.

**Comment by chdenat** [comment]
@danielbachhuber  I'm sure not ;)

**Comment by westonruter** [comment]
This seems like a key feature that would make the shortcodes behave like content blocks.

**Comment by mehigh** [comment]
Cutting and pasting (using keyboard shortcuts) is the only possible way to reorder in the visual editor view. Drag and dropping using a Move icon in the tooltip would definitely provide a better user experience.
Any pointers on whether there are any in-progress developments which might touch this feature? Or this needs to be fully developed on top of the plug-in?

**Comment by mattheu** [comment]
Yeah I'd love to support this. Thanks for linking to that trac ticket - it looks like it specifically refers to images being dragged, and will not just automatically work for all MCE views.

However could be a good start - i'll look into this.

**Comment by mattheu** [comment]
🎉 Support for this has landed in core as of https://core.trac.wordpress.org/changeset/37446!
