### ISSUE TITLE
Can classnames be added to attribute wrappers in the shortcake modal 

### ISSUE THREAD

**Issue by cggit** [wp-shortcake/shortcake#524]
In the shortcake modal, inside div.edit-shortcode-form-fields each attribute is wrapped in a classless div. /inc/templates/edit-form.tpl.php

It would be helpful to label these divs so they can be styled if needed.

Maybe something like.
shortcake-[shortcodeName]-[attributeName]

**Comment by khromov** [comment]
See: #479

**Comment by cggit** [comment]
Cool, I like that, but why not label the div above .field-block to make positioning easier?

**Comment by khromov** [comment]
It was harder to do because that div comes from the depths of Backbone. Also you can just use 'display: inline;' or similar on the outer div to position the inner one.

**Comment by cggit** [comment]
fair enough. maybe should include .edit-shortcode-form-fields > div{ display:inline; }
