### ISSUE TITLE
Release 0.6.0

### ISSUE THREAD

**Issue by mattheu** [wp-shortcake/shortcake#526]
- [ ] Write up release notes
- [ ] Release

Plan is to release this next week during the meeting at 19:00 UST.

**Comment by mattheu** [comment]
Draft release notes: https://docs.google.com/document/d/1sZ2bVO0easnyWGT53_NHJ35eWokl1frKA-wHQZpDJUU/edit?usp=sharing

**Comment by danielbachhuber** [comment]
:ship:
