### ISSUE TITLE
Some fields not being updated in v.0.6

### ISSUE THREAD

**Issue by jordif** [wp-shortcake/shortcake#546]
Some fields (such as checkbox and radio buttons) are not being updated when editing a shortcode.

The cause seems to be the following commit:

https://github.com/wp-shortcake/shortcake/commit/9f5890f3d204fadb3f74286704357e0dbb3f3bd5

(Rolling back to the previous array of events fixes this. Apparently the "input event" is not fired for checkboxes and radio buttons. I'm using Google Chrome on Linux)

Thanks,

Jordi

**Comment by danielbachhuber** [comment]
Closing in favor of #543
