### ISSUE TITLE
`$shortcode_tag` not defined in demo plugin wiki file

### ISSUE THREAD

**Issue by cliffordp** [wp-shortcake/shortcake#549]
Am I mistaken, or is `$shortcode_tag` not defined anywhere at https://github.com/fusioneng/Shortcake/blob/master/dev.php ?
Thanks.

**Comment by danielbachhuber** [comment]
It's not defined anywhere. Why would it need to be?

**Comment by cliffordp** [comment]
I guess I messed something up changing it into my own plugin (was significantly different, including using PHP classes). Thanks anyway.
