### ISSUE TITLE
Yoast SEO 3.0.1 Compatibility

### ISSUE THREAD

**Issue by vincio87** [wp-shortcake/shortcake#552]
Shortcode preview doesn't work with Yoast SEO v 3.0.1

![schermata 2015-11-19 alle 10 45 24](https://cloud.githubusercontent.com/assets/3018251/11267277/b775ccfe-8eaa-11e5-95dc-e90f2cd2ef5d.png)

**Comment by danielbachhuber** [comment]
Doesn't work in what sense? Are there JavaScript errors you can see? Can you upgrade to the latest version of Yoast SEO to see if it fixes your issues?

**Comment by vincio87** [comment]
No, there aren't any javascript errors.
I can't update Yoast plugin to the latest release because it corrupts the proper working of the shortcake plugin.

Example:

With **Yoast 2.x**
![yoast 2 x](https://cloud.githubusercontent.com/assets/3018251/11273739/4446ade0-8ed5-11e5-8905-b275e16f02aa.png)

With **Yoast 3.x** | Preview doesn't work
![yoast 3 0 1](https://cloud.githubusercontent.com/assets/3018251/11273752/5179fd1e-8ed5-11e5-8c64-0e4d881699f1.png)

**Comment by danielbachhuber** [comment]
Have you tried with Yoast 3.0.2? There were JS bugs in 3.0.1 that broke parts of the editor.

**Comment by vincio87** [comment]
I upgrade to the latest version (3.0.2) and there's a console error:

`Uncaught TypeError: Cannot read property 'value' of null`

Ya, **wp-seo-post-scraper-302.min.js** is the problem! :)

Thank you very much!
