### ISSUE TITLE
Co-Authors Plus is breaking shortcake

### ISSUE THREAD

**Issue by pbearne** [wp-shortcake/shortcake#553]
Hi

Not sure what is gong on here not seeing any errors

tested on trunk and 4.3.1

With shortcake bakery  0.1.0  ,Shortcake (Shortcode UI)  0.6.2  and Image-shortcake  0.1.0  (just in case its a combo problem)

if you activate Co-Authors Plus  3.1.2 shortcake stops working 

Shortcodes don't render and the tab is missing from add media

Paul

**Comment by danielbachhuber** [comment]
I can't reproduce, unfortunately.

> Shortcodes don't render and the tab is missing from add media

This sounds suspiciously like Shortcake has been deactivated. Can you confirm it actually is activated?

Do you see any JavaScript errors in your console?

**Comment by pbearne** [comment]
only Uncaught ReferenceError: $coauthors_loading is not defined

happy to share sceens ot show you

I can toggle by just deactiving/activating co-author

**Comment by danielbachhuber** [comment]
This is a bug in Co-Authors Plus https://github.com/Automattic/Co-Authors-Plus/pull/309

**Comment by pbearne** [comment]
video https://drive.google.com/file/d/0B5QczxsmCk1vTFIxc1BheUViT0E/view?usp=sharing
