### ISSUE TITLE
add information text to UI

### ISSUE THREAD

**Issue by pbearne** [wp-shortcake/shortcake#556]
HI Guys

I may have missed this, but I want ot put some instructions on the UI form but cant see a way to add them 

I am looking to do something like this

`'attrs' => array(
            array( 'type'   => 'info', 'html' => '<p> see <a href="xxx"> for more info</a></p>'
      )
)
`

I put it in the attrs as you might need to have more than one block

**Comment by danielbachhuber** [comment]
> I want ot put some instructions on the UI form but cant see a way to add them

This use case isn't supported yet. See these related issues:
- https://github.com/wp-shortcake/shortcake/issues/408
- https://github.com/wp-shortcake/shortcake/issues/386
- https://github.com/wp-shortcake/shortcake/issues/120

As one way to hack it, you could use the CSS `content` property to inject some text.
