### ISSUE TITLE
Alternate shortcode editing UX suggestions

### ISSUE THREAD

**Issue by pbearne** [wp-shortcake/shortcake#557]
I have been working on migrating my plugin author avatar to shortcake and have few of thoughts

I already have a shortcode creator that I also use for widgets which a couple of custom controls and a tabbed section due to a number of options

![image](https://cloud.githubusercontent.com/assets/46270/11337666/aae4ace8-91bc-11e5-9adb-d93e74a154fd.png)
this first control allows to pick and user or enter an email address and other allows you do drag the avatar to set the size
![image](https://cloud.githubusercontent.com/assets/46270/11337690/d4f5dd0e-91bc-11e5-8d28-53a187bca546.png)

this one popup creates 2 different shortcodes

I did really what to loose these features as I migrate so this led me to few suggestions

To migrate to the editing UI, I need to be able to add custom form elements
and/or
Add the ability to wrap groups of attrs into tabs in the form editor

If I don't migrate I would like to use the rending in tinyMCE

Allow us to pass false as the second parm and this removes the short from the form editor interface but still handles the rendering the edit/double click should just open a textarea with the shortcode to edit with a save button

![image](https://cloud.githubusercontent.com/assets/46270/11338262/23666f90-91c1-11e5-8620-59f0e0409dc4.png)

or/and

Allow us to pass string as the second parm and this is assumed to be a tingMCE command which gets wired to the edit and double click on the preview 

I realize these may be edge cases but in a community as big as WordPress edge case mount up 

I hope this makes sense and helps

I did have a look but could see these requested before in a way I hope I have missed the ability is already there so I can add shortcake support today.

Paul

**Comment by danielbachhuber** [comment]
> Allow us to pass false as the second parm and this removes the short from the form editor interface but still handles the rendering the edit/double click should just open a textarea with the shortcode to edit with a save button

Hm. Interesting idea.

I think we'll want to solve this in whatever way we end up solving #116. The current thinking is to have an API for providing a custom editing interface. We'll keep this use case in mind as we work on it.

**Comment by mattheu** [comment]
Yes allowing you to provide your own custom view for editing the shortcode would help you achieve this, and definitely something I'd like to do. 

I'm going to close this for now. Thanks for your input!
