### ISSUE TITLE
Feature Suggestion: Shortcode Tag Preview

### ISSUE THREAD

**Issue by nextgenthemes** [wp-shortcake/shortcake#558]
I have my own shortcode creator dialog build inside thickbox for [ARVE](https://nextgenthemes.com/plugins/advanced-responsive-video-embedder-pro/)  but will be switching to shortcake soon.

![bildschirmfoto vom 2015-11-25 19-49-14](https://cloud.githubusercontent.com/assets/1780826/11406492/c2bfceae-93ad-11e5-8b65-79882f7a1ea7.png)

It looks like this. I think the bottom where the insert/update button is shown for shortcake is perfect for a live preview of the generated shortcode tag. Also I would like to see a more compact layout. #557 Looks interresting.

For a start I think radios should be inline on big screens instead of stacked. If not done like in #557 with a preview on the right I think all labels should be on the same line as the input fields.

In general I think the spacings are just a bit too much.

**Comment by danielbachhuber** [comment]
Thanks for submitting your comments.

> I think the bottom where the insert/update button is shown for shortcake is perfect for a live preview of the generated shortcode tag.

Because Shortcake is intended to obscure the fact you're using shortcodes, displaying the shortcode in the editor doesn't fit the philosophy of the plugin.

Also, there's sufficient helper classes for you to style the form in a way that best fits your fields.

**Comment by nextgenthemes** [comment]
@danielbachhuber Could you tell me where I can find this helper classes to style the form like I need and how to apply them to the form?

Like I said I like to have the labels inline, radios inline and not so much vertical spacing between elements.

I found nothing documented here apart that I guess I could add classes to the inputs with 'meta' - 'class' during setting up the form.
