### ISSUE TITLE
Bug: Clicking the edit icon requires two clicks to open the Shortcake modal

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#559]
After the shortcake modal has been opened once, clicking the pencil icon on any post element in the TinyMCE editor requires two clicks to open the '{Shortcode} Details` frame of the media editor.

This is specific to this frame having been last open, and trying to open it again with the same or a different shortcode. I suspect that the `currentShortcode` property isn't set correctly when first trying to open that modal, or that it isn't unset on closing the `wp.media.editor` the first time, and this causes an error setting it later. 

I don't see any console errors or obvious causes for the issue.

**Comment by jesperbjerke** [comment]
this is the same bug reported here #501

**Comment by goldenapples** [comment]
Thanks! I knew I'd seen it brought up before, but couldn't find it by title. yes, it looks like the same bug, and your debugging there is a good start.

**Comment by danielbachhuber** [comment]
:hammer:

**Comment by minimaluminium** [comment]
Has this issue been fixed yet?

**Comment by goldenapples** [comment]
@sodbileg Yes, this issue was fixed with #560, and should be resolved in the master branch. We haven't cut a new release since then, so the problem exists in 0.6.2, the latest released version.

**Comment by oritiger** [comment]
@goldenapples Hi, I encountered the same issue. Are there any plan for the next release?
