### ISSUE TITLE
libdist, all files in one directory

### ISSUE THREAD

**Issue by soderlind** [wp-shortcake/shortcake#56]
Could you please put all files in one directory i.e.

```
/inc/class-shortcode-ui.php
/inc/templates/*
/inc/css/*
/inc/js/*
```

.. not sure if it should be named `inc` (maybe `shortcake`is better), but as it's now `js`and `css` have to be put in the plugin root directory.

**Comment by danielbachhuber** [comment]
Why?

**Comment by soderlind** [comment]
I'd like to keep "libraries" seperate from my code. I also use `css` and `js`, but they are for my plugin.

**Comment by joshlevinson** [comment]
`inc` immediately makes me think it's strictly for "includes", not for assets. If anything, an assets directory would be appropriate but only if the plugin author cares to. Not sure why this would affect anyone besides him.

**Comment by soderlind** [comment]
This is "just" a nice to have. I love what you've done, and I've learned a lot reading your code.

**Comment by danielbachhuber** [comment]
We probably won't be changing our directory structure, as I'd consider that [bikeshedding](http://en.wikipedia.org/wiki/Parkinson%27s_law_of_triviality)
