### ISSUE TITLE
Wordpress 4.4 compatibility

### ISSUE THREAD

**Issue by orest22** [wp-shortcake/shortcake#563]
Hello, plugin doesn't work with 4.4
`Uncaught TypeError: Cannot read property 'views' of undefined`

**Comment by danielbachhuber** [comment]
I'm unable to reproduce the error in WordPress 4.4.

To confirm, this error exists in a stock install of WordPress, with 2016 activated and no other plugins active?

If you do have other plugins active, can you try disabling them to see if the error goes away?

And, can you provide the full error, including line number reference?

**Comment by orest22** [comment]
Hi! Thanks for response. It could be closed. I had installed old Shortcake plugin.
