### ISSUE TITLE
[Question] Is there a way to identify each instance of a shortcode?

### ISSUE THREAD

**Issue by bruno-barros** [wp-shortcake/shortcake#565]
I have some instances of a shortcode on a page and I need to treat each instance with a diferent style.

How could I identify each instance as unique on a page?

**Comment by danielbachhuber** [comment]
There isn't a great way to do this at the moment, unfortunately. You'd need to write some custom JavaScript to keep track of the number of instances on your page, and then pass that context in the AJAX preview.

**Comment by davisshaver** [comment]
@bruno-barros You might be able to use CSS `nth` selectors to accomplish the desired effect.

**Comment by StaggerLeee** [comment]
Why not a select dropdown attribute with changeable CSS classes ?
Option 1 = Blue block
Option 2 = Green block...etc...just for info. And name it so Users cannot miss point. Later adapt CSS code to it.

**Comment by bruno-barros** [comment]
Yeah!
Simple and effective idea.
