### ISSUE TITLE
shortcode-ui.js // bug without inline-content

### ISSUE THREAD

**Issue by ivan79** [wp-shortcake/shortcake#570]
I have a problem with my shortcakes without inline-content, the tag don't close.
I resolve that putting this "else" on shortcode-ui.js

```
if ( content && content.length > 0 ) {
            template += "{{ content }}[/{{ shortcode }}]";
}
else {
            template += "[/{{ shortcode }}]";
}
```

**Comment by danielbachhuber** [comment]
> the tag don't close.

You actually don't need the tag to close — the shortcode parser works with `[shortcode]`

**Comment by ivan79** [comment]
Yes, but have you tried to put two with parameters together? In my case, one disappear.

**Comment by danielbachhuber** [comment]
> Yes, but have you tried to put two with parameters together? In my case, one disappear.

Sorry, I'm not sure I follow. Can you share more details, including steps to reproduce?
