### ISSUE TITLE
Wiki Select example wrong parameters

### ISSUE THREAD

**Issue by widoz** [wp-shortcake/shortcake#572]
Hi,

I don't know if this is the right place where signal a wiki incongruence but in the example for the select field type https://github.com/wp-shortcake/shortcake/wiki/Field-example:-Select the key value pair for the multiple is 'multiple' => false, rather than 'meta' => [ 'multiple' => false ]. May confuse someone about the right usage of the select args.

**Comment by mattheu** [comment]
I think the correct usage is indeed `multiple => false`. There is an issue around consistency of when `meta` is used to pass args and when it isn't, but I'm going to close this for now.

Can also just update the wiki if its incorrect.

**Comment by widoz** [comment]
Uhm, the second one worked. The 'multiple' => true doesn't make the select multiple.

Tested with shortcake Version 0.6.2

**Comment by cggit** [comment]
also ran into select multiple => true not working in 0.6.2

**Comment by widoz** [comment]
@cggit As I said, have you tried 'meta' => [ 'multiple' => false ]?
