### ISSUE TITLE
Shortcake Example (dev.php) not working

### ISSUE THREAD

**Issue by MALIK-0** [wp-shortcake/shortcake#574]
# Hi I'm currently looking into Shortcake cause I like the idea behind this project.

However I can't get the example code (https://github.com/wp-shortcake/shortcake/blob/master/dev.php) to work. (Also there is a missing php closing tag on the last line)

After installing the Plugin and adding the code of dev.php I can only see the "Shortcake With No Attributes" in the "Add Post Element" section. Any ideas?

I'm using Wordpress 4.4.2 and Shortcode-UI (Shortcake) 0.6.2

**Comment by danielbachhuber** [comment]
When you install Shortcake, you'll see both Shortcake and the dev plugin available for activation:

![image](https://cloud.githubusercontent.com/assets/36432/13110578/cbfebc54-d535-11e5-9ef2-8910b6e7a4cc.png)

The dev plugin includes two example shortcodes:

![image](https://cloud.githubusercontent.com/assets/36432/13110588/dba0a168-d535-11e5-9752-c01e2056f379.png)

Hope this helps.

**Comment by MALIK-0** [comment]
Hi Daniel,

thanks for the quick reply and sorry to post again. Before I installed the plugin via the Wordpress backend plugin section. Now I've downloaded the complete zip from this repro and installed it manually. On the attached screenshots you can see, that I've activated both plugins but only the "Shortcake With No Attributes" is visible.

Do you've any idea whats wrong?
![shortcake-1](https://cloud.githubusercontent.com/assets/7972402/13111853/773af0ea-d588-11e5-97aa-11ecd0f53e0e.JPG)
![shortcake-2](https://cloud.githubusercontent.com/assets/7972402/13111854/773e17e8-d588-11e5-867a-0570626bb404.jpg)

**Comment by danielbachhuber** [comment]
> Do you've any idea whats wrong?

No ideas, sorry. I'd need access to the environment to do some debugging. I might recommend deactivating any other plugins you've installed to see if there's a conflict.
