### ISSUE TITLE
Icon Picker Field

### ISSUE THREAD

**Issue by Pigrecolab** [wp-shortcake/shortcake#575]
I finally managed to find a simple way to create an icon picker field in shortcake.
I used [Balachuang Icon Picker](https://github.com/balachuang/IconPicker) with a small change and then I added this script in WP admin:
`jQuery(document).ready(function($) {

```
$(document).on('click',"#insert-media-button, .dashicons-edit", function () {

    $(document).one('focus',"input[role='fonticonpicker']", function () {
        fld= $('.media-modal-content').contents().find( "input[role='fonticonpicker']" )
        if (fld.length) {
            fld.after('<div id="picker"><img src="http://icons.iconarchive.com/icons/ampeross/smooth/128/Apple-Finder-icon.png" title="apple"><img src="http://icons.iconarchive.com/icons/ampeross/smooth/128/Apple-Mail-icon.png" title="mail"><img src="http://icons.iconarchive.com/icons/ampeross/smooth/128/Apple-Messages-icon.png" title="message"></div>');

            $('#picker').IconPicker({
                'onDisplayIconChange' : function(imgIdx, imgUrl,imgTitle){
                    imgTitle=imgTitle.replace(/\"/g, "");
                    fld.val(imgTitle).trigger('input');;
                }

            });

        }

    });


});
```

});`

Could please someone help me to replace the example icons with the fontawesome icons ? I found it on [this link](http://www.flaticon.com/packs/font-awesome)...
In title attribute should be the icon name (ex. fa-anchor )

For modified icon picker file: [download here](https://dl.dropboxusercontent.com/u/74800587/bala.IconPicker.jquery.zip)

**Comment by mattheu** [comment]
If you want to add a custom field type, I'd try to start by looking at the colour picker field, post select field etc  and try copying the patterns used there. 

I'd love to work a bit more on the documentation for this, and its something we have lots of ideas around. 

In the meantime - I'm going to close this ticket. Thanks for your feedback!
