### ISSUE TITLE
Clicking 'Edit Attachment' should not cause new page load

### ISSUE THREAD

**Issue by braders** [wp-shortcake/shortcake#576]
Firstly, I have been really enjoying using  this plugin, and it seems to provide a great interface for content editors. 

I have been using the `attachment` field type which is working great. One thing I have noticed however is that when the user edits the shortcode and then clicks 'Edit Attachment' a whole new page loads, breaking the user flow. 

It would be better if a new media modal was opened, so that the user could edit the attachment meta(alt text, title, description) whilst staying on the page. I think this would make a far better user journey.

**Comment by danielbachhuber** [comment]
What you're experiencing is WordPress' default behavior, not something introduced by Shortcake. There are historical reasons why "Edit Attachment" is still included on a second page. I'd encourage you to follow along on those conversations on [core Trac](https://core.trac.wordpress.org/).
