### ISSUE TITLE
Jquery UI Error

### ISSUE THREAD

**Issue by Pigrecolab** [wp-shortcake/shortcake#577]
Hello,
when I use the color type field I get in console: 

> Uncaught Error: cannot call methods on iris prior to initialization; attempted to call method 'toggle'

After that the insert media button doesn't work anymore.

Maybe it's caused by the last jquery ui update...

**Comment by movingSone** [comment]
Is this issue solved, I have tried to recreate it with latest version for shortcake and it is working fine. No errors inside WordPress.

**Comment by Pigrecolab** [comment]
Sorry, I was not very clear.. If you have a shortcake using the color picker you get that error only if you choose the color and then click on "Insert element" **without closing the color picker box** .
The problem is that after this error javascript is off... Could you please try again ? Thanks a lot

**Comment by mattheu** [comment]
👍 I was able to reproduce.

**Comment by goldenapples** [comment]
I remember seeing this issue in the past, but am not seeing it anymore. 

I tried to reproduce by: 
- opening a shortcode with a "color" attribute
- selecting a color using the color picker, but not closing the iris colorpicker
- clicking "Insert" (or "Update") for a shortcode which has already been sent to the editor

I don't see any error messages in the console. Can someone confirm if this is still an issue?

**Comment by isGabe** [comment]
@goldenapples I could not reproduce this with the same steps.

Unrelated note: I was playing around with the color picker and the hex color came out with the `#` URL encoded to `%23`, where `#444444` would output as `%23444444`.

`urldecode()` works to get it back to normal hex notation, but wondering if there's a better way to handle that.

**Comment by goldenapples** [comment]
> hex color came out with the # URL encoded to %23

Was that field registered with "encode => true"? That's the only way I can think of that would happen.

Now that I look through it, it looks like the example color field in the dev plugin is [set as url-encoded](https://github.com/wp-shortcake/shortcake/blob/master/dev.php#L216)... It'd be good to change that example, since it's not necessary to encode a hex value.

**Comment by isGabe** [comment]
> Was that field registered with "encode => true"? That's the only way I can think of that would happen.

It's funny I saw that `"encode => true"` and changed it to `false` and it did not seem to affect the output. But going back to it just now, I was able to toggle back and forth between encoded and unencoded with that setting. Go figure.

Agree that the example there should be set to `"encode => false"` to avoid confusing people like me :)

I can open up a wee PR for that.

**Comment by goldenapples** [comment]
Closing this issue, as it seems to be fixed from several reports on this thread. Feel free to reopen if anyone can reproduce with steps on a recent version of core and this plugin.

**Comment by trdevelopment** [comment]
I understand that this issue has been closed for al long time. However I'm encountering this exact issue. Is it possible to reopen this or do i need to create a new issue? 

I'm running the latest version of WordPress and Shortcake. I'm also using the Classic Editor and ACF plug-ins. Is there anyone else with this issue?

Steps to reproduce are the same as before:
1. opening a shortcode with a "colour" attribute
2. selecting a colour using the colour picker, but not closing the iris colour picker
3. clicking "Insert" (or "Update") for a shortcode which has already been sent to the editor
