### ISSUE TITLE
Deleting Shortcode UI Example plugin deletes Shortcake (Shortcode UI) plugin

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#586]
Why it is so ? There is not much logic in it. Deleting non-activated Example plugin can confuse some Users and they will be no aware main plugin is deleted too.

Best would be not to list it in plugin list. As it is not ordinary standalone plugin from WP perspective.

That not all is OK witness empty Shortcode UI folder as leftover.

![2016-03-23_003855](https://cloud.githubusercontent.com/assets/7382616/13971383/2042c682-f090-11e5-9644-70ce5054aa13.jpg)

**Comment by danielbachhuber** [comment]
> Why it is so ? There is not much logic in it.

Because they're bundled together in the same directory. This is core behavior, and not something that we can or want to change.

**Comment by StaggerLeee** [comment]
Why then deleting example plugin leave empty Shortcode UI folder ?
It is windows, WP never fails to delete folder on plugin deleting. And I was not inside that folder in Explorer, to be treated as "used".

Check it, not all is OK seems as.

Problem could be for some Users losing its time as I sad it above. Normally after this I got fatal error, Shortcode UI PHP code is not there anymore. And i went and saw Shortcode UI folder is still there. Initial belief was Shortcode UI PHP files are there, and lost some time on Google checking why is example plugin so important for whole functioning of Shortcode UI.
