### ISSUE TITLE
"caching" issue ?

### ISSUE THREAD

**Issue by soderlind** [wp-shortcake/shortcake#59]
Added Shortcake to https://github.com/soderlind/lorem-shortcode. When I edit the shortcode (change values), the shortcode is updated but not the content in tinymce.

**Comment by danielbachhuber** [comment]
Hm, can you share more details? Screenshots, reproduction steps, etc.

**Comment by soderlind** [comment]
http://screencast.com/t/KiVlmKir

code: https://github.com/soderlind/lorem-shortcode/blob/master/lorem-shortcode.php#L29

**Comment by danielbachhuber** [comment]
I think this was caused by #62. Can you pull master and retest?

**Comment by soderlind** [comment]
Yepp, https://github.com/fusioneng/Shortcake/pull/62 fixed this issue
