### ISSUE TITLE
Style elements not injected

### ISSUE THREAD

**Issue by stevenvachon** [wp-shortcake/shortcake#597]
If my shortcode generates:

``` html
<style> @media (max-width:40em) { div { background-image:url(...) } } </style>
<div>content</div>
```

the `<style>` is not injected and my preview looks incomplete.

**Comment by khromov** [comment]
I believe TinyMCE has special handling of script and style tags, see:
http://stackoverflow.com/questions/3037501/tinymce-is-removing-style-tags

I suggest using inline element style property instead, ie `<div style="">...` or enqueue your styles with `add_editor_style`:
https://developer.wordpress.org/reference/functions/add_editor_style/

**Comment by stevenvachon** [comment]
If I type the style tag manually in text/quicktags mode, it is part of the dom in visual mode.

**Comment by stevenvachon** [comment]
Also, I can't seem to get this to work (?):

``` php
add_action('init', function()
{
  // Add `<style>` support to TinyMCE (particularly for Shortcake)
  add_filter('tiny_mce_before_init', function($settings)
  {
    if (!isset($settings['valid_children']))
    {
      $settings['valid_children'] = '+body[style]';
    }
    else
    {
      $settings['valid_children'] .= ',+body[style]';
    }

    if (!isset($settings['extended_valid_elements']))
    {
      $settings['extended_valid_elements'] = 'style';
    }
    else
    {
      $settings['extended_valid_elements'] .= ',style';
    }

    return $settings;
  });
});
```

**Comment by khromov** [comment]
@stevenvachon Text mode and the way Shortcake adds the TinyMCE view are different. I would still advise you to use the aformentioned techniques to insert styling in the preview mode.

**Comment by stevenvachon** [comment]
Media queries do not work inline and I really don't think that generating multiple *.css files is the best solution.

**Comment by stevenvachon** [comment]
It turns out that it does inject the `<style>` elements, if I changed my logic. Which brings my real issue to #598
