### ISSUE TITLE
Shortcode Attributes Not Rendered in TinyMCE

### ISSUE THREAD

**Issue by zebulonj** [wp-shortcake/shortcake#60]
I'm seeing that the Shortcake view (preview) in Tiny MCE includes the shortcode "content," but is missing the shortcode attributes.

Using a clean development environment ([VIP Quickstart](https://github.com/Automattic/vip-quickstart)), I added the bleeding edge version of Shortcake, as well as the [demo plugin](https://gist.github.com/Mte90/cb8a0e37565d219062ec). I then added a "Pullquote" content item via the media interface. Returning to the post, the pullquote content showed in the embedded preview, but the source (citation) did not. When previewing the post outside the admin, the shortcode renders fine.

See attached screenshots.
![screen shot 2014-11-23 at 9 17 50 pm](https://cloud.githubusercontent.com/assets/1703671/5161176/5d24df44-7356-11e4-9069-848aadc41386.png)
![screen shot 2014-11-23 at 9 17 56 pm](https://cloud.githubusercontent.com/assets/1703671/5161177/5d26154e-7356-11e4-8deb-8e88b3899a6e.png)
![screen shot 2014-11-23 at 9 18 21 pm](https://cloud.githubusercontent.com/assets/1703671/5161178/5d2b16b6-7356-11e4-9d27-21d3ae4f7f56.png)

I did a bit of diagnostic work, and it appears that when fetched in the admin via the ajax method, the shortcode attributes are not being parsed correctly via `wp_parse_args(...)`. For example, the string 'source="The Dude"' is being returned as the value at index 0 in the associative array.

I'm happy to dig deeper, but was hoping someone else could verify this behavior before I do... in case it's my setup.

Thanks!

**Comment by roborourke** [comment]
I'm seeing this too with the wordpress-develop repo.

**Comment by danielbachhuber** [comment]
Caused by 3ad09a2459f1e81f6f2f2b268d43df2b80db942c. I think kses thinks its invalid attributes.
