### ISSUE TITLE
Twitter Bootstrap & Shortcake

### ISSUE THREAD

**Issue by raptor235** [wp-shortcake/shortcake#602]
Is there any initiatives out there to implement bootstrap into shortcake, so you can have all the bootstrap modules show up as shortcake modules?

**Comment by khromov** [comment]
Shortcake is framework-agnostic, I don't see a reason to tie itself into a frontend framework.

But you can easily build shortcodes to do this yourself.

**Comment by raptor235** [comment]
More clerification here -> https://github.com/wp-shortcake/shortcake/issues/603
