### ISSUE TITLE
Selecting post element in editor causes page jump

### ISSUE THREAD

**Issue by pravdomil** [wp-shortcake/shortcake#606]
![mov](https://cloud.githubusercontent.com/assets/2387356/15392530/e9c4e8e6-1dc7-11e6-8d02-5b32fbb95141.gif)

Try out this code:

``` php
shortcode_ui_register_for_shortcode('abc', ['label' => 'abc', 'listItemImage' => 'dashicons-carrot']);

add_shortcode('abc', function( $attr, $content, $shortcode_tag ) {
    $attr = shortcode_atts(['source' => '', 'attachment' => 0, 'page' => null], $attr, $shortcode_tag );
    ob_start();
    ?>
    <section class="pullquote" style="padding: 20px; background: rgba(0, 0, 0, 0.1);">
        <p style="margin:0; padding: 0;">
            <b><?php esc_html_e( 'Content:', 'shortcode-ui-example' ); ?></b><br>
            <b><?php esc_html_e( 'Source:', 'shortcode-ui-example' ); ?></b><br>
            <b><?php esc_html_e( 'Image:', 'shortcode-ui-example' ); ?></b><br>
        </p>
    </section>
    <?php
    return ob_get_clean();
});
```

And make few copies on blank page and try to select between elements.

Clean install no other plugins activated
WP v4.5.2
Shortcake v0.6.2
Chrome v50.0.2661.102

**Comment by pravdomil** [comment]
fixed by removing `editor.getBody().focus();` from includes/js/tinymce/plugins/wpview/plugin.js:100
and by forcing non gzipped version in includes/js/tinymce/tinymce.php

**Comment by mattheu** [comment]
👍 As discussed at WCEU - this affects the built in galleries too and isn't necessarily a Shortcake issue.

However I think we can turn your fix into a core patch and open a ticket on trac :)

**Comment by jfbon** [comment]
It's here https://core.trac.wordpress.org/ticket/28322

So fixed in trunk but it's not in the latest release.

**Comment by mattheu** [comment]
Thats great. I'm going to close this issue.
