### ISSUE TITLE
Render hook

### ISSUE THREAD

**Issue by marcin-lawrowski** [wp-shortcake/shortcake#616]
It would be great to have a hook that is triggered every time the layer shows up. It has to distinguish between shortcodes. The hook would be perfect to implement any custom add-ons on the interface, for example - when there is a need to add a button next to one of fields and implement its custom behaviour.

**Comment by goldenapples** [comment]
Hmm. Any update hooks registered on a shortcode's attributes get called on initially rendering the UI, and they have access to the shortcode model (albeit in a somewhat awkward way). What more would be required to make this work for your use case? Do we just need to namespace initial render events differently than update events?

**Comment by mehigh** [comment]
The `wp.shortcake.hooks.addAction` can be used to tie a function on a particular short-code attribute. Which means that if we need to run some script to all textareas for example (rich text editing is a need which happens to pop frequently), we can't do that without tightly coupling this with all of the occurrences of a textarea field inside this JS file, which would make it cumbersome to maintain in the long run.

I'm playing a bit with it and make a suggestion with a PR.

**Comment by mehigh** [comment]
@marcin-lawrowski 
This is now merged into core and you can hook into either `shortcode-ui.render_new` for when the layer shows up anew (after interacting with insert new post element) or `shortcode-ui.render_edit` when the layer shows up when editing an already existing element from page.
I believe this issue can be closed now.

**Comment by Goncalom** [comment]
Hi, I've noticed that this feature is not yet present on the stable, when can we expect this to be pushed to a new version, so it can be available on the wordpress website? Thanks

**Comment by mehigh** [comment]
Indeed it's been more than a year since the Wordpress SVN had been updated with the latest developments in this GitHub. It's a matter worth bumping up.

**Comment by goldenapples** [comment]
Resolved in #628, which will be in the next stable.
