### ISSUE TITLE
Attachment field hook

### ISSUE THREAD

**Issue by marcin-lawrowski** [wp-shortcake/shortcake#617]
I have noticed that the hook is not triggered on attachment field when user deletes the attachment.

**Comment by goldenapples** [comment]
Yup, that's definitely a bug. 

It's happening because there's a check in the `updateValue` method (which is where the hooks are triggered on other events) which returns early if there's no attachment set. We'll have to manually call `triggerCallbacks` in the `_removeAttachment` method.

**Comment by goldenapples** [comment]
Closing, resolved by #619.
