### ISSUE TITLE
Whats the future of this plugin?

### ISSUE THREAD

**Issue by nextgenthemes** [wp-shortcake/shortcake#629]
I am have plans to ship my next big version of [ARVE](https://wordpress.org/plugins/advanced-responsive-video-embedder/) with a UI powered by this plugin.

I noticed that the wordpress.org version is **12 month outdated**. I just wanted to ask why that is. Would it not make way more sense to let people there actually run the latest code or at least a newer version then 9 month old one when there are lots of improvements done here? I mean its described as beta / future testing. But there is nobody testing the new stuff if you do not update.

I think I even had a issue where I needed a newer version but I do not want my users to have to install a plugin from Github.

And excuse me for not searching for this information extensively but is there any information on how likely it is that this gets into core and how long it may take? And what if it will rejected? Will this plugin still be maintained?

**Comment by StaggerLeee** [comment]
Seems as it is stalled. First enthusiasm went out. Maybe they cannot agree with core people about future of this plugin.

**Comment by khromov** [comment]
From talking to @danielbachhuber I get the impression this plugin is in limbo at least until:
- There is a unified field API so that Shortcake won't have to create its own (This is being worked on by Weston Ruter amongst others)
- The new [shortcode roadmap](https://make.wordpress.org/core/2015/10/08/shortcode-roadmap-draft-three/) starts progressing (It seems to have stalled)
- The issues on whether to store data in shortcodes or a separate CPT is resolved.

We are currently using Shortcake actively and I don't see it being discontinued in the immediate future - what we have now works and is good enough for a lot of use cases.

**Comment by StaggerLeee** [comment]
Dont know all responsible developers. But sometimes it helps just to write one comment here or in forum and say hallo to people. It has not to be something tehnically, time demanding, not even support comment.

**Comment by nextgenthemes** [comment]
Thats really a bummer, I am disappointed that nobody seem to take care to at least update it to the latest version from here, alpha or not, stalled or not - having a plugin listed and promoted as "future testing" I was expecting more, again especially because there is actually new and improved code here that is not shared with most users.

I know what the issue was: Following #554 I think, I have this custom button opening my shortcode, but when I use the wordpress.org version it need 2 clicks, pretty serious bug, I cant expect my users to remember and do 2 clicks every time.

So I am thinking of shipping the 0.7.0-alpha (with the above fixed among others things I guess) within my plugin with http://tgmpluginactivation.com in fact I am already doing this with the beta my testers update with the github updater. I don't know if its allowed to ship zip files with another plugin inside my plugin to wordpress.org.

@mattheu, @danielbachhuber, @jitendraharpalani58, @goldenapples, @zebulonj (just picked the top5 committers) Would be great to hear something from you directly about this.

**Comment by zebulonj** [comment]
@nextgenthemes Thanks for tagging me into this conversation. I haven't had any involvement with this plugin in almost two years. Give me a few days, and I'll see what I can learn about its status.

**Comment by mattheu** [comment]
Yes we're still using this actively, and I do have some plans but other things have gotten in the way.

I recommend using the version from github for now, but should possibly look at doing another release and updating the version on .org

**Comment by goldenapples** [comment]
Should we seet up a chat to discuss what needs to be finalized to tag and release version 0.7.0, and perhaps some plans for the future?

**Comment by nextgenthemes** [comment]
I tried, updated the "10 months outdated" above to 12 Months now.

**Comment by goldenapples** [comment]
@nextgenthemes We're meeting over Slack to discuss what final tickets should be closed before releasing 0.7.0. If you're interested and able to attend, we'll be in the #feature-shortcode channel of Making WordPress Slack, Monday 2016-10-31 at 16:00 GMT.

**Comment by goldenapples** [comment]
I'm going to close this issue -- we have a new release out the door, and have made at least some progress on gardening the issue backlog and maintaining the code.

There's certainly still a discussion to be had about the future of the plugin, but I don't think a github ticket is going to be the best place for it. It would be good to begin more regular meetings to plan out future development and plans for a core merge proposal, if that's the route we decide to take.

**Comment by nextgenthemes** [comment]
@goldenapples Sounds not very good. Why would this Ticket not be a good place to inform people about decisions you still did not make?

Finally the update at least! Please don't do this bullshit useless release policy again. You probably have created the a record of the longest not updated **(1 YEAR+)** "feature testing" "beta" plugin ever. And the worst part there was actually new and fixed code rotting here on Github! Just push what happens here on Github to wp.org. If it breaks sites, so be it. Its a "Feature Testing" "Beta" plugin. People have to expect that! What you did there made no sense and I hope you don't repeat.

**Comment by StaggerLeee** [comment]
It is getting complicated. Github code v0.7.0 seems same as WP plugin directory code, just compared. Difference is some Github specific folders and files, seems as, nothing important for plugin.

I am more concerned dev.php plugin is constantly changing, evolving, and now half-finished. It has some image attachment code but only half of it, doesnt show anything in modal window.
