### ISSUE TITLE
Why is my term_select not displaying/working?

### ISSUE THREAD

**Issue by alicam** [wp-shortcake/shortcake#632]
This is my array for the registering of a shortcode/shortcake field:

`array(`
`'label'    => __( 'Select Customer Type', 'clearnetworks' ),`
`'attr'     => 'tax_customer_type',`
`'type'     => 'term_select',`
`'taxonomy' => 'tax_customer_type',`
`'multiple' => true,`
`),`

The custom taxonomy is NOT registered for the post that's being edited. It's a custom taxonomy that applies only to a custom post type that I'm trying to list on the page, via this shortcode.

But in this circumstance it's not displaying the select element on the Shortcode UI modal.

Is that because the taxonomy has to be "linked"/available to the "type" of the post type I'm editing??

If so, I think that's a mistake.

I'll keep testing but hoping someone can answer that quickly enough :)

A

**Comment by alicam** [comment]
My more general question is: how do I debug this?!

**Comment by alicam** [comment]
!!!BUMP!!!

**Comment by alicam** [comment]
OK RESOLVED.

It looks like wpackagist/composer is pulling down an INCOMPLETE version of this plugin. They're not synced properly.

For example, after a composer update/check, the file `inc/fields/class-field-term-select.php` is not there :(

Not sure how to fix that.

A

**Comment by goldenapples** [comment]
Ah, probably because we haven't released a new plugin version in a long time. We need to wrap up a couple issues to get 0.7.0 out the door, which includes the term_select field and several other enhancements.
