### ISSUE TITLE
"Insert Post Element" button beside "Add Media" button?

### ISSUE THREAD

**Issue by alicam** [wp-shortcake/shortcake#633]
I have added a button beside the standard WP "Add Media" button (on the admin edit page, der). I'd like it to do exactly the same thing (open the media modal), but I'd like it to automatically switch to the "Insert Post Element"/Shortcake screen.

I assume that means "hooking" into the backbone routing somehow?? I have really no clue and am hoping someone has done it.

Yes, this is kind of a vanity thing for my client, but it would be nice to get it right ;)

A

**Comment by goldenapples** [comment]
You can see example code in https://github.com/wp-shortcake/shortcake/pull/551. I think we'll likely expose something like this in the next plugin version, though there's some discussion yet to have on how and where.

**Comment by goldenapples** [comment]
Resolved via #551
