### ISSUE TITLE
listItemImage doesn't work for full image path

### ISSUE THREAD

**Issue by ajambrovic** [wp-shortcake/shortcake#635]
The render function in insertShortcodeListItem creates an HTML element if a dashicon is used, but doesn't do that for full image path - the path gets outputted. 

Processing:

```
var data = this.model.toJSON();
this.$el.attr('data-shortcode', data.shortcode_tag);

if (('listItemImage' in data) && 0 === data.listItemImage.indexOf('dashicons-')) {
    var fakeEl = $('<div />').addClass( 'dashicons' ).addClass( data.listItemImage );
    data.listItemImage = $('<div />').append( fakeEl ).html();
}
this.$el.html(this.template(data));
return this;
```

Template:

```
<div class="add-shortcode-list-item-icon">{{{ data.listItemImage }}}</div>
```

Proposed solution:

```
if ('listItemImage' in data) {
    if (0 === data.listItemImage.indexOf('dashicons-')) {
        var fakeEl = $('<div />').addClass('dashicons').addClass(data.listItemImage);
        data.listItemImage = $('<div />').append(fakeEl).html();
    } else {
        var fakeEl = $('<img src="' + data.listItemImage + '" />').addClass(data.listItemImage);
        data.listItemImage = $('<div />').append(fakeEl).html();
    }
}
```

**Comment by goldenapples** [comment]
Apologies for missing this issue. What I've always done is to pass a full image tag for `listItemImage` - see how it's done in Shortcake Bakery, for example: https://github.com/wp-shortcake/shortcake-bakery/blob/d25d6d3636f7fe5ce9127aa7fd35be85626ebf7a/inc/shortcodes/class-googledocs.php#L12

If you pass anything other than a string which begins with `dashicons-`, it'll just be used as-is for the list item image. I think this approach is much more flexible, as it allows you to use things like svgs or divs. The solution you're proposing would break that existing usage, so we'd need to think it through a bit more.

**Comment by ajambrovic** [comment]
Hi - after reading your and my comment, I realise I could have came to the same conclusion alone - I agree, the way you do it is much more flexible, and the change by Perturbatio reflects what I wanted to suggest, so this is resolved - thanks!
