### ISSUE TITLE
Shortcakes act as drag&drop when clicked on the new WP/TinyMCE

### ISSUE THREAD

**Issue by eBestPL** [wp-shortcake/shortcake#636]
Hi there,
Just noticed a bug after update to the latest Wordpress. I have also updated my TinyMCE Advanced plugin (tried downgrades, didn't help). Shortcake 0.6.2.

When you click on a shortcake and want to edit, it doesn't work. Instead the whole shortcake acts like drag&drop, but you only clicked once. 

It happens on every browser. 

The only workaround I figured out is to right click on it and then you are able to access the toolbar.

Please help!

**Comment by eBestPL** [comment]
It was a conflict with another plugin I have just fixed. This topic can be deleted.

Sorry.

**Comment by goldenapples** [comment]
Thanks for reporting and for troubleshooting!
