### ISSUE TITLE
Shortcake clashes with Advanced Custom Fields (ACF) plugin - Select 2 library

### ISSUE THREAD

**Issue by StaggerLeee** [wp-shortcake/shortcake#660]
I pasted all code from **dev.php** and ShortcakeDev shortcode gives blank modal window. 
JS error is below.

Not so small problem.

```
Uncaught Error: Option 'multiple' is not allowed for Select2 when attached to a <select> element.
    at String.<anonymous> (select2.js:930)
    at Function.each (jquery.js:2)
    at constructor.prepareOpts (select2.js:928)
    at constructor.prepareOpts (select2.js:2337)
    at constructor.init (select2.js:690)
    at HTMLSelectElement.<anonymous> (select2.js:3391)
    at Function.each (jquery.js:2)
    at jQuery.fn.init.each (jquery.js:2)
    at jQuery.fn.init.$.fn.select2 (select2.js:3378)
    at n.render (shortcode-ui.js:1762)
```

**Comment by StaggerLeee** [comment]
Exchange private mails developers between and find solution. Both plugins are very important.

https://support.advancedcustomfields.com/forums/topic/select2-conflict-with-awesome-support/#post-45959

Some temporary solution:

```
function my_acf_admin_enqueue_scripts() {
    wp_dequeue_script( 'select2');
    wp_deregister_script( 'select2' );
    wp_enqueue_style('select2', '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css');
    wp_enqueue_script('select2', '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js', '', '', false);
}
add_action('admin_enqueue_scripts', 'my_acf_admin_enqueue_scripts');

```

**Comment by StaggerLeee** [comment]
Better to keep it on post edit screen only for safety. Wordpress SEO plugin use this script, possibly many more.

```
/*Remove coflict between Shortcake Shortcode UI select2 script and ACF select2 script (different versions, ACF script removed)*/
function my_acf_admin_enqueue_scripts() {
    if( strstr($_SERVER['REQUEST_URI'], 'wp-admin/post-new.php') || strstr($_SERVER['REQUEST_URI'], 'wp-admin/post.php') ) {
    wp_dequeue_script( 'select2');
    wp_deregister_script( 'select2' );
    wp_enqueue_style('select2', '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/css/select2.min.css');
    wp_enqueue_script('select2', '//cdnjs.cloudflare.com/ajax/libs/select2/4.0.0/js/select2.min.js', '', '', false);
}
}
add_action('admin_enqueue_scripts', 'my_acf_admin_enqueue_scripts');
```

**Comment by goldenapples** [comment]
Will the ACF fields actually work with select2 version 4? From the work I had to do to update this plugin to work with the newest version of Select2, it seems unlikely that anything beyond a very basic implementation of Select2 which was originally written for an older version of the library will work with v4.

Since the library is not bundled in core, there's not much chance of a version being standardized in use across the whole WP ecosystem. Maybe a first step to take would be to evaluate all plugins in the plugin library which enqueue Select2, and check which version they're using.

Out of curiosity, which ACF plugin are you using that's using select2? I don't see it in the [base plugin](https://github.com/elliotcondon/acf) anywhere, although version 3.5.2 is enqueued [in the Pro version](https://github.com/wp-premium/advanced-custom-fields-pro/blob/9e0470fe52570a79c00e4d26f837c70bc03bef2b/assets/inc/select2/select2.js).

**Comment by StaggerLeee** [comment]
I sent them mail and they will take a look on it. On forum they say sorting is gone, but as I can see sorting is still there with 4.x versions. Did hard cache reset several times, different ways.
Yes, it is latest PRO version.

**Comment by goldenapples** [comment]
I spent a little bit of time looking into whether it would be feasible to build the version of select2 we're requiring into the browserify bundle, to encapsulate it and avoid conflicts with plugins which require alternate versions. 

However, I didn't get anywhere with this approach. Just owing to the way that jquery plugins are architected (attached as functions to the global `jQuery` object's prototype) it doesn't seem very feasible to load two different versions of select2 in one pageload. I found a couple of examples of people doing roughly similar things with select2 or other jquery plugins, but the only way I can see of doing that here is to bundle our own copy of jQuery as well, and initialize our copy of select2 on that local jQuery. This is probably possible, but seems way too hacky to maintain.

Is it worth maintaining two versions of this plugin for compatability's sake?

**Comment by StaggerLeee** [comment]
Took me few minutes to find solution and fix it. Seems as ACF select2 fields are no different than with version 3.x, So from this side problem is trivial. 

But it is not trivial when all users need to know how to add snippet to functions.php. On other side everyone doing Shortcake is for sure advanced enough to add that snippet.

But all this is workaround, and workaround for huge user base. Maybe to ask developers behind ACF politely to follow new select2 versions.

All this is more or less chit-chat when I have no clue what ACF uses from 3.x and exist not in 4.x versions.

**Comment by kshaner** [comment]
ACF added a new setting in version 5.5.0 to select (no pun intended) which version of select2 to enqueue.

```php
add_filter( 'acf/settings/select2_version', function( $version ) {
	return 4; // 3 or 4
});
```
