### ISSUE TITLE
Issue with select2

### ISSUE THREAD

**Issue by yanknudtskov** [wp-shortcake/shortcake#662]
The issue from https://github.com/wp-shortcake/shortcake/issues/646 still persists in version 0.7.0

**Comment by mladjom** [comment]
I was able to solve this by adding 
<pre>$min = '.full'; </pre>
in class-shortcode-ui.php on line 200

**Comment by goldenapples** [comment]
I noticed that... it looks like the only difference between the version of select2 in Customize Posts and here is that Customize Posts is loading Select2.full.js, which includes some back compat shims for methods which were removed from the 3.x branch of select2.

If enqueing that same file here is enough to make the two plugins work well together, that seems like a good fix to make.

**Comment by mladjom** [comment]
It seems that plugin is locking WooCoomerce products edit screen.
[https://wordpress.org/support/topic/version-0-7-0-interferes-with-woocommerce-products](https://wordpress.org/support/topic/version-0-7-0-interferes-with-woocommerce-products)
Even in WooCommerce settings wherever select2 is used select fields are hidden.

**Comment by mladjom** [comment]
I created pull request which at least temporary solves this  #664

**Comment by yanknudtskov** [comment]
awesome @mladjom :-)
