### ISSUE TITLE
Bug with ACF (pro)

### ISSUE THREAD

**Issue by Nuranto** [wp-shortcake/shortcake#671]
When editing an existing shortcode using UI in an ACF wysiwyg field, the shortcode is not updated. Instead, a new shortcode with the new values is inserted in post content field. 
(Which is hidden by ACF in our configuration). 
But the bug does not occurs systematically. It looks like if we click outside of the rendered shortcode, then click again on it, and edit, it works.

**Comment by Nuranto** [comment]
Could be related to #584

**Comment by goldenapples** [comment]
> Could be related to #584

It sounds like the same thing that's being reported there. Let's close this issue and work on it there.
