### ISSUE TITLE
Uncaught Error: No select2/compat/initSelection

### ISSUE THREAD

**Issue by hirejordansmith** [wp-shortcake/shortcake#683]
Hi,

I'm have an issue I can't seem to resolve unless I deactivate the Shortcake (Shortcode UI) plugin and trying to get to the bottom of it.

I am running WP 4.7 with 2016 theme for theme / plugin conflict testing

The only plugins I have installed at the moment are WooCommerce (v2.6.11) and Shortcode UI (0.7.0)

I also removed all of the actual Shortcode UI code so it's just the plugin itself as far as related code.

The problem is that all of the jQuery elements on single product pages and admin pages are breaking so no longer functional.

Any idea what this is related to? I don't see anyone else having the same issue when I review issues.

This is the full error:

Uncaught Error: No select2/compat/initSelection
    at callDep (select2.js?ver=4.0.3:215)
    at req (select2.js?ver=4.0.3:376)
    at select2.js?ver=4.0.3:190
    at Defaults.apply (select2.js?ver=4.0.3:4619)
    at new Options (select2.js?ver=4.0.3:4919)
    at new Select2 (select2.js?ver=4.0.3:5046)
    at HTMLInputElement.<anonymous> (select2.js?ver=4.0.3:5667)
    at Function.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:2)
    at a.fn.init.each (load-scripts.php?c=0&load[]=jquery-core,jquery-migrate,jquery-ui-core,utils,jquery-ui-widget,jquery…:2)
    at a.fn.init.$.fn.select2 (select2.js?ver=4.0.3:5664)

And it says the error is line 215 in this file 

https://darby.staging.wpengine.com/wp-content/plugins/shortcode-ui/lib/select2/js/select2.js?ver=4.0.3

Any help would be appreciated! I seriously love this plugin! :-)

**Comment by goldenapples** [comment]
I think that problem should be resolved on the master branch here. We have a new release that should probably go out soon to the plugin repository. 

Can you try downloading the plugin from here and see if it works?

**Comment by hirejordansmith** [comment]
Hi Nathaniel,

I downloaded stable version from Master branch from github and see the same issue. Looks like the same version that I'm currently seeing the issue with as well - 0.7.0. Is there a newer version than 0.7.0? Thanks man!

**Comment by goldenapples** [comment]
Hmm. Seems I was wrong in thinking that issue was resolved.

In version 0.7.0, we updated the select2 library we were using from the 3.5 branch to the 4.0 branch, to maintain compatability with plugins that were using the 4.0 branch. However, doing so broke compatability with some plugins that are still using certain features from the 3.5 branch. The master branch here, which will be released as 0.7.1 soon, switches to using the "full" version of select2 4.0.3, which includes compatability shims that allow at least some functionality from the 3.5.x branch to keep working. But there are some features in select2 3.5, like using `<input>` fields as multi-selects, that aren't supported even with the "select2/compat" shims. It looks like you've run into one of those conflicts.

If you downgrade Shortcake to a pre 0.7.0 version (like [0.6.2 here](https://downloads.wordpress.org/plugin/shortcode-ui.0.6.2.zip)) that was still using the older version of select2, your problem should go away. In the meantime, we'll have to figure out a solution for standardizing the libraries we use.

**Comment by pabowles** [comment]
Having the same issue that hirejordansmith described...Staying on version 0.6.2 for now.

**Comment by stormrockwell** [comment]
I can confirm this issue happens for me too with woocommerce

**Comment by yurii-diachenko** [comment]
Hi, the bug happens to me a well on woocommerce. Reverting the plugin back to 0.6.2 fixed the issue

**Comment by brandomeniconi** [comment]
I managed to create a [temporary patch](https://github.com/silverbackstudio/shortcake/commit/b6a6ba262597be04ab27cf4ce1eaa7f58bf494fc) that registers Select2 to a separate jQuery namespace to prevent conflict with other plugins.

**Comment by pySilver** [comment]
@goldenapples any news on this issue?

**Comment by stalukder03** [comment]
any update? please let us know.
best regards

**Comment by goldenapples** [comment]
I haven't had a chance to hack on this in a while. @brandomeniconi's hack above seems like a workaround that we could possibly expose in the plugin as an option that we could point people to in case they're having conflicts. Anyone want to have a go at trying to prepare a pull request for it?

**Comment by brandomeniconi** [comment]
I've used that hack on more than 10 WP installations (with WC and ACF Pro) and it's holding up well. I can try to make a PR from if you agree, but does the plugin has an options page? Or we just create a named constant that users can define in `wp-config.php`?

**Comment by goldenapples** [comment]
I'd say that a named constant, maybe something like `SELECT2_NOCONFLICT`, would be fine for enabling this feature - no reason to create an options page for this.

The main thing I'd like to see in a PR is to move the hack outside of the built select2.js script, and into scripts that we run before and after loading select2.js if no-conflict mode is desired. That way we can more easily track updates to the upstream plugin.

**Comment by brandomeniconi** [comment]
PR #702 ready. Sorry for the delay and non super clean code but I'm little busy right now. Open for suggestions :)

**Comment by goldenapples** [comment]
Resolved.
