### ISSUE TITLE
Conflict with Enhanced Media Library Plugin

### ISSUE THREAD

**Issue by kshaner** [wp-shortcake/shortcake#688]
There is javascript conflict with the enhanced media library plugin (https://wordpress.org/plugins/enhanced-media-library/developers/).

I suspect the error lives there and have filed a support ticket with their developer. https://wordpress.org/support/topic/conflict-with-shortcode-ui-plugin/

The error is ‘TypeError: n is undefined’ and occurs when you click Add Post Element or from within the media modal.  You are also unable to edit existing shortcodes.

I'm filing this here in case there is another type of workaround.  I'm currently downgrading Enhanced Media Library.

**Comment by goldenapples** [comment]
It looks like this was fixed in Enhanced Media Library plugin: https://wordpress.org/support/topic/conflict-with-shortcode-ui-plugin/
