### ISSUE TITLE
question, wrap existing content?

### ISSUE THREAD

**Issue by Hube2** [wp-shortcake/shortcake#693]
Looking over the documentation and examples I cannot find the answer to this but I'm beginning to expect the answer is no.

Can I create a shortcode for use with the plugin to wrap existing content in the editor?

**Comment by goldenapples** [comment]
Not currently, but it has been requested many times. Pull requests would be welcome, though!

**Comment by Hube2** [comment]
Thanks for the answer. I'll keep it in mind if I find some free time to add another project to my list.
