### ISSUE TITLE
Conflicts with WooCommerce

### ISSUE THREAD

**Issue by bostonchic** [wp-shortcake/shortcake#694]
I use this plugin as it's required by the ARVE plugin for shortcodes but on sites running WooCommerce, it renders WooCommerce useless on backend.  :(

**Comment by Tobias-Conrad** [comment]
@roborourke @danielbachhuber @thomasmb @glueckpress nice plugin.
i can confirm the issue: 
"breaking woocommerce backend",
woocommerce shipment tracking button 
and sent note to the customer (standard included in woo) button.

easy to test. just install woocommerce add an invoice and try to sent a note the customer of the invoice. you see the button is not working.

@bostonchic you can just disable "shortcode UI" plugin and copy the shortcode for a new video.
Videos already created will stay working.

**Comment by alexbudin** [comment]
Yes, this is a HUGE problem as it cannot be used with WooCommerce. It interferes with all its UI in the backend (WooCoomerce -> Settings)

When can we see a fix? As i made the mistake of updating this plugin and now everything in woocommerce is all over the place. I will have to roll back.

Im using this with ProfilePress and seems that ProfilePress does not work without this. So stupid to set dependencies on something that is badly coded.

Alex

**Comment by rogercoathup** [comment]
Can confirm -- v0.7 is breaking the WooCommerce JS on our sites as well

**Comment by goldenapples** [comment]
This should be fixed with 0.7.1, but may require setting the `SELECT2_NOCONFLICT` flag in your wp-config.

**Comment by Tobias-Conrad** [comment]
please show a notification if to set or set it by auto. thx
