### ISSUE TITLE
Backend conflict with ACF Pro

### ISSUE THREAD

**Issue by yumyo** [wp-shortcake/shortcake#696]
With **Shortcake** enabled, **Edit Filed Group** make the page completely unresponsive and crashes Chrome. 

It happens in conjunction with the **Repeater** and **Post Object Fields** at least. 

With just one of these fields the page hangs just for a couple of seconds. 3 Relationship and 5 Post Objects in the same group are enough to make the **Edit Field Group** page totally unusable. 
The issue disappear completely disabling **Shortcake**

WP 4.7.2
ACF PRO 5.5.2
Shortcake 0.7

The test was based on a clean **Twenty Seventeen** with no other plugin active except for **ACF PRO** and **Shortcake**.

**Comment by marcoboekestijn** [comment]
I have the same problem.

**Comment by alexbudin** [comment]
I can confirm this is happening on my end as well. Seems its conflicting with WooCommerce and ACF Pro so far.

We need an update that fixes this ASAP!

**Comment by goldenapples** [comment]
The recent update 0.7.1 fixes this.

If you're using Shortcake with other plugins that load select2, and you experience conflicts, the fix is to add the following line to wp-config.php:

`define( ‘SELECT2_NOCONFLICT’, true );`
