### ISSUE TITLE
JS errors out of the box when running WP 4.1-beta2-30587

### ISSUE THREAD

**Issue by MickeyKay** [wp-shortcake/shortcake#70]
I get the following JS errors when attempting to run the demo code on the latest release of WP Dev (4.1-beta2-30587). Any ideas?

Uncaught TypeError: Cannot read property 'id' of undefined
load-scripts.php?c=1&load[]=jquery-core,jquery-migrate,utils,jquery-ui-core,jquery-ui-widget,jquery…:157 Uncaught TypeError: Cannot read property 'id' of undefined

Uncaught TypeError: Cannot read property 'views' of undefined
shortcode-ui.js?ver=0.1:1047

**Comment by danielbachhuber** [comment]
Interesting. I can't reproduce. To confirm, you've disabled all plugins, are running TwentyFourteen, etc?

**Comment by MickeyKay** [comment]
So I think I found out what's causing this, along with an example. Try running underscores as your theme, and you should see the error.

It seems like this arises from a lack of `wp_enqueue_media()` being called on the admin page. For whatever reason, most themes seem to be triggering this call, however underscores doesn't. So it seems like perhaps you need to ensure your plugin is calling in the necessary scripts that are triggered by `wp_enqueue_media()`. What's weird is this would usually be handled by the default media button, if I'm not mistaken, so I wonder if somehow y'all are accidentally removing/overriding some default functionality. Please let me know if you have any insights. Thanks!

**Comment by MickeyKay** [comment]
Just as a follow up, I want to be clear on what the consequences of this are:

When using most themes, my shortcode renders as expected, like so (with no JS errors):
![image](https://cloud.githubusercontent.com/assets/3189678/5606973/16ad6efc-93fc-11e4-878d-33640eaab2e5.png)

However when I activate _s theme, it doesn't render as expected, instead I just see the shortcode:
![image](https://cloud.githubusercontent.com/assets/3189678/5606987/3ee31e80-93fc-11e4-9945-f3959f328497.png)

And I get the following JS errors:
![image](https://cloud.githubusercontent.com/assets/3189678/5606994/6cd9d25c-93fc-11e4-9abe-c0850b917334.png)

Note that the first two errors show on load, and the second two they show up later, apparently triggered via Ajax or some event listener.

**Comment by danielbachhuber** [comment]
> Try running underscores as your theme, and you should see the error.

Oh, this makes sense. We can fix by running `wp_enqueue_media()`

**Comment by MickeyKay** [comment]
Any idea why some themes work and some don't. It seems like calling
wp_enqueue_media() in the admin isn't something a theme should be doing
anyways. Well, either way this would be a good fix!

**Comment by danielbachhuber** [comment]
Actually, on second thought, we shouldn't be loading Post Elements unless the media library is loaded, as it's largely dependent on the media library.

`wp_enqueue_media()` is called by core when the post type supports thumbnails, loads the editor, etc. I suspect you've found some instance where this isn't the case.

**Comment by MickeyKay** [comment]
Well it's just pure underscores. You can see what I mean by installing
underscores and testing. The "Add Media" button utilizes the same scripts,
I believe (though I may be mistaken), and this works just fine with
underscores. So that leads me to believe it's something missing/erroneous
with Shortcake. Thoughts?

**Comment by danielbachhuber** [comment]
@MickeyKay Can you see if this was resolved by #118 ?
