### ISSUE TITLE
Suggestion, add post element to meta boxes

### ISSUE THREAD

**Issue by mfolkeseth** [wp-shortcake/shortcake#708]
We are using the media gallery to select images for our meta boxes. It would be great if Add Post Element could do the same. Then we'll have one big button for all media needs.

**Comment by goldenapples** [comment]
What would the expected outcome be? The "Add post element" workflow, as designed now, is tied to an editor instance, and inserts a shortcode at the current insertion point in the editor. If you went through that UI to add a shortcode in a meta box, what would happen after inserting it? How would that differ from a customizer instance?

**Comment by mfolkeseth** [comment]
I get you. This is a bad researched type of question. Closed.
