### ISSUE TITLE
The add post element button highjacks the active modal in the media modal

### ISSUE THREAD

**Issue by rianrietveld** [wp-shortcake/shortcake#712]
For a site I have the `add media button`, the `add post element` and 1 other button above the editor.
Once you selected `add post element` the active modal item stays 'Insert Post Element' if you select one of the other buttons. The active menu and the title stays 'Insert Post Element'.

**Comment by goldenapples** [comment]
Hmm. I thought this issue was fixed in #689, and that we were successfully resetting the modal state on closing to avoid that issue. Anyone else seeing this?

**Comment by rianrietveld** [comment]
Ok, if this has been merged 12 days ago, we may have not updated this yet on our site. I will check this ASAP.

**Comment by rianrietveld** [comment]
@goldenapples Thanks for pointing me to the proper issue, it turns out we need to update our current plugin version. 
cc @mattheu
