### ISSUE TITLE
Attribute field for editor?

### ISSUE THREAD

**Issue by mfolkeseth** [wp-shortcake/shortcake#713]
What about wordpress editor (wysiwyg) as attribute type?

**Comment by goldenapples** [comment]
There are a few plugins which add this as a field. 

For example: https://github.com/xwp/wp-shortcode-ui-richtext  (using Summernote editor)

Also [this gist](https://gist.github.com/rahulsprajapati/b1363acee3864cf344f4fec10d8cbc18) shows the rough outline of using a tinymce editor in a shortcake rich text field.
