### ISSUE TITLE
Wordpress 4.7.4 edit element issue

### ISSUE THREAD

**Issue by PhilipRowe** [wp-shortcake/shortcake#723]
Hello

Since updating to wordpress 4.7.4 I am having issues updating post elements. The edit dialog opens and you can make changes however when you click the insert / update button nothing is changed, instead a new element is added to the bottom of the editor and the old one is left untouched.

Steps to reproduce:
1. Add a new element to the page (this seems to be working ok and inserting where it should)
2. Click on the element in the visual editor and click edit
3. Make changes to the element
4. Click the insert / update button
5. The updated element isn't displayed, a new element has been added to the bottom of the page

**Comment by goldenapples** [comment]
I was able to confirm this in a couple different browsers. Looking into what's changed to cause this issue.

**Comment by PhilipRowe** [comment]
Thanks for confirming.

**Comment by sudar** [comment]
I am also facing the same problem. I can confirm that this happens in the latest version of Chrome, Firefox and Safari in Mac.

While searching the issue list I found an old issue #584. I am not sure if this has resurfaced.

**Comment by mehigh** [comment]
The bug is still present with the latest Wordpress trunk.

**Comment by goldenapples** [comment]
Did some bisecting this morning and was able to confirm the core commit that broke this functionality was [r40398](https://core.trac.wordpress.org/changeset/40398), which updated the version of TinyMCE in core to 4.5.6. Now to track down what specific changes in TinyMCE might be causing this issue...

**Comment by mehigh** [comment]
Maybe https://www.tinymce.com/docs/changelog/ could help?
Version 4.5.0 - November 23, 2016 seems like a big update adding many many features.

I would bet the previous version of TinyMCE in WP -> prior to that core commit was older than 4.5.0.

**Comment by sathyapulse** [comment]
I think TinyMCE version was updated from v4.4.3 to v4.5.6 in the WordPress core.

**Comment by alasdaircr** [comment]
Thaks for the update. I'm noticing a delay of sorts in that after Inserting a component, if I quickly select it and edit it, the button still says 'Insert' and confirming the modal causes another element to be inserted. From the second time onwards, the button shows 'Update' and the plugin works as expected.

I can create a video if that helps. Insert a component, quickly edit it, see if the confirm button shows Insert, or Update.

**Comment by alasdaircr** [comment]
This is with version 0.7.2

**Comment by alasdaircr** [comment]
It appears related to saving. If the post has not been saved (or autosaved) then the first click of the pencil edit icon does not perform an AJAX request and the modal code does not show Update.

**Comment by alasdaircr** [comment]
Also just noticed that sometimes clicking 'Add Post Element' causes the Update Dialog for the last inserted shortcake component to show :-(

I'm going to try and test this on an install with no other plugins.

**Comment by goldenapples** [comment]
I'm not able to reproduce the first problem. Can you give specific steps to reproduce the issue where clicking the pencil icon and editing a post element brings up the insert state rather than the update state? 

However, I was able to reproduce the second bug you noted: "sometimes clicking 'Add Post Element' causes the Update Dialog for the last inserted shortcake component to show". I'll open a separate issue (#726) to track that.

**Comment by alasdaircr** [comment]
@goldenapples will do,just installing a vanilla wordpress and will report back today

**Comment by alasdaircr** [comment]
Testing with a vanilla wordpress install the first time I edit a shortcode, immediately after inserting, I see the Update button briefly flash 'Insert Element', from then on the effect is not present. Without looking into the javascript it seems on my production site something is causing the transition from 'insert' mode to 'update' mode to stall somehow. But only the first time.

**Comment by sathyapulse** [comment]
The issue started appearing again in the new WP 4.8 RC it seems. Could anyone of you please check and confirm?
