### ISSUE TITLE
After editing post element and dismissing the modal, the next click on "Add Post Element" will bring up the previous state of the modal

### ISSUE THREAD

**Issue by goldenapples** [wp-shortcake/shortcake#726]
As noted in https://github.com/wp-shortcake/shortcake/issues/723#issuecomment-297661591:

In some conditions, the media modal state isn't being properly reset after editing a post element.

One way of reproducing this issue:

1. In a new post, insert a post element.
2. Click on the post element to select it and click the pencil icon to edit the shortcode
3. Dismiss the media frame by clicking the "X" link to close the modal.
4. Move the cursor to a different spot in the editor so nothing is selected.
5. Click the "Add Post Element" button to add a new post element. The state of the previously selected post element is shown, with no way to switch out to a different shortcode.

**Comment by mattheu** [comment]
I think I ran into this too. See https://github.com/wp-shortcake/shortcake/pull/728

**Comment by goldenapples** [comment]
Closing this issue, as #728 seems to fix the problem.
