### ISSUE TITLE
Modal preview doesn't resize to height of the embed

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#73]
See screenshot:

![image](https://cloud.githubusercontent.com/assets/36432/5387165/9b09248c-808a-11e4-9440-3ad883c99ebf.png)

Think we need some `postMessage()` to report the expected height.

**Comment by zebulonj** [comment]
Is it the iframe that doesn't resize? There is a mutation observer in there (modeled on the TinyMCE View code) that should resize the iframe. It worked with the YouTube embed.

—

**Comment by danielbachhuber** [comment]
Interesting. It is an iframe. I'll have to see how it differs from the YouTube embed.

**Comment by zebulonj** [comment]
Does it resize correctly in the editor itself (and if so, is it in an iframe there too)?

—

**Comment by danielbachhuber** [comment]
> Does it resize correctly in the editor itself (and if so, is it in an iframe there too)?

Yes, and yes.

**Comment by danielbachhuber** [comment]
Won't be an issue after #384
