### ISSUE TITLE
UI breaks when switching from one shortcode to another

### ISSUE THREAD

**Issue by jitendraharpalani58** [wp-shortcake/shortcake#74]
Noticed this today: 
![screen shot 2014-12-11 at 6 35 17 pm](https://cloud.githubusercontent.com/assets/7255301/5395253/9e3451b2-816c-11e4-90e9-02dc84b1c42f.png)

Steps to reproduce: 
Add New Post -> Add content -> Video -> return to list

**Comment by danielbachhuber** [comment]
This is actually a bug specific to our Select2 shortcode UI field, which is in the theme https://github.com/fusioneng/fusion-theme/issues/888
