### ISSUE TITLE
'select' field option doesn't retain value on subsequent edits

### ISSUE THREAD

**Issue by sudar** [wp-shortcake/shortcake#747]
Steps to replicate

- Set a shortcode with a 'select' field.
- Open the modal by clicking 'Insert Page Element' and select the shortcode
- Select a value from the dropdown and click insert.
- Now select the shortcode and then click the edit button
- The modal opens. All the other fields retain their value. Select field doesn't.

**Comment by goldenapples** [comment]
Is this happening with the current `master` head? It sounds like you might be coming uip against the issue that was just fixed in #745.

**Comment by antek83** [comment]
It happens to me as well, for select fields with just 2/3 options it is not a big problem. If you don't count that when u edit a field it automatically shows you the first option but does not let you select It. 

I've resorted in leaving the first option empty or a useless value, with a label of 'Select -whatever-' this way when reopnening a shortcode for editing the user is forced to select at least the second option and it will work. If the user does not touch it it will keep the previously selected value but it will show the text "Select" not perfect ux but better that showing a completely different option

**Comment by goldenapples** [comment]
Thanks for the report. Are you sure you're seeing this issue on the current `master` branch? I can't replicate it right now (though I did see that same problem before #745 was merged).

I'd just like to make sure this bug is fixed before cutting a new release.

**Comment by ocean90** [comment]
Confirmed that it's broken in 0.7.2 but fixed in the master branch.

**Comment by sudar** [comment]
Even I can confirm that it is broken in 0.7.2 but fixed in master.

**Comment by szepeviktor** [comment]
@sudar Please try the master branch.

**Comment by sudar** [comment]
Any idea when the next release of the plugin (with this fix) will be made?
