### ISSUE TITLE
How to add buttons to Shortcake UI postMediaFrame 

### ISSUE THREAD

**Issue by nicoladj77** [wp-shortcake/shortcake#754]
Hi, for a UI reason I would want to add buttons to the Shortcake UI postMediaFrame that, when clicked, perform a custom js action.

To add a button I can simply do:

```php
add_filter('shortcode_ui_shortcodes', function($shortcodes){
	$shortcodes['section'] = [
		'label' => 'Section',
		'shortcode_tag' => 'section',
		'listItemImage' => 'dashicons-forms',
		'attrs' => [],
	];
	return $shortcodes;
});
```

Which adds a button ( The fourth one )

![image](https://user-images.githubusercontent.com/333069/28345580-82cb9fb4-6c2b-11e7-8b87-c12ae822e098.png)

What I would like to do is that, when I click the new button, I run custom js code. What would be the cleanest way to do this?

**Comment by szepeviktor** [comment]
Enqueue your JavaScript file on post edit pages and add an event to the Section element with preventDefault()

**Comment by goldenapples** [comment]
Closing unless there are other questions here.
