### ISSUE TITLE
Term Select: Unable to remove term only replace

### ISSUE THREAD

**Issue by grappler** [wp-shortcake/shortcake#758]
When using `term_select` with `'multiple' => false,` there is no option to remove the selected term just to override it.

When using `'multiple' => true,` it is possible to remove the term but the value is then defined as null.

It would be good to be able to select "All terms".

This may apply to `post_select` too.

**Comment by goldenapples** [comment]
I was able to replicate. I think we should add a check in `Shortcode.formatShortcode()` to ensure that if a value is `null`, that attribute doesn't get output. Would that fix the issue?

> It would be good to be able to select "All terms".

I've been thinking this over and I have a few questions:

* How should this be represented? Should we just add an option with a value of -1 and a name of "All terms" (or "All {taxonomy_plural_name}" if only one taxonomy is selected?
* What does this mean in the case of multiple taxonomies?
* Is there anything that having an "All terms"/"All posts" option would enable from a user standpoint that wouldn't be possible just by removing all the selections? Usually when I've used these fields, I've used them as a filter - like "show related posts, but limit to these these terms". In all the use cases I've come up with, having no value in the field is just as useful as a "Select all" value would be.

**Comment by grappler** [comment]
> if a value is null, that attribute doesn't get output. Would that fix the issue?

Yes, this would fix it when `multiple` is enabled.

Removing the selection is only possible when `multiple` is enabled. It would work for me too just to have a blank option where nothing is selected.
