### ISSUE TITLE
Expose EditShortcodeForm View for reuse markup. i.e., in repeater field.

### ISSUE THREAD

**Issue by rahulsprajapati** [wp-shortcake/shortcake#773]
Hello, 
I need this view sui.views.EditShortcodeForm for reuse the markup with shortcode object. Can we please expose this view so that I can use it.

Can we add this code in edit-shortcode-form.js
https://github.com/rahulsprajapati/shortcake/blob/master/js/src/views/edit-shortcode-form.js#L82
> module.exports = sui.views.EditShortcodeForm = EditShortcodeForm;

@mattheu can you please take a look at this as we discussed earlier this one can help me in reusing markup with existing event binding.

you can check this my gist for reference, how I've used this for repeater.
https://gist.github.com/rahulsprajapati/066f61e97f934ff82dc6f77bc89bf522

cc: @goldenapples

**Comment by goldenapples** [comment]
Addressed by #783.
