### ISSUE TITLE
Add sorting arrows beside drag&drop reordering

### ISSUE THREAD

**Issue by szepeviktor** [wp-shortcake/shortcake#778]
On every shortcake there is an edit and a delete link/action.

Could we add a *move up one block-level element* and a *move down* action?
Is it possible in TinyMCE?

**Comment by szepeviktor** [comment]
When there are more than a screen-full amount of shortcakes I am not able to reorder them with the mouse.
Although it is possible with Cut, arrow keys and Paste.

**Comment by goldenapples** [comment]
Sounds like... Gutenberg.

And yes, it would be possible to build this interface, but I'm not sure if we want to go down the road of reimplementing gutenberg in the classic editor...

**Comment by szepeviktor** [comment]
I see!
