### ISSUE TITLE
JS error when adding Photo Gallery after clicking "Add Post Element"

### ISSUE THREAD

**Issue by joeyblake** [wp-shortcake/shortcake#811]
There is a JS error thrown when attempting to add a Photo Gallery *after* clicking the Add Post Element button.

To duplicate: 
Click "Add Post Element"
Click "Create Gallery"
Choose Photos
Click "Insert Gallery"

Error from the reset method on the MediaController because the shortcode is not a shortcode-ui code.

**Comment by goldenapples** [comment]
Should be addressed by #812.
