### ISSUE TITLE
Fieldmanager Media fields not able to be changed after insertion

### ISSUE THREAD

**Issue by davisshaver** [wp-shortcake/shortcake#83]
Steps to reproduce:
1. Insert shortcode that uses Fieldmanager Media attribute.
2. Click 'edit' button to open options modal.
3. Remove file.
4. Adding new file doesn't work.

**Comment by danielbachhuber** [comment]
Or sometimes it inserts a new shortcode instead of updating the existing one.

**Comment by mattheu** [comment]
PR opened. 

> Or sometimes it inserts a new shortcode instead of updating the existing one. 

Couldn't replicate this.

**Comment by danielbachhuber** [comment]
Shortcode UI inserting a new shortcode instead of updating the existing one is a consistent bug for me with the media field.

**Comment by danielbachhuber** [comment]
I've created an issue in the Fusion repo for the bug specific to the image comparison shortcode.
