### ISSUE TITLE
Shortcodes with dashes in attributes don't work in TinyMCE views

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#86]
Stuff breaks. @mattheu has more details.

**Comment by danielbachhuber** [comment]
@mattheu This is solved now, right?

**Comment by mattheu** [comment]
I'm happy to close.

Its solved in that core doesn't support them so I don't think we need to either. Although shortcake does seem to handle them fine.

**Comment by mattheu** [comment]
> Although shortcake does seem to handle them fine.

Actually - now we're using the shortcode regex from core - they don't work.
