### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#87]
We're getting pretty close to v0.1.0. Here's what we need to do to release:
- [x] Write a blog post detailing the shipped features and bug fixes: https://github.com/fusioneng/Shortcake/issues?q=milestone%3Av0.1.0+is%3Aclosed
- [x] Tag v0.1.0 on Github
- [ ] Create and push to WordPress.org Plugins profile

**Comment by soderlind** [comment]
.. and please add a CHANGELOG

**Comment by danielbachhuber** [comment]
Per conversation with @mattheu, punting on the WordPress.org release until I can produce an automated way to do that.

Release notes: http://next.fusion.net/2014/12/23/shortcake-v0-1-0-live-previews-fieldmanager-integration/

@soderlind there's a changelog in the release notes. We'll try to be more diligent about it in the future.
