### ISSUE TITLE
Missing button

### ISSUE THREAD

**Issue by MickeyKay** [wp-shortcake/shortcake#92]
Question: does Shortcake add the TinyMCE button that is shown in the example?

![image](https://cloud.githubusercontent.com/assets/3189678/5527768/3454439a-89b6-11e4-810f-a8a6f8617cff.png)

I've installed Shortcake and added the demo plugin - the shortcode editor functionality seems to be working just fine, however there's not shortcode insertion button like above. Is this functionality included in Shortcake, or does it need to be added separately?

**Comment by danielbachhuber** [comment]
> Is this functionality included in Shortcake, or does it need to be added separately?

It's actually available in "Add Media":

![image](https://cloud.githubusercontent.com/assets/36432/5527858/ecc40046-89b6-11e4-89ec-8da5a8cca0b1.png)

**Comment by MickeyKay** [comment]
Hmmm. That seems pretty counterintuitive to me. I mean, what if the
shortcode is for something like a custom heading or a block quote - neither
of which is really "media"? On the demo image there's a separate button for
inserting a poll - was this a totally separate plugin I'm seeing? Anyhow,
it'd be nice to be able to have either option.

**Comment by danielbachhuber** [comment]
> it'd be nice to be able to have either option.

I agree #94

**Comment by DevinWalker** [comment]
+1 it would be nice to add you own custom TinyMCE icons to click and open your own modal.
