### ISSUE TITLE
Support for editing shortcode inner content

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake#93]
If I have a shortcode like this:

```
[my-shortcode]Some awesome inner content[/my-shortcode]
```

It should be possible to edit that inner content.

**Comment by mattheu** [comment]
This is currently possible. Just add an attribute as normal with the name 'content'.

Perhaps this should be a bit more explicit....

**Comment by danielbachhuber** [comment]
> Just add an attribute as normal with the name 'content'.

Seems a bit magical — what if I had an attribute named "content"?

**Comment by mattheu** [comment]
Yeah agreed.

**Comment by jitendraharpalani58** [comment]
@danielbachhuber This issue is a bit unclear to me. We need add a new feature to edit content. 
Consider this for example: 

```
'lede' => array(
            'label' => 'Lede',
            'listItemImage' => 'dashicons-editor-textcolor',
            'attrs' => array(
                array(
                    'label' => 'Text',
                    'attr'  => 'content',
                    'type'  => 'textarea',
                ),
            ),
        ),
```

can we add another element with key as content

```
'lede' => array(
            'label' => 'Lede',
            'listItemImage' => 'dashicons-editor-textcolor',
                       'content' => array( 
                               'type' => 'String', // this can be reference/original another shortcode to support nesting. 
                               'value' => 'My test content',
                        ),
        ),
```

Am I thinking it right?

**Comment by mattheu** [comment]
Yes I think that would make things a bit clearer. Currently we just treat an attribute with the attr 'content'  as a speacial case.

**Comment by danielbachhuber** [comment]
We should remove `content` as a special case, and handle inner content in a proper manner.

**Comment by jitendraharpalani58** [comment]
@danielbachhuber what are you proposing ? 
I think having a `content=>{{value}}` pair is a good way to go as it gives an option to support nested shortcodes. Along with this, we can add some front end UI also to support inner content (to make it more intuitive). 

So there will be two ways of adding inner content
- via code (`content=>{{value}}`). Default value: true (will show the add/edit button)
- Add/edit content button on UI.

**Comment by danielbachhuber** [comment]
The current problem is that `content` is a valid shortcode attribute, but we can't use it. We should have a special flag for it instead.
