### ISSUE TITLE
Shortcode editor appearance doesn't match demo image

### ISSUE THREAD

**Issue by MickeyKay** [wp-shortcake/shortcake#96]
In the demo, this is the screenshot you've got for the demo quote shortcode:
![image](https://cloud.githubusercontent.com/assets/3189678/5562883/6a662034-8df8-11e4-87ae-3ba4a813de8c.png)

However when I use the demo straight out of the box, it doesn't match this at all and instead just looks like an fairly unstyled div (picking up my theme's basic styling):
![image](https://cloud.githubusercontent.com/assets/3189678/5562885/da58daa8-8df8-11e4-8e13-6c76cfedcc3b.png)

Did you add some extra styling to make the embed appear this way? Is there something else I'm missing?

**Comment by danielbachhuber** [comment]
> Did you add some extra styling to make the embed appear this way?

Yes — the screenshot depicts the styling of a pull quote for our theme, and those styles aren't included in the demo. You'll need to style the pull quote as you want it styled, both in your theme's style.css and the editor.css file you have enqueued for TinyMCE.
