### ISSUE TITLE
Question: status of tinymce-views branch

### ISSUE THREAD

**Issue by MickeyKay** [wp-shortcake/shortcake#97]
Hi there,

I just wanted to inquire about the status of the `tinymce-views` branch. It looks like this branch is attempting to incorporate TinyMCE insertion buttons for shortcodes, which is awesome!!! Also notice that the regular add media button doesn't seem to work when on this branch, so clearly still in development. Would love to know how progress is going. Thanks!
- Mickey

**Comment by danielbachhuber** [comment]
`tinymce-views` branch is stale by three months. We'll handle the TinyMCE button integration as a part of #94
