### ISSUE TITLE
Some changes in css to have better rendering

### ISSUE THREAD

**Issue by chdenat** [wp-shortcake/shortcake#98]
Hello,

Not an issue but maybe enhancement !

I'm playing around rendering into the editor and made some change to have better rendering with these css in my editor style css.
It suppresses the grey rectangle when I insert my shorcode and offers a better rendering. 
To edit or delete, I've to click on  the shortcode area and act as usual. 
I've played around and did not see any issue or fallback !

.wpview-wrap {
    min-height: 0px!important ;
}
.wpview-wrap {
    position: relative;
    border: 1px solid transparent;
}

**Comment by danielbachhuber** [comment]
Hi @christian-denat, is this still an issue?

**Comment by chdenat** [comment]
Daniel,
For me it's an enhancement, because the short code area is reduced to a bold line and it is ok for the shortcodes that require alignment on left or right.

**Comment by soderlind** [comment]
I tried to add this css, but I still can't align the shortcode using the align buttons in tinymce.

**Comment by soderlind** [comment]
I guess #169 will fix this :)

**Comment by danielbachhuber** [comment]
Let's keep #169 for tracking alignment.
