### ISSUE TITLE
Add mce editor to textarea field

### ISSUE THREAD

**Issue by chdenat** [wp-shortcake/shortcake#99]
Hello,

I've some shortcode used to insert formatted text (ads, list.., headers, paragraphs ....).

Is there any wordpress dedicated action I can launch with an "add_action" to force mce editor on textarea fields  in order to ease the editing ?

Another way is to integrate this with the textarea through a checkbox labelled add editor (or the stabdard button to switch from HTML to editor). When clicked (off by default), the textarea will be changed to editor area, else it remains pure textarea.

Thx

**Comment by danielbachhuber** [comment]
This isn't yet supported, but we can file it as an enhancement.

**Comment by milgrom** [comment]
This is something that would be great.  If we could insert a field that uses the default wp_editor then we could also create nested shortcodes along with other formatted text which I use when developing certain complex shortcodes that function inside of other shortcodes.

**Comment by CybMeta** [comment]
I also think a "editor" field type would be great, specially for shortcodes that outputs block elements.

**Comment by CybMeta** [comment]
I just saw this added for v0.3.0 milestone: https://github.com/fusioneng/Shortcake/issues/236

**Comment by danielbachhuber** [comment]
Closing in favor of #236
